gm_global_a_chassis.dbc
gm_global_a_lowspeed.dbc
gm_global_a_object.dbc
gm_global_a_powertrain.dbc

Volt gen 2 support, DBC files for https://github.com/commaai/openpilot/pull/104.

Volt gen 2 support

---

subaru_outback_2016_eyesight.dbc

Add brake position and steering angle.

Brake position and steering angle

---

subaru_outback_2016_eyesight.dbc

After some comments back, and some additonal messages being found, I'm submitting this PR.
SteeringAngle now includes limits, and units of measure (in degrees)
Added DoorOpen status for all 5 doors (didn't check if the hood needed another switch, yet)
Update CruiseButtons to be mutually exclusive

Update Subaru Outback

---

subaru_outback_2016_eyesight.dbc

This typo doesn't allow cabana to load the file.  Apologies.

Fixed a typo

---

honda_civic_touring_2016_can.dbc

Added counter and checksum to all defined messages, also corrected checksum and counter signals on 2:e4

Added counter and checksum to all defined messages

---

honda_civic_touring_2016_can.dbc

Added signal for when reverse lights are on/off

Reverse Lights on 0x326

---

honda_civic_touring_2016_can.dbc

ECON Mode On 0x221

---

honda_civic_touring_2016_can.dbc

Added gear 2

---

honda_civic_touring_2016_can.dbc

Removed wrong gear signal and renamed correct signal for Gearbox

Removed wrong gear signal

---

honda_civic_touring_2016_can.dbc

Added passenger airbag on/off signals. Might just be the indicator light and not actually turning off the airbags. Noted in  comments

Passenger Airbag

---

tesla_can.dbc

Updated Tesla DBC for our openpilot pull request

Lots of correction, thanks to cabana!

---

honda_civic_hatchback_ex_2017_can.dbc

This works in OP with no checksum errors.

Add stalk definitions and checksum fixes

---

gm_global_a_powertrain.dbc

Some messages can't be used for 'user gas' as they reflect ACC gas/regen commands too.

Volt's gas pedal only and combined gas/acc

---

gm_global_a_powertrain.dbc

Does not include 'trunk open' status.
Door open = 1
Seat belt latched = 1

Chevy Volt doors and belts status

---

gm_global_a_powertrain.dbc

- Adjust Volt's speed scaling
- Change Volt's brakes to reporting raw values

Chevy Volt tweaks

---

kia_sorento_2018.dbc

This adds support for 8 Speed Auto Tranismission used in Diesels
It also converts LKAS11 and LKAS12 into byte only messages
Based off hyundai_2015_ccan.dbc

Kia dbc - needed for Hyundai/Kia/Genesis port

---

gm_global_a_powertrain.dbc

These are the 2 bits that control the driver forward collision HUD and audible collision alert.
I can provide a cabana of this if proof is needed, PM me on slack (someone else's capture, don't want to disclose without permission)
+ @vntarasov

Add GM FCW dashboard alert

---

gm_global_a_powertrain.dbc

This reverts commit 98b5f66978694dcd2e9e92ab8a609da391b33ee1.

Revert "Add GM FCW dashboard alert (#123)"

---

gm_global_a_powertrain.dbc

Same as #123 but big endian to match the other signals this time.
@vntarasov

Add GM FCW Alert (Take 2)

---

generator/toyota/_toyota_2017.dbc

Will add more later and run the generator when finished.

Add more Sign recognitions

---

gm_global_a_object.dbc

This brings over all the front camera messages  The vast majority of these messages populate data, at least on my vehicle
the pedestrian tracking works too.  lots of cool info in here
hope this looks good.  compiles and works fine for me on Openpilot and Cabana

GM Object Front Cam Signals

---

gm_global_a_powertrain.dbc

added and fixed a couple signals.  new yaw rate and LKA torque.

new GM powertrain signals

---

mazda_cx5_gt_2017.dbc

Signed-off-by: Jafar Al-Gharaibeh <to.jafar@gmail.com>

Add Mazda CX-5 2017 GT

---

generator/toyota/_toyota_2017.dbc
lexus_is_2018_pt_generated.dbc
lexus_is_hybrid_2017_pt_generated.dbc
lexus_rx_hybrid_2017_pt_generated.dbc
toyota_avalon_2017_pt_generated.dbc
toyota_camry_hybrid_2018_pt_generated.dbc
toyota_chr_2018_pt_generated.dbc
toyota_chr_hybrid_2018_pt_generated.dbc
toyota_corolla_2017_pt_generated.dbc
toyota_highlander_2017_pt_generated.dbc
toyota_highlander_hybrid_2018_pt_generated.dbc
toyota_prius_2017_pt_generated.dbc
toyota_rav4_2017_pt_generated.dbc
toyota_rav4_hybrid_2017_pt_generated.dbc
toyota_sienna_xle_2018_pt_generated.dbc

https://photos.app.goo.gl/iN6rbsAaZ8sWQYNN7

Add wet  road symbol for RSA

---

nissan_2017.dbc

Tested on a Nissan X-Trail 2017

Nissan: Added nissan_2017.dbc

---

hyundai_kia_generic.dbc

TechInfo Diagram denote MFC unit as having BCA-R function. Profile and message characteristics match.
https://i.imgur.com/vANN6Ho.png

Correct Message ID on LKAS11

---

README.md

Impressive work on gathering all DBC data. Thanks for that! I was using your work as a base for development of signals handling in CANdevStudio project. CANdevStudio is done from a perspective of automotive developer that requries CAN simulations for his work rather than reverse engineer. Hovewer I think it may be useful for some of opendbc users.

Add reference to CANdevStudio in README file

---

gm_global_a_high_voltage_management.dbc

Put these together while working on an EV conversion, so I only have the charger and the becm.

Adding GM A High Voltage Management file.

---

nissan_2017.dbc

Submitting PR to clean up the Nissan DBC. Also updated message names to work with latest Nissan port.

Cleanup of Nissan DBC

---

nissan_2017.dbc

Added messages. Cleaned up endianness

---

nissan_2017.dbc

Fixing DriverTorque sign as lane change is not working properly

Fixed up sign on Driver Torque, added unit

---

can/common.cc
can/common.h
can/common.pxd
can/common_dbc.h
can/dbc_template.cc
can/packer.cc
can/process_dbc.py
subaru_crosstrek_2018.dbc
subaru_global_2017.dbc
subaru_outback_2015_eyesight.dbc

needs a matching openpilot PR before merging

CANPacker: Subaru checksum support 

---

mazda_cx5_gt_2017.dbc

Tidy up a few signals for the the Mazda port PR

Raw angle signal data for easy checksum calc, and one less gear bit

---

mazda_cx5_gt_2017.dbc

A simpler signal for better gear parsing
Signed-off-by: Jafar Al-Gharaibeh <to.jafar@gmail.com>

Mazda: Better GEAR signal tracking the gear stick rather than the gear box

---

can/process_dbc.py
subaru_forester_2017.dbc
subaru_outback_2015_eyesight.dbc

This PR adds Subaru preglobal gear values and disables automatic checksum generation for preglobal DBC files. Prerequisite for merging https://github.com/commaai/openpilot/pull/1489

Subaru preglobal update

---

subaru_crosstrek_2018.dbc
subaru_global_2017.dbc

This PR adds BSD_RCTA (blindspot detection system) messages for Subaru global and pre-global platforms

Subaru BSD_RCTA messages

---

.github/workflows/tests.yml

Docker layer caching in CI

---

hyundai_kia_generic.dbc

scc14 had comfort bands min/max set to zero, OP long can not work without this
also included some L-Can to spoon-feed the scc *emu*lation data and perhaps radard

add some L-CAN signals and update scc14

---

toyota_nodsu_pt_generated.dbc

Date and Time

---

hyundai_kia_generic.dbc

endian was flipped but start index was not https://github.com/commaai/opendbc/pull/175/commits/7950da9674e9576e7045e58abc76a9590efef778

Hyundai - fix LKAS12 CF_Lkas_Daw_USM

---

generator/toyota/_toyota_2017.dbc
lexus_ct200h_2018_pt_generated.dbc
lexus_gs300h_2017_pt_generated.dbc
lexus_is_2018_pt_generated.dbc
lexus_nx300_2018_pt_generated.dbc
lexus_nx300h_2018_pt_generated.dbc
lexus_rx_350_2016_pt_generated.dbc
lexus_rx_hybrid_2017_pt_generated.dbc
toyota_avalon_2017_pt_generated.dbc
toyota_camry_hybrid_2018_pt_generated.dbc
toyota_corolla_2017_pt_generated.dbc
toyota_highlander_2017_pt_generated.dbc
toyota_highlander_hybrid_2018_pt_generated.dbc
toyota_nodsu_hybrid_pt_generated.dbc
toyota_nodsu_pt_generated.dbc
toyota_prius_2010_pt.dbc
toyota_prius_2017_pt_generated.dbc
toyota_rav4_2017_pt_generated.dbc
toyota_rav4_hybrid_2017_pt_generated.dbc
toyota_sienna_xle_2018_pt_generated.dbc

Added description for CRUISE_STATE value 11 : 3 seconds waiting timer. Will switch cruise state to standstill (7) after 3 seconds.
Added description for CRUISE_STATE value 9 : set cruise speed higher.
Added description for CRUISE_STATE value 10 : set cruise speed lower.

Added CRUISE_STATE value 11 description (timer_3sec)

---

generator/toyota/_toyota_2017.dbc
lexus_ct200h_2018_pt_generated.dbc
lexus_gs300h_2017_pt_generated.dbc
lexus_is_2018_pt_generated.dbc
lexus_nx300_2018_pt_generated.dbc
lexus_nx300h_2018_pt_generated.dbc
lexus_rx_350_2016_pt_generated.dbc
lexus_rx_hybrid_2017_pt_generated.dbc
toyota_avalon_2017_pt_generated.dbc
toyota_camry_hybrid_2018_pt_generated.dbc
toyota_corolla_2017_pt_generated.dbc
toyota_highlander_2017_pt_generated.dbc
toyota_highlander_hybrid_2018_pt_generated.dbc
toyota_nodsu_hybrid_pt_generated.dbc
toyota_nodsu_pt_generated.dbc
toyota_prius_2017_pt_generated.dbc
toyota_rav4_2017_pt_generated.dbc
toyota_rav4_hybrid_2017_pt_generated.dbc
toyota_sienna_xle_2018_pt_generated.dbc

The unit is dependent on unit setting.
PS: Cabana currently doesn't parse the last comment's terminator correctly.

Add Toyota Odometer Reading to Toyota DBCs

---

tesla_can.dbc

From https://github.com/BogGyver/opendbc

Update Tesla DBCs

---

can/common.h
can/common_dbc.h
can/dbc.cc
can/packer.cc
can/parser.cc
can/process_dbc.py

- PlotJuggler uses dynamic structs, so added optional dependency to capnp struct files.
- Added CANParser which parses all messages and signals

Modified can parser to run it from PlotJuggler

---

generator/toyota/_toyota_2017.dbc
lexus_ct200h_2018_pt_generated.dbc
lexus_gs300h_2017_pt_generated.dbc
lexus_is_2018_pt_generated.dbc
lexus_nx300_2018_pt_generated.dbc
lexus_nx300h_2018_pt_generated.dbc
lexus_rx_350_2016_pt_generated.dbc
lexus_rx_hybrid_2017_pt_generated.dbc
toyota_avalon_2017_pt_generated.dbc
toyota_camry_hybrid_2018_pt_generated.dbc
toyota_corolla_2017_pt_generated.dbc
toyota_highlander_2017_pt_generated.dbc
toyota_highlander_hybrid_2018_pt_generated.dbc
toyota_nodsu_hybrid_pt_generated.dbc
toyota_nodsu_pt_generated.dbc
toyota_prius_2017_pt_generated.dbc
toyota_rav4_2017_pt_generated.dbc
toyota_rav4_hybrid_2017_pt_generated.dbc
toyota_sienna_xle_2018_pt_generated.dbc

Co-Authored-By: @arne182 <arneschwarck@gmail.com>

More TSS2 RSA symbol

---

hyundai_kia_generic.dbc

Taken from https://github.com/commaai/openpilot/blob/master/selfdrive/car/hyundai/carstate.py#L84

Define Hyundai gears in dbc

---

cadillac_ct6_powertrain.dbc
gm_global_a_powertrain.dbc

Pending tests:
- position or torque?
- does regen affect these signals?

GM brake pedal position sensors and normalized/scaled brake/decel signal.

---

generator/toyota/_toyota_2017.dbc
lexus_ct200h_2018_pt_generated.dbc
lexus_gs300h_2017_pt_generated.dbc
lexus_is_2018_pt_generated.dbc
lexus_nx300_2018_pt_generated.dbc
lexus_nx300h_2018_pt_generated.dbc
lexus_rx_350_2016_pt_generated.dbc
lexus_rx_hybrid_2017_pt_generated.dbc
toyota_avalon_2017_pt_generated.dbc
toyota_camry_hybrid_2018_pt_generated.dbc
toyota_corolla_2017_pt_generated.dbc
toyota_highlander_2017_pt_generated.dbc
toyota_highlander_hybrid_2018_pt_generated.dbc
toyota_nodsu_hybrid_pt_generated.dbc
toyota_nodsu_pt_generated.dbc
toyota_prius_2017_pt_generated.dbc
toyota_rav4_2017_pt_generated.dbc
toyota_rav4_hybrid_2017_pt_generated.dbc
toyota_sienna_xle_2018_pt_generated.dbc

for https://github.com/commaai/openpilot/pull/22626

Toyota PCS Off Signal

---

generator/toyota/_toyota_2017.dbc
lexus_ct200h_2018_pt_generated.dbc
lexus_gs300h_2017_pt_generated.dbc
lexus_is_2018_pt_generated.dbc
lexus_nx300_2018_pt_generated.dbc
lexus_nx300h_2018_pt_generated.dbc
lexus_rx_350_2016_pt_generated.dbc
lexus_rx_hybrid_2017_pt_generated.dbc
toyota_avalon_2017_pt_generated.dbc
toyota_camry_hybrid_2018_pt_generated.dbc
toyota_corolla_2017_pt_generated.dbc
toyota_highlander_2017_pt_generated.dbc
toyota_highlander_hybrid_2018_pt_generated.dbc
toyota_nodsu_hybrid_pt_generated.dbc
toyota_nodsu_pt_generated.dbc
toyota_prius_2017_pt_generated.dbc
toyota_rav4_2017_pt_generated.dbc
toyota_rav4_hybrid_2017_pt_generated.dbc
toyota_sienna_xle_2018_pt_generated.dbc

0 = off
1 = constant on
2 = blinking
3 = does nothing

PCS indicator signal is actually 2 bits

---

Dockerfile
SConstruct

See https://github.com/commaai/openpilot/pull/22756
https://github.com/commaai/cereal/pull/214 needs merged first to fix the tests since the build clones the cereal repo

enable wshadow

---

nissan_leaf_2018.dbc

Nissan Leaf: add user brake signal

---

ford_lincoln_base_pt.dbc

Used for lane centering in 2018+ vehicles.

Ford: Add LateralMotionControl

---

vw_mqb_2010.dbc

Improved signal and value enums conforming more closely to the authoritatively correct definitions.
Upon review/merge, I request corresponding bumps to openpilot (for Panda CI) and PlotJuggler.

VW MQB: Updated ACC_07 and TSK_06 signals and values

---

generator/toyota/_toyota_2017.dbc
lexus_ct200h_2018_pt_generated.dbc
lexus_gs300h_2017_pt_generated.dbc
lexus_is_2018_pt_generated.dbc
lexus_nx300_2018_pt_generated.dbc
lexus_nx300h_2018_pt_generated.dbc
lexus_rx_350_2016_pt_generated.dbc
lexus_rx_hybrid_2017_pt_generated.dbc
toyota_avalon_2017_pt_generated.dbc
toyota_camry_hybrid_2018_pt_generated.dbc
toyota_corolla_2017_pt_generated.dbc
toyota_highlander_2017_pt_generated.dbc
toyota_highlander_hybrid_2018_pt_generated.dbc
toyota_nodsu_hybrid_pt_generated.dbc
toyota_nodsu_pt_generated.dbc
toyota_prius_2017_pt_generated.dbc
toyota_rav4_2017_pt_generated.dbc
toyota_rav4_hybrid_2017_pt_generated.dbc
toyota_sienna_xle_2018_pt_generated.dbc

A simple correction of a comment so that it accurate describes the possible values.

Toyota: Correct Comment on Barriers Values

---

ford_lincoln_base_pt.dbc

This leaked DBC file was found on a public GitHub repo and contains all of the existing messages/signals and more. I have checked that it contains all of the messages used in the existing Ford code in the openpilot repo, although that car port uses the Ford Fusion DBC files anyway so this can be merged without worries of messages/signals being renamed.

Ford: update common dbc

---

generator/toyota/_toyota_2017.dbc
lexus_ct200h_2018_pt_generated.dbc
lexus_gs300h_2017_pt_generated.dbc
lexus_is_2018_pt_generated.dbc
lexus_nx300_2018_pt_generated.dbc
lexus_nx300h_2018_pt_generated.dbc
lexus_rx_350_2016_pt_generated.dbc
lexus_rx_hybrid_2017_pt_generated.dbc
toyota_avalon_2017_pt_generated.dbc
toyota_corolla_2017_pt_generated.dbc
toyota_highlander_2017_pt_generated.dbc
toyota_highlander_hybrid_2018_pt_generated.dbc
toyota_nodsu_hybrid_pt_generated.dbc
toyota_nodsu_pt_generated.dbc
toyota_prius_2017_pt_generated.dbc
toyota_rav4_2017_pt_generated.dbc
toyota_rav4_hybrid_2017_pt_generated.dbc
toyota_sienna_xle_2018_pt_generated.dbc

This signal is the LKAS status that is controlled by the steering wheel button.
Such could be used for things like toggling OP lateral so a user can use stock or OP cruise without OP's lateral control by pushing the LKAS steering wheel button.

Toyota: LKAS status on gauge cluster

---

generator/toyota/_toyota_2017.dbc
lexus_ct200h_2018_pt_generated.dbc
lexus_is_2018_pt_generated.dbc
toyota_corolla_2017_pt_generated.dbc
toyota_nodsu_hybrid_pt_generated.dbc
toyota_nodsu_pt_generated.dbc
toyota_prius_2017_pt_generated.dbc
toyota_rav4_2017_pt_generated.dbc
toyota_tssp_hybrid_generated.dbc
toyota_tssp_pt_generated.dbc

That was quick! 🔫🤠
Here's a screenshot of the signals (when the car is off):

Toyota: add comment for LOCK_STATUS signal

---

generator/toyota/_toyota_2017.dbc
generator/toyota/_toyota_nodsu_common.dbc
generator/toyota/lexus_ct200h_2018_pt.dbc
generator/toyota/lexus_is_2018_pt.dbc
generator/toyota/toyota_corolla_2017_pt.dbc
generator/toyota/toyota_nodsu_hybrid_pt.dbc
generator/toyota/toyota_prius_2017_pt.dbc
generator/toyota/toyota_rav4_2017_pt.dbc
generator/toyota/toyota_tssp_hybrid.dbc
generator/toyota/toyota_tssp_pt.dbc
lexus_ct200h_2018_pt_generated.dbc
lexus_is_2018_pt_generated.dbc
toyota_corolla_2017_pt_generated.dbc
toyota_nodsu_hybrid_pt_generated.dbc
toyota_nodsu_pt_generated.dbc
toyota_prius_2017_pt_generated.dbc
toyota_rav4_2017_pt_generated.dbc
toyota_tssp_hybrid_generated.dbc
toyota_tssp_pt_generated.dbc

Toyota: sort messages by address

---

can/parser_pyx.pyx

Reduce repeated dictionary creations when initialize CANDefine class.

Reduce repeated dictionary creations

---

can/common.pxd
can/common_dbc.h
can/parser.cc
can/parser_pyx.pyx

CANParser: remove configurable default values

---

hyundai_kia_generic.dbc

Thanks @gregjhogan! Look good to merge?
From comment here: https://github.com/commaai/openpilot/pull/23745#issuecomment-1035963704

Hyundai: add definitions for ACCMode

---

hyundai_kia_generic.dbc

based on parsing from firmware

hyundai: fix TCS13 signals

---

luxgen_s5_2015.dbc
volvo_v40_2017_pt.dbc

so these work when trying to view them in PJ

DBCs: fix duplicate messages

---

vw_golf_mk4.dbc

English translation as field comment as suggest in #652

vw_golf_mk4: translate signals to english as comments

---

vw_golf_mk4.dbc

vw_golf_mk4: translate signals to english as comments episode 2

---

kia_ev6.dbc

Splitting out common definition updates from #673

Hyundai CAN-FD DBC updates

---

can/common.h
can/parser.cc
can/parser_pyx.pyx

Just a refactor, does not change behavior

CANParser: move can valid threshold into parser

---

.pre-commit-config.yaml
generator/test_generator.py

pre-commit: check generated DBC files

---

hyundai_kia_generic.dbc

Add manumatic gear signal for CAN HKG.
route ID: `36e10531feea61a4|2022-09-07--09-44-23--13`

Hyundai: Add Manumatic/Paddle Shifter signal

---

hyundai_kia_generic.dbc

required for https://github.com/commaai/openpilot/pull/25027

hyundai: fix FCA11 checksum and counter

---

can/common_dbc.h
can/dbc.cc

related to https://github.com/commaai/openpilot/pull/26098

CANParser: parse DBC from stream

---

hyundai_canfd.dbc

the chime, speed change indicator and sound will be used downstream with SunnyPilot. The icons (arrow up and down) might be useful in the future

CAN-FD HGK - additional icons and chime from cars dash

---

generator/toyota/toyota_nodsu_pt.dbc
toyota_nodsu_pt_generated.dbc

used in https://github.com/commaai/openpilot/pull/26687

Toyota: add steer_unavailable states

---

generator/gm/gm_global_a_powertrain.dbc
gm_global_a_powertrain_generated.dbc

Message's rate is very close to what's shown on the Bolt!

GM: add cluster speed signal

---

vw_golf_mk4.dbc

Fixes many messages, some of which are used as feedback to ACC and "Follow-to-Stop" function.

VW PQ: corrections to EPB_1

---

vw_golf_mk4.dbc

A bit more of the same - English translation as comments

vw_golf_mk4: a bit of progress

---

hyundai_canfd.dbc

Adds more signals and comments for doors/seatbelts/drive mode/local time/HVAC.

EV6 dbc updates

---

mazda_rx8.dbc

subject line says it all; I've tried to follow the good practices guidelines specified in README.md

Mazda: add RX-8

---

generator/toyota/_toyota_2017.dbc
toyota_new_mc_pt_generated.dbc
toyota_nodsu_pt_generated.dbc
toyota_tnga_k_pt_generated.dbc

Just to label one of the few messages left undefined from the camera. seems plausible looking at a 2023 RAV4 and 2022 Camry night drive

Toyota: add auto high beam message from camera

---

generator/toyota/toyota_nodsu_pt.dbc
toyota_nodsu_pt_generated.dbc

split from https://github.com/commaai/opendbc/pull/877

Toyota: update an LTA signal name

---

generator/toyota/toyota_nodsu_pt.dbc
toyota_nodsu_pt_generated.dbc

has no affect on driving, and because it's region specific, it may just describe if LTA is available

Toyota: add LTA comment for SETME_X1

---

can/tests/__init__.py
can/tests/test_dbc_exceptions.py
can/tests/test_dbc_parser.py
can/tests/test_packer_parser.py

split from https://github.com/commaai/opendbc/pull/888

tests: global constants

---

can/packer_pyx.pyx

CANPacker: don't track size

---

can/common.h
can/common.pxd
can/packer.cc
can/packer_pyx.pyx
can/tests/test_packer_parser.py

split from https://github.com/commaai/opendbc/pull/884
resolve https://github.com/commaai/opendbc/issues/500

CANPacker: refactor to avoid undefined signals

---

vw_golf_mk4.dbc

AWV_only signal length is 1 (not 4)

VW PQ: AWV_only signal fix

---

generator/subaru/_subaru_global.dbc
generator/subaru/subaru_global_2017.dbc
subaru_global_2017_generated.dbc
subaru_global_2020_hybrid_generated.dbc

infotainment is used to forester 2020 hybrid, so move this message up to _subaru_global

Subaru: move infotainment up

---

hyundai_canfd.dbc

**Prerequisite of**
- https://github.com/commaai/openpilot/pull/29658

Hyundai CAN-FD HDA2: specify signals to suppress LFA

---

generator/subaru/_subaru_preglobal_2015.dbc
subaru_forester_2017_generated.dbc
subaru_outback_2015_generated.dbc
subaru_outback_2019_generated.dbc

ES_RPM -> ES_Status to match global
name signals within ES_Distance and ES_Brake to match global

Subaru: preglobal normalize signals to global

---

can/parser_pyx.pyx

do not build value maps for all dbc messages.

parser_pyx: build value maps for requied messages

---

generator/gm/gm_global_a_powertrain.dbc
gm_global_a_powertrain_generated.dbc

EBCM=Electronic Brake Control Module

GM: annotate source ECU for EBCM message

---

can/tests/test_define.py
generator/honda/honda_civic_touring_2016_can.dbc
honda_civic_touring_2016_can_generated.dbc

Not sure if this value is also the same on other Honda's, left on the civic for now

Honda: new EPS faulted value

---

can/parser.cc
can/tests/test_packer_parser.py

Matches panda's behavior exactly, and solves a mismatch in https://github.com/commaai/openpilot/pull/30443

CANParser: clip `counter_fail` to the max

---

vw_golf_mk4.dbc

VAG focusing on TCU

---

.github/workflows/tests.yml

it pulls the cache on mine (https://github.com/bongbui321/opendbc/actions/runs/8015385821/job/21895470467)

CI: enable docker cache pull

---

can/SConscript

for: https://github.com/commaai/openpilot/pull/31621

scons: export opendbc_python

---

vw_mqb_2010.dbc

VW MQB: add adaptive cruise signal

---

can/packer_pyx.pyx
can/parser.cc
can/tests/test_packer_parser.py

openpilot PR: https://github.com/commaai/openpilot/pull/33146

deprecate busTime

---

.github/workflows/tests.yml
Dockerfile

- copy into container and compile opendbc during docker build step, more similar to msgq. no state from mounting a volume. for: https://github.com/commaai/opendbc/pull/1069
- test_generator is ran in: pytest, pre-commit, and special step. remove special step

new docker image structure

---

opendbc/can/packer_pyx.pyx
opendbc/can/tests/test_packer_parser.py

can't type annotate a list like this. related: https://github.com/commaai/openpilot/pull/33215

CANPacker: msg type is tuple

---

opendbc/car/gm/carcontroller.py
opendbc/car/structs.py

This is the most straightforward car to add first. openpilot PR: https://github.com/commaai/openpilot/pull/33384

GM: implement allow throttle/brakes

---

opendbc/car/structs.py

Companion to commaai/openpilot#33580, keeping capnp and structs in sync.

FCA Giorgio: Reserve safety ID

---

opendbc/car/toyota/carcontroller.py
opendbc/car/toyota/toyotacan.py

Revert "Lexus ES TSS2: improve start from stop response time"

---

opendbc/car/toyota/carcontroller.py
opendbc/car/toyota/toyotacan.py

Reverts commaai/opendbc#1302
Needs hysteresis

Re-apply "Lexus ES TSS2: improve start from stop response time"

---

opendbc/car/interfaces.py
opendbc/car/secoc.py
opendbc/car/structs.py

Revert "temp remove SecOC support"

---

opendbc/car/mazda/carstate.py
opendbc/car/nissan/carstate.py
opendbc/car/structs.py

Related: https://github.com/commaai/openpilot/issues/22746
https://github.com/commaai/openpilot/pull/1275/commits/a9bad8b6a9304f052ca520f48699a5352c91b27c

structs: add lkasEnabled and lkasDisabled

---

opendbc/car/subaru/fingerprints.py

Added Engine FW Version for 2020 Subaru Impreza
Route: 2e7f34ee218f76b6/00000009--c7565cf845

Subaru: Add FW for 2020 Subaru Impreza

---

opendbc/car/mazda/carstate.py
opendbc/car/nissan/carstate.py
opendbc/car/structs.py

Revert "structs: add lkasEnabled and lkasDisabled"

---

opendbc/car/toyota/carstate.py

Alert is the same. openpilot PR: https://github.com/commaai/openpilot/pull/33693

Toyota: low speed lockout is an ACC fault

---

opendbc/car/gm/carstate.py

openpilot PR: https://github.com/commaai/openpilot/pull/33697

GM: signed wheel speeds

---

opendbc/car/gm/carcontroller.py
opendbc/car/gm/carstate.py

This reverts commit 1f7fc5107c3e9592394aa5bd4f291994d0711832.
~No process replay got me :cry:~ huh not even fuzzing tests catch this

Reapply "GM: signed wheel speeds (#1323)"

---

opendbc/car/mazda/carstate.py
opendbc/car/nissan/carstate.py
opendbc/car/structs.py

openpilot PR: https://github.com/commaai/openpilot/pull/33700

CarState: add invalidLkasSetting

---

.github/workflows/tests.yml

resolves: https://github.com/commaai/opendbc/issues/1313

CI: Add macOS CI

---

opendbc/car/docs.py

Place cautionary comments above docs functions that have external consumers.
> [!NOTE]
> That's why you always leave a note.
>   - J. Walter Weatherman

docs: annotate functions used by comma website and shop

---

opendbc/dbc/generator/gm/gm_global_a_powertrain.dbc
opendbc/dbc/gm_global_a_powertrain_generated.dbc

I was live streaming cabana trying to find the LKAS button and found this.

GM: Add Snow/Ice Mode

---

opendbc/car/hyundai/fingerprints.py

<details open><summary>View table</summary><br>
|Dongle, platform, VIN|Name from VIN 🆚 CarDocs|Segments|Bad seg tags|Good seg tags|
|:--------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------|:-------------------------------------------|:---------------|:--------------------------------------------------------------------------------------|
|[bdb27acca0667105](https://useradmin.comma.ai/?onebox=bdb27acca0667105)<br><sub>HYUNDAI_TUCSON<br>KMHJ281AB........</sub>|HYUNDAI  1990 🆚<br>Hyundai Tucson 2021|39 routes,<br>842 segments<br>(14.0 hours)||- valid torque params: 842<br>- all lat active: 385<br>- no input all lat active: 275| …

[bot] Fingerprints: add missing FW versions from new users

---

opendbc/car/tesla/carstate.py

This message is more precise than the old message.

Tesla: better standstill message

---

opendbc/dbc/tesla_model3_party.dbc

Tesla: fix DAS_accSpeedLimit scale

---

opendbc/dbc/tesla_model3_party.dbc

add missing APS_eacMonitormessage to tesla model 3 dbc

add APS_eacMonitor to dbc

---

opendbc/car/toyota/values.py

Broken since https://github.com/commaai/openpilot/pull/30259!

Toyota: fix hybrid query for some cars

---

opendbc/car/body/carcontroller.py
opendbc/car/common/pid.py

Split from https://github.com/commaai/opendbc/pull/1379

PIDController: move to common

---

opendbc/car/ford/carcontroller.py
opendbc/car/ford/fordcan.py

Closes https://github.com/commaai/opendbc/issues/1398

Ford: show bars on change for 4s

---

opendbc/car/ford/fordcan.py

`apred simulation` is this lua function:
```lua
value = AccPrpl_A_Rq
v1 = AccBrkTot_A_Rq
if value == -5 then
ret = v1
else
ret = value
end
return ret
```

Ford long: add more notes

---

opendbc/car/ford/carcontroller.py

To be clear, this overshoot is not seen in normal driving with continuous requests. This PR aims to improve step response found in the longitudinal maneuver report:
- applies a jerk limit to the decel signal of 3.5 m/s^3
- allows gas to go negative instantly, allowing us to utilize engine braking before braking
The stock system has been seen using a max of 5 m/s^3 so far, and the ABS can actuate ~8 m/s^3 with heavy overshoot:
---
A 3.5 m/s^3 rate limit doesn't fully resolve overshooting on the step response in the master long maneuver report, however it does reduce it somewhat (mostly seen at higher speeds):
- master: https://commaai.github.io/opendbc-data/longitudinal_reports/FORD_BRONCO_SPORT_MK1_b9d015f8ff659e1e_00000494--6f8f5b9bd5.html
- this PR: …

Ford: reduce brake step response overshooting

---

opendbc/car/ford/values.py

<details open><summary>View table</summary><br>
|Dongle, platform, VIN|Name from VIN 🆚 CarDocs|Segments|Bad seg tags|Good seg tags|
|:---------------------------------------------------------------------------------------------------------------------------------|:--------------------------------------------------------------------------------------------------|:-----------------------------------------|:---------------|:-----------------------------------------------------------------------------------|
|[3ac6be16e44c9df0](https://useradmin.comma.ai/?onebox=3ac6be16e44c9df0)<br><sub>FORD_BRONCO_SPORT_MK1<br>3FMCR9C68........</sub>|FORD Bronco Sport 2024 🆚<br>Ford Bronco Sport 2021-23<br><sub>🎉 <b>New model year!</b> 🎉</sub>|2 routes,<br>31 segments<br>(0.5 hours)||- all lat active: …

[bot] Car docs: update model years from new users

---

opendbc/car/ford/interface.py

Revert "Ford: enable radar"

---

opendbc/car/ford/carcontroller.py

Fixes https://github.com/commaai/opendbc/issues/1433
After:

Ford long: smooth creep compensation

---

opendbc/car/toyota/carcontroller.py

Could have rolled back on sharp inclines when stopping

Toyota: set permit braking when stopping

---

opendbc/car/toyota/carcontroller.py

For https://github.com/commaai/opendbc/issues/1378

Toyota: move accel compensation logic to 33 Hz block

---

opendbc/car/toyota/carcontroller.py

See https://github.com/commaai/opendbc/issues/1462

Lexus ES TSS2: fix acceleration overshoot from a stop

---

.github/workflows/stale.yml

This PR adds the bot that marks PRs as stale from https://github.com/commaai/openpilot.
Let me know if the parameters need adjusting. It also requires the creation of stale and ignore stale labels.
Fixes #1473

Stale bot for PRs

---

opendbc/car/toyota/carcontroller.py

if down limits are imposed, this can cause a feedback loop where it goes negative temporarily in some cases

Toyota: fix accel rate limit

---

opendbc/car/chrysler/fingerprints.py

Preserved and public route 
904403a7e1bb1f77/00000157--b383e7c8ff

Chrysler: Add 2024 Pacifica Hybrid FW

---

opendbc/car/hyundai/carstate.py

Reverts commaai/opendbc#1326
Fixes https://github.com/commaai/openpilot/pull/34022

Revert "Hyundai: always publish cruise and main buttons"

---

opendbc/car/volkswagen/values.py

@jyoung8607 does VW_MQB_A0 make sense to also hide or no?

Remove VW footnote from website

---

opendbc/car/chrysler/interface.py
opendbc/car/hyundai/interface.py

fix hyundai bug in https://github.com/commaai/opendbc/pull/1470

fix DBC dict check regression

---

opendbc/car/common/pid.py

It's more bug-prone to alter the file, just copy it

Match pid.py file from openpilot

---

.github/workflows/tests.yml
SConstruct
pyproject.toml
test.sh

Addresses the issues found in [#1493](https://github.com/commaai/opendbc/pull/1493) (Mac OS not running)

CI: fix macOS test running

---

opendbc/car/gm/carstate.py

Route: 162796f1469f2f1b/00000001--df8f9ff62b

GM: Add Stock FCW to CarState

---

opendbc/car/hyundai/carcontroller.py
opendbc/car/hyundai/carstate.py
opendbc/car/hyundai/hyundaican.py
opendbc/car/hyundai/interface.py

Revert "Hyundai CAN Longitudinal: Enable for Camera SCC cars"

---

opendbc/car/toyota/carcontroller.py
opendbc/car/toyota/interface.py

Prepares for https://github.com/commaai/opendbc/pull/1522

Toyota: move longitudinal PID into carcontroller

---

opendbc/car/hyundai/fingerprints.py

<details open><summary>View table</summary><br>
|Dongle, platform, VIN|Name from VIN 🆚 CarDocs|Segments|Bad seg tags|Good seg tags|
|:---------------------------------------------------------------------------------------------------------------------------|:---------------------------|:-------------------------------------------|:---------------|:------------------------------------------------------------------------------------|
|[fcb975ffe122a0cc](https://useradmin.comma.ai/?onebox=fcb975ffe122a0cc)<br><sub>HYUNDAI_KONA_EV<br>000000000........</sub>|None 🆚<br>None|62 routes,<br>959 segments<br>(16.0 hours)||- valid torque params: 711<br>- all lat active: 74<br>- no input all lat active: 26|
Dongles to re-run category: `fcb975ffe122a0cc`
</details>
<details ><summary>View …

[bot] Fingerprints: add missing FW versions from CAN fingerprinting cars

---

opendbc/car/toyota/carcontroller.py

From https://github.com/commaai/opendbc/pull/1536

Toyota: error correct on future acceleration

---

opendbc/car/toyota/carcontroller.py
opendbc/car/toyota/carstate.py
opendbc/car/toyota/interface.py

Superseded by https://github.com/commaai/opendbc/pull/1559 for a more generic approach to prevent overshoot

Toyota: remove PCM compensation

---

test.sh

possible fix https://github.com/commaai/opendbc/issues/1557

check if uv is installed

---

opendbc/car/gm/carstate.py

Null effect refactor, enabled by #1470, will make #1223 come in a little nicer.

GM: CAN parser cleanup, prep for Yukon

---

opendbc/car/ford/radar_interface.py

https://github.com/commaai/opendbc/issues/1611

Ford: invalid radar data tolerance

---

opendbc/car/ford/carcontroller.py

Regression from https://github.com/commaai/opendbc/pull/1419
Only possible if using joystick mode

Ford: clip gas

---

opendbc/car/honda/carcontroller.py
opendbc/car/honda/carstate.py
opendbc/car/toyota/carcontroller.py

From https://github.com/commaai/opendbc/pull/1626
failure in CI job: https://github.com/commaai/openpilot/actions/runs/12936212729/job/36081308961#step:8:937

Honda: missing float

---

opendbc/car/isotp_parallel_query.py
opendbc/car/uds.py

Prep for https://github.com/commaai/opendbc/pull/1681

IsoTpMessage: calculate max length

---

opendbc/car/uds.py

Moved from https://github.com/commaai/panda/pull/1524
Will merge by hackathon! Just need some time to make sure this is done correctly w/ reasonable assertions

IsoTpMessage: support CAN FD single frames

---

.github/workflows/release.yml
pyproject.toml
test.sh

need to remove pandacan direct dep

PyPI publishing

---

opendbc/car/uds.py

BMW returns a different sub address when talking to the ECU

Custom rx sub_addr

---

opendbc/car/tesla/interface.py
opendbc/car/tesla/teslacan.py
opendbc/car/tesla/values.py

For https://github.com/commaai/panda/pull/2036

Tesla: Model 3/Y safety prep

---

opendbc/car/fw_query_definitions.py
opendbc/car/fw_versions.py
opendbc/car/tests/test_fw_fingerprint.py

https://github.com/commaai/opendbc/pull/1613

Move some FW query checks into config

---

setup.sh
test.sh

For tests in https://github.com/commaai/opendbc/pull/1713

uv environment setup script

---

setup.sh

for https://github.com/commaai/opendbc/pull/1713

clean up setup.sh

---

opendbc/car/fingerprints.py
opendbc/car/tests/test_car_interfaces.py
opendbc/car/tests/test_lateral_limits.py

```
>>> set(all_known_cars()) - set(PLATFORMS)
set()
>>> set(PLATFORMS)- set(all_known_cars())
{'RIVIAN_R1_GEN1', 'MOCK', 'CHEVROLET_TRAILBLAZER'}
```

rm all_known_cars

---

opendbc/car/fw_versions.py
opendbc/car/tests/test_fw_fingerprint.py

Reverts commaai/opendbc#1742
Something about this fails test_onroad

Revert "FW query: sort brands by percentage of ECU matches"

---

opendbc/car/fw_versions.py
opendbc/car/tests/test_fw_fingerprint.py

Reapply "FW query: sort brands by percentage of ECU matches"

---

opendbc/car/ford/fingerprints.py

route: e36b272d5679115f/000002fc--34c96aa127

2023 F-150  5.0 - FIngerprint

---

opendbc/car/interfaces.py
opendbc/car/tesla/carstate.py

we mainly want to reduce false positives, jitteriness in the signal is fine (but this also reduces that from a plain threshold a little)

common update_steering_pressed

---

opendbc/car/tesla/fingerprints.py

Adding fingerprint for 2022 Tesla Model Y Performance.
[Route](https://useradmin.comma.ai/?onebox=d3cff3c1d3af097b%7C00000000--c634965703)

Fingerprint: 2022 Tesla Model Y Performance

---

opendbc/car/rivian/carstate.py

Rivian: less sensitive steering pressed threshold

---

opendbc/dbc/hyundai_canfd.dbc

Fixed invalid comments found in the dbc. Split from https://github.com/commaai/opendbc/pull/1717

HKG: fix hyundai_canfd comments

---

opendbc/dbc/generator/honda/_honda_common.dbc
opendbc/dbc/generator/honda/_nidec_common.dbc

Rebased for new repo structure. 
See https://github.com/commaai/opendbc/pull/875

Honda: DBC updates

---

opendbc/car/ford/interface.py

Moved out of debug firmware here: https://github.com/commaai/panda/pull/2128

Ford: CAN longitudinal has been verified

---

opendbc/car/ford/fingerprints.py

Route: `112e4d6e0cad05e1/00000008--9edc168b3f`

2022 F150 Lightning - Fingerprint

---

opendbc/car/ford/fingerprints.py

https://connect.comma.ai/ca2640038e5391c3/000000a5--d6e26ef9d9

Ford: add Mach E fingerprint

---

opendbc/car/hyundai/values.py

Simplify Hyundai safety flag values

---

opendbc/dbc/vw_meb.dbc
opendbc/safety/safety/safety_volkswagen_common.h
opendbc/safety/safety/safety_volkswagen_mqb.h

Null-effect change, cleanup and diff reduction in preparation for commaai/opendbc#1696.

VW MQB: More cleanup and prep for MEB

---

opendbc/car/tesla/fingerprints.py

f15cb91e37913f92/00000005--79b48670c2

Tesla: Model3 Highland 2024 fingerprint

---

opendbc/car/body/carcontroller.py
opendbc/car/car.capnp
opendbc/car/chrysler/carcontroller.py
opendbc/car/chrysler/chryslercan.py
opendbc/car/gm/carcontroller.py
opendbc/car/gm/gmcan.py
opendbc/car/honda/carcontroller.py
opendbc/car/honda/hondacan.py
opendbc/car/hyundai/carcontroller.py
opendbc/car/hyundai/hyundaican.py
opendbc/car/hyundai/hyundaicanfd.py
opendbc/car/mazda/carcontroller.py
opendbc/car/mazda/mazdacan.py
opendbc/car/nissan/nissancan.py
opendbc/car/rivian/carcontroller.py
opendbc/car/rivian/riviancan.py
opendbc/car/subaru/carcontroller.py
opendbc/car/subaru/subarucan.py
opendbc/car/toyota/carcontroller.py
opendbc/car/volkswagen/carcontroller.py
opendbc/car/volkswagen/mqbcan.py
opendbc/car/volkswagen/pqcan.py

Can be confusing if a port supports angle and torque side by side

actuators: rename steer to torque

---

opendbc/car/__init__.py
opendbc/car/nissan/carcontroller.py
opendbc/car/nissan/values.py
opendbc/car/tesla/carcontroller.py
opendbc/car/tesla/values.py
opendbc/car/toyota/carcontroller.py
opendbc/car/toyota/values.py

So you don't write this bug: https://github.com/commaai/opendbc/pull/1674/commits/c83f49db8ff1319e9fea59ae9af03ac0d2395d5c

angle limits: enforce a max angle and inactive angle

---

opendbc/car/nissan/values.py
opendbc/safety/safety/safety_nissan.h
opendbc/safety/tests/common.py
opendbc/safety/tests/test_nissan.py
opendbc/safety/tests/test_tesla.py
opendbc/safety/tests/test_toyota.py

tests the max angle limiting when inactive

Angle safety: test above max angle

---

opendbc/car/tesla/fingerprints.py

Route: https://connect.comma.ai/db792d9f5ca5ef59/0000007e--4488054949

fingerprint: 2023 Tesla Model Y (HW3)

---

opendbc/car/hyundai/hyundaicanfd.py
opendbc/dbc/generator/hyundai/_hyundai_common.dbc
opendbc/dbc/generator/hyundai/hyundai_canfd.dbc
opendbc/safety/tests/test_hyundai_canfd.py

Revert "Hyundai CAN FD: ADAS steering API updates"

---

opendbc/safety/tests/safety_replay/helpers.py
opendbc/safety/tests/safety_replay/replay_drive.py

for https://github.com/commaai/opendbc/pull/1852

Fix Ford CAN FD safety replay

---

opendbc/safety/safety/safety_ford.h

enabled by https://github.com/commaai/opendbc/pull/1852

Ford CAN FD: enable safety in release

---

opendbc/safety/safety/safety_hyundai_common.h
opendbc/safety/tests/test.sh

- adds back nested directories in the report
- no cd

Coverage fixups

---

opendbc/car/toyota/carstate.py

Looks like a regression from https://github.com/commaai/openpilot/pull/33696

Toyota: low speed lockout is a fault only if openpilot longitudinal

---

.gitignore

Ignore build and report artifacts from the code-coverage and MISRA tests.

add CI test artifacts to gitignore

---

opendbc/car/tesla/fingerprints.py

route: da74b4dc7cea694c/00000000--00a44ee521

Tesla: add Model Y 2022 (HW3)

---

opendbc/car/tesla/carcontroller.py
opendbc/car/tesla/teslacan.py

simple correctness fix from https://github.com/commaai/opendbc/pull/1792

Tesla: setSpeed is vEgo while disabled

---

opendbc/car/body/carcontroller.py
opendbc/car/chrysler/carcontroller.py
opendbc/car/honda/carcontroller.py
opendbc/car/hyundai/carcontroller.py
opendbc/car/mazda/carcontroller.py
opendbc/car/rivian/carcontroller.py
opendbc/car/subaru/carcontroller.py
opendbc/car/toyota/carcontroller.py

carcontroller cleanup

---

opendbc/car/car.capnp
opendbc/safety/safety.h

VW MEB: Reserve safety identifier

---

opendbc/car/volkswagen/fingerprints.py
opendbc/car/volkswagen/interface.py

Just wanted to add in my firmware so that it could get upstreamed into master-ci for my car.

VW PQ: Add FW for 2012 Jetta Sportwagen TDI

---

opendbc/car/vin.py
opendbc/car/volkswagen/values.py

Split from https://github.com/commaai/opendbc/pull/1821

vin: add parse function

---

opendbc/car/tesla/teslacan.py

Tesla: fix an ACC fault

---

opendbc/safety/tests/test_hyundai.py

- Split from https://github.com/commaai/opendbc/pull/1964

Hyundai Safety: Use safety flags in tests

---

opendbc/safety/safety.h
opendbc/safety/safety/safety_chrysler.h
opendbc/safety/safety/safety_defaults.h
opendbc/safety/safety/safety_ford.h
opendbc/safety/safety/safety_gm.h
opendbc/safety/safety/safety_honda.h
opendbc/safety/safety/safety_hyundai.h
opendbc/safety/safety/safety_hyundai_canfd.h
opendbc/safety/safety/safety_mazda.h
opendbc/safety/safety/safety_nissan.h
opendbc/safety/safety/safety_rivian.h
opendbc/safety/safety/safety_subaru.h
opendbc/safety/safety/safety_subaru_preglobal.h
opendbc/safety/safety/safety_tesla.h
opendbc/safety/safety/safety_toyota.h
opendbc/safety/safety/safety_volkswagen_mqb.h
opendbc/safety/safety/safety_volkswagen_pq.h
opendbc/safety/safety_declarations.h

Split from https://github.com/commaai/opendbc/pull/1954

safety fwd hook: returns a bool

---

opendbc/safety/safety/safety_ford.h
opendbc/safety/tests/test_ford.py

For https://github.com/commaai/opendbc/pull/1959 and https://github.com/commaai/opendbc/pull/1954

Ford safety: only check relevant LKAS addresses

---

opendbc/safety/safety.h
opendbc/safety/safety/safety_body.h
opendbc/safety/safety/safety_chrysler.h
opendbc/safety/safety/safety_ford.h
opendbc/safety/safety/safety_gm.h
opendbc/safety/safety/safety_honda.h
opendbc/safety/safety/safety_hyundai.h
opendbc/safety/safety/safety_hyundai_canfd.h
opendbc/safety/safety/safety_mazda.h
opendbc/safety/safety/safety_nissan.h
opendbc/safety/safety/safety_rivian.h
opendbc/safety/safety/safety_subaru.h
opendbc/safety/safety/safety_subaru_preglobal.h
opendbc/safety/safety/safety_tesla.h
opendbc/safety/safety/safety_toyota.h
opendbc/safety/safety/safety_volkswagen_mqb.h
opendbc/safety/safety/safety_volkswagen_pq.h
opendbc/safety/safety_declarations.h
opendbc/safety/tests/common.py
opendbc/safety/tests/test_honda.py

split from https://github.com/commaai/opendbc/pull/1954

safety: relay malfunction config

---

opendbc/car/hyundai/interface.py
opendbc/safety/safety/safety_hyundai.h
opendbc/safety/safety/safety_hyundai_common.h
opendbc/safety/tests/test_hyundai.py

Dashcamming the car from https://github.com/commaai/opendbc/pull/933 as it's missing an rx check
Bug is in the safety tests in https://github.com/commaai/opendbc/pull/1903. @sunnyhaibin can you fix?

Hyundai: dashcam FCEV

---

opendbc/dbc/tesla_model3_party.dbc

@sshane Could you verify if the DAS_autoPilotEnabled flag changes when FSD is activated? I'd like to implement a warning notification when either Autopilot or FSD is enabled.

Tesla: Autopilot enabled signal

---

opendbc/dbc/tesla_model3_party.dbc

Tesla: fix incorrect DBC msg length

---

opendbc/dbc/generator/subaru/_subaru_preglobal_2015.dbc
opendbc/safety/safety/safety_subaru_preglobal.h

Subaru Pre-Global: fix missing rx checks

---

opendbc/safety/safety/safety_honda.h

Honda Nidec: missing brake command rx check

---

opendbc/car/gm/interface.py
opendbc/car/gm/values.py
opendbc/safety/safety/safety_gm.h
opendbc/safety/tests/common.py
opendbc/safety/tests/test_gm.py

GM safety: add missing regen rx check

---

opendbc/safety/safety/safety_hyundai.h

Hyundai safety: add missing rx checks

---

opendbc/safety/safety.h
opendbc/safety/safety/safety_body.h
opendbc/safety/safety/safety_defaults.h
opendbc/safety/safety/safety_elm327.h
opendbc/safety/safety_declarations.h

a small simple start at https://github.com/commaai/opendbc/pull/1954 since it requires a bunch of verification/test changes

safety: start fwd hook config

---

opendbc/car/rivian/interface.py

No reason we can't set this, safety is not in release and toggle isn't on master

Rivian: set long safety flag

---

opendbc/safety/safety/safety_rivian.h
opendbc/safety/tests/common.py
opendbc/safety/tests/test_rivian.py

Split from https://github.com/commaai/opendbc/pull/2016

Rivian safety: parse speed

---

opendbc/car/gm/gmcan.py
opendbc/dbc/generator/gm/gm_global_a_powertrain.dbc

Split from https://github.com/commaai/opendbc/pull/2006

GM: fix some ACC signals

---

opendbc/car/toyota/values.py

seen a dongle and report in Discord

Toyota: bump RAV4 ICE to 2025

---

opendbc/car/docs_definitions.py

Matches the [website][1]
[1]: https://comma.ai/shop/car-harness

docs: add comma power to Rivian and Tesla harness

---

opendbc/car/tesla/fingerprints.py

3a44d15e384e1dc4/00000000--80950c404d

Tesla: add Model 3 HW3 fingerprint

---

opendbc/car/hyundai/fingerprints.py
opendbc/car/hyundai/values.py

2024 Kia Niro EV
Hyundai A
80b8e9a6ad0acec3/00000003--837bed849a

HKG: Add FW for 2024 Kia Niro EV

---

opendbc/car/gm/interface.py
opendbc/car/gm/radar_interface.py

Closes https://github.com/commaai/opendbc/issues/2012

GM: check camera object data for radarUnavailable

---

opendbc/safety/safety.h
opendbc/safety/safety/safety_rivian.h
opendbc/safety/safety_declarations.h
opendbc/safety/tests/common.py
opendbc/safety/tests/test_chrysler.py
opendbc/safety/tests/test_gm.py
opendbc/safety/tests/test_hyundai.py
opendbc/safety/tests/test_hyundai_canfd.py
opendbc/safety/tests/test_mazda.py
opendbc/safety/tests/test_rivian.py
opendbc/safety/tests/test_subaru.py
opendbc/safety/tests/test_subaru_preglobal.py
opendbc/safety/tests/test_toyota.py
opendbc/safety/tests/test_volkswagen_mqb.py
opendbc/safety/tests/test_volkswagen_pq.py

For https://github.com/commaai/opendbc/pull/2016

safety: support dynamic max torque from speed

---

opendbc/safety/safety/safety_ford.h
opendbc/safety/safety/safety_rivian.h
opendbc/safety/tests/test_rivian.py

For https://github.com/commaai/opendbc/pull/2016. After this we need https://github.com/commaai/opendbc/issues/1999

Rivian: add all validity checks for speed message

---

opendbc/car/honda/values.py

2025 Passport - 350165ca086d6482/00000000--7b694ec27e

Honda: update compatibility for Passport

---

opendbc/dbc/tesla_model3_party.dbc

Tested everything in DAS_Settings: https://connect.comma.ai/2c912ca5de3b1ee9/0000017d--eb694a326e

Tesla: new Autopilot and other vehicle signals

---

opendbc/car/tesla/fingerprints.py

057a750157f846bb/0000026f--0edcb20226

Tesla: fingerprint Tesla Model Y 2024 (HW4)

---

opendbc/car/ford/fingerprints.py

Route: `112e4d6e0cad05e1/00000000--598baa7f7a`

[Ford] F150 Lightning Fingerprint

---

opendbc/car/tesla/fingerprints.py

3ae5e3d7179aa92c/000000b6--0c207463fd

Tesla: fingerprint Model 3 (2023) HW3

---

opendbc/car/tesla/fingerprints.py
opendbc/car/tesla/values.py

6321083713becd53/00000003--b6c8cf2fd2

Tesla: fingerprint Model 3 2025 (HW4)

---

opendbc/car/docs_definitions.py
opendbc/car/rivian/values.py

To be added to the website setup guide in https://github.com/commaai/website/pull/66

docs: add setup video link

---

opendbc/car/tesla/fingerprints.py

3ae5e3d7179aa92c/000000d9--027a4da5d7

Tesla: add Model 3 2023 (HW3)

---

opendbc/safety/safety.h
opendbc/safety/tests/common.py
opendbc/safety/tests/hyundai_common.py

Reverts commaai/opendbc#2087
This is actually just more confusing

Revert "Move relay malfunction check to fwd hook"

---

opendbc/safety/safety/safety_toyota.h
opendbc/safety/tests/misra/test_mutation.py
opendbc/safety/tests/test_toyota.py

Split from https://github.com/commaai/opendbc/pull/2095 since it requires changes outside of Toyota

safety: move Toyota to msg block config

---

opendbc/safety/safety/safety_subaru.h
opendbc/safety/tests/test_subaru.py

Split from https://github.com/commaai/opendbc/pull/2095 since it's a little larger than the other brands

safety: move Subaru to msg block config

---

opendbc/safety/safety/safety_hyundai.h
opendbc/safety/tests/test_hyundai.py

Split from https://github.com/commaai/opendbc/pull/2095 since it's a little bigger

safety: move Hyundai to msg block config

---

opendbc/car/body/interface.py
opendbc/car/car.capnp
opendbc/car/car_helpers.py
opendbc/car/chrysler/interface.py
opendbc/car/docs.py
opendbc/car/docs_definitions.py
opendbc/car/ford/interface.py
opendbc/car/gm/interface.py
opendbc/car/honda/interface.py
opendbc/car/hyundai/interface.py
opendbc/car/interfaces.py
opendbc/car/mazda/interface.py
opendbc/car/mock/interface.py
opendbc/car/nissan/interface.py
opendbc/car/rivian/interface.py
opendbc/car/subaru/interface.py
opendbc/car/subaru/values.py
opendbc/car/tesla/interface.py
opendbc/car/tests/test_car_interfaces.py
opendbc/car/toyota/interface.py
opendbc/car/volkswagen/interface.py

Reverts commaai/opendbc#2114
Some problem in openpilot we're debugging in https://github.com/commaai/openpilot/pull/35014

Revert "Rename experimental long"

---

opendbc/car/body/interface.py
opendbc/car/car.capnp
opendbc/car/car_helpers.py
opendbc/car/chrysler/interface.py
opendbc/car/docs.py
opendbc/car/docs_definitions.py
opendbc/car/ford/interface.py
opendbc/car/gm/interface.py
opendbc/car/honda/interface.py
opendbc/car/hyundai/interface.py
opendbc/car/interfaces.py
opendbc/car/mazda/interface.py
opendbc/car/mock/interface.py
opendbc/car/nissan/interface.py
opendbc/car/rivian/interface.py
opendbc/car/subaru/interface.py
opendbc/car/subaru/values.py
opendbc/car/tesla/interface.py
opendbc/car/tests/test_car_interfaces.py
opendbc/car/toyota/interface.py
opendbc/car/volkswagen/interface.py

Revert "Revert "Rename experimental long""

---

opendbc/car/hyundai/fingerprints.py

Add support my EU version of SantaFe

---

opendbc/dbc/rivian_park_assist_can.dbc

route: 0d2ed7da516cc8aa/0000006b--028bd72cd5

Rivian: add park assist dbc

---

opendbc/car/honda/values.py

[c28ee1100a35e353/00000052--b23408ad0d](https://connect.comma.ai/c28ee1100a35e353/00000052--b23408ad0d)

Honda: 2025 HRV 

---

opendbc/safety/tests/safety_replay/helpers.py

Split from https://github.com/commaai/opendbc/pull/2115

safety replay: add Tesla support

---

opendbc/car/honda/values.py

Correcting Acura ILX documentation.  Please confirm this split is the proper way for the robo-documentation processor to work.
Source:
https://acuranews.com/en-US/releases/release-939646ef330948738e2e07a0b8e3e706-2016-acura-ilx-specifications-features
https://acuranews.com/en-US/releases/release-6597cf3c2e0246cab2263563702bffdb-2017-ilx-specifications-features
https://acuranews.com/en-US/releases/release-fcfa911f78aa459ba83121a2c79a614d-2018-ilx-specifications-features
https://acuranews.com/en-US/releases/release-66267fa576124c298412b6031443552b-2019-acura-ilx-specifications

Acura: Fix ILX documentation

---

opendbc/car/ford/values.py

split out install video for Ford Q4 harness into separate PR

docs: Ford Q4 setup video

---

opendbc/safety/safety/safety_tesla.h
opendbc/safety/tests/test_tesla.py

Split from https://github.com/commaai/opendbc/pull/2190

Tesla: check steer control type

---

opendbc/car/ford/values.py

Revert "Ford Q4 setup video, long_odbc_cable for Q4"

---

opendbc/can/common.cc
opendbc/can/common.h
opendbc/can/common_dbc.h
opendbc/can/dbc.cc

For https://github.com/commaai/opendbc/pull/2204

CANParser: add signal setup hook

---

opendbc/can/dbc.cc
opendbc/can/packer.cc

Needed so the packer can set the counter signal properly after https://github.com/commaai/opendbc/pull/2206

CANPacker: support signal types

---

opendbc/can/common.cc
opendbc/can/common.h
opendbc/can/dbc.cc
opendbc/can/parser.cc
opendbc/dbc/tesla_model3_party.dbc

for CAN validity and CAN packing

CANParser: support Tesla checksums

---

opendbc/car/tesla/teslacan.py

Enabled by https://github.com/commaai/opendbc/pull/2223

Tesla: let CANPacker set checksums

---

opendbc/car/tesla/carcontroller.py
opendbc/car/tesla/teslacan.py

This reverts commit b9225178021be2b606dab89bf941440562f4cc6c.

Reapply "Tesla: let CANPacker set counters (#2214)"

---

.pre-commit-config.yaml
opendbc/can/packer_pyx.pyx
opendbc/can/parser_pyx.pyx
opendbc/car/honda/interface.py
test.sh

without mypy, it's fast enough
would be nice to try out lefthook at some point https://github.com/evilmartians/lefthook

enable pre-commit

---

opendbc/car/ford/values.py

Ranger install video

---

opendbc/car/docs.py

for https://github.com/commaai/website/pull/58

docs: custom kwargs in markdown generator

---

opendbc/car/toyota/carcontroller.py

skip for loop when self.enableDsu is false, otherwise it will do the for loop regardless.

Skip for loop calls when enableDsu is false

---

opendbc/safety/tests/common.py
opendbc/safety/tests/test_ford.py
opendbc/safety/tests/test_rivian.py
opendbc/safety/tests/test_tesla.py

extension of https://github.com/commaai/opendbc/pull/2294

safety: common speed mismatch test

---

opendbc/safety/safety.h
opendbc/safety/safety_declarations.h

Can't move everything because MISRA checks for scope

safety: consolidate some lateral constants

---

opendbc/car/tesla/fingerprints.py

route: https://connect.comma.ai/64efe75db7b9d883/00000000--4d82aaee84

fingerprint: 2022 Tesla Model Y, 2023.40

---

opendbc/car/body/interface.py
opendbc/car/car_helpers.py
opendbc/car/chrysler/interface.py
opendbc/car/docs.py
opendbc/car/ford/interface.py
opendbc/car/gm/interface.py
opendbc/car/honda/interface.py
opendbc/car/hyundai/interface.py
opendbc/car/hyundai/tests/test_hyundai.py
opendbc/car/interfaces.py
opendbc/car/mazda/interface.py
opendbc/car/mock/interface.py
opendbc/car/nissan/interface.py
opendbc/car/panda_runner.py
opendbc/car/rivian/interface.py
opendbc/car/subaru/interface.py
opendbc/car/tesla/interface.py
opendbc/car/tests/test_car_interfaces.py
opendbc/car/toyota/interface.py
opendbc/car/volkswagen/interface.py

Closes https://github.com/commaai/opendbc/issues/2313

car interfaces: pass in if release build

---

opendbc/car/honda/carstate.py

I'm not even finding where this code is used. And git blame seems to go back to very early days of openpilot and seems to have been added without explanation?

Honda: Clean up carstate

---

opendbc/safety/lateral.h
opendbc/safety/tests/safety_replay/helpers.py
opendbc/safety/tests/test_tesla.py

prep for https://github.com/commaai/opendbc/pull/2343

angle safety: reset to current angle for violation

---

opendbc/car/ford/interface.py
opendbc/car/ford/radar_interface.py
opendbc/car/ford/values.py

Reverts commaai/opendbc#1835
this changed the radar delay for CAN Fords as seen in the process replay diff https://github.com/commaai/openpilot/actions/runs/15380637829/job/43270877769

Revert "Ford CANFD Radar Parser"

---

opendbc/car/hyundai/interface.py

fixes dashcam not taking effect from https://github.com/commaai/opendbc/pull/1137

Hyundai: fix dashcam setting

---

opendbc/car/ford/values.py

Validation
* Dongle ID: 
* Route:

Link Expedition to F150/Lightning install video

---

opendbc/car/hyundai/fingerprints.py

**Route:** `267ff54b09621336/00000000--f575385532`

HKG: Add FW for 2022 Hyundai Azera

---

opendbc/car/car.capnp
opendbc/car/interfaces.py

Validation
* Dongle ID: 
* Route:

Torque control: rm localizer option

---

opendbc/car/rivian/carstate.py

Metric: 2d2da5dea63b5c5e/00000000--4f8dce236e
Imperial: 2d2da5dea63b5c5e/00000002--8904021af2

Rivian: add vEgoCluster

---

opendbc/car/honda/carstate.py

Get a little clever:
* Auto-detect and use any DRIVERS_DOOR_OPEN signal in the SCM messages for this car
* If the DOORS_OPEN message is available, OR those results with any SCM signal we got

Honda: Door open message refactor, part 2

---

opendbc/car/docs_definitions.py
opendbc/car/subaru/values.py

- Moved tools to harness definition
- Refer to comment: https://github.com/commaai/opendbc/pull/2477#discussion_r2209384501

Subaru Docs: move tools to harness definition

---

opendbc/safety/safety.h

safety: make RX checks go invalid on unset frequency

---

opendbc/car/body/values.py

- COMMA_HACK_4 [vid](https://youtu.be/VT-i3yRsX2s?t=2736)
- time stamped it at a part I thought would be fun to watch for people not familiar with the comma body

Docs: add vid link to comma body

---

.github/workflows/tests.yml

Even a dirty port is better than the state things are in now.

port over test_models from openpilot

---

opendbc/safety/board/can_declarations.h
opendbc/safety/modes/chrysler.h
opendbc/safety/modes/ford.h
opendbc/safety/modes/gm.h
opendbc/safety/modes/honda.h
opendbc/safety/modes/hyundai.h
opendbc/safety/modes/hyundai_canfd.h
opendbc/safety/modes/mazda.h
opendbc/safety/modes/nissan.h
opendbc/safety/modes/rivian.h
opendbc/safety/modes/subaru.h
opendbc/safety/modes/subaru_preglobal.h
opendbc/safety/modes/tesla.h
opendbc/safety/modes/toyota.h
opendbc/safety/modes/volkswagen_mqb.h
opendbc/safety/modes/volkswagen_pq.h
opendbc/safety/safety.h
opendbc/safety/safety_declarations.h

rm GET_BUS

---

opendbc/safety/board/can_declarations.h
opendbc/safety/modes/body.h
opendbc/safety/modes/chrysler.h
opendbc/safety/modes/elm327.h
opendbc/safety/modes/ford.h
opendbc/safety/modes/gm.h
opendbc/safety/modes/honda.h
opendbc/safety/modes/hyundai.h
opendbc/safety/modes/hyundai_canfd.h
opendbc/safety/modes/hyundai_common.h
opendbc/safety/modes/mazda.h
opendbc/safety/modes/nissan.h
opendbc/safety/modes/rivian.h
opendbc/safety/modes/subaru.h
opendbc/safety/modes/subaru_preglobal.h
opendbc/safety/modes/tesla.h
opendbc/safety/modes/toyota.h
opendbc/safety/modes/volkswagen_common.h
opendbc/safety/modes/volkswagen_mqb.h
opendbc/safety/modes/volkswagen_pq.h
opendbc/safety/safety.h

safety: rm GET_ADDR

---

opendbc/car/hyundai/values.py

Last 180 days Telluride and Palisade users:
And this is with 8 degree mount subtracted from Telluride users:

Hyundai: update Telluride mount

---

opendbc/car/interfaces.py
pyproject.toml

This was 1% of process replay time

interfaces: remove numpy.mean usage

---

opendbc/car/vehicle_model.py

> [!WARNING]
> Differences observed on the process replay due to float precision
> * https://github.com/commaai/openpilot/pull/35866
Consolidates `ACCELERATION_DUE_TO_GRAVITY` definition to one location instead of 2

refactor: consolidate ACCELERATION_DUE_TO_GRAVITY import path

---

opendbc/car/honda/carcontroller.py
opendbc/car/honda/interface.py

Prep / diff reduction for #2610.
* Don't send BOSCH_SUPPLEMENTAL_1
* Allow steer actuator delay to be tuned per-car
* Only HONDA_PILOT_4G in dashcam

Honda: CAN-FD platform cleanup

---

opendbc/car/honda/interface.py
opendbc/car/honda/values.py
opendbc/safety/modes/honda.h
opendbc/safety/tests/test_honda.py

Prep / diff reduction for #2610.

Honda: Bosch CAN-FD platform safety

---

opendbc/car/subaru/fingerprints.py

Validation
* Dongle ID: 2e120a0dd145dbfd
* Route: 2e120a0dd145dbfd/0000000d--b5b95920e2

Added FW for Subaru XV 2018

---

README.md

Wikipedia changed title of section broking link here

README: Update CAN DBC wiki link

---

opendbc/can/tests/test_checksums.py
opendbc/car/honda/hondacan.py
opendbc/dbc/generator/honda/_bosch_2018.dbc
opendbc/dbc/generator/honda/_lkas_hud_5byte.dbc
opendbc/dbc/generator/honda/_lkas_hud_8byte.dbc

Resurrect the reverse-engineering work done by @csouers in #252.
This PR is a null effect change, but will enable finer control of the LKA HUD in future updates.

Honda: ADAS messaging refactor, part 2

---

opendbc/car/subaru/fingerprints.py

**Route:** `f5dddb74aa41bd0f/00000010--f3f54d1fa7`

Subaru: Add FW for 2022 Subaru Legacy

---

opendbc/safety/tests/test_toyota.py

Merged #1385 with passing tests, but other refactors were merged after CI ran.

fix build breakage
