honda_odyssey_exl_2018.dbc
Searched through Cabana with @energee to find proper signals for EPB and Brake_Hold. We found them. 
=> Added EPB and Brake_Hold

gm_global_a_chassis.dbc, gm_global_a_powertrain.dbc
Displaying steering, gas, regen braking, and friction braking, correctly in Cabana.
Doesn't affect Volt's actuator code in gmcan.py (doesn't use DBCs).
=> Fix Chevy Volt actuator signal parsing

gm_global_a_lowspeed.dbc, gm_global_a_powertrain.dbc
As an effort to reduce dependency on low-speed GMLAN.
Currently Volt port still relies on GMLAN to send chimes.
=> Volt: switch to parsing ACC buttons from powertrain CAN

cadillac_ct6_powertrain.dbc, generator/honda/honda_civic_touring_2016_can.dbc, gm_global_a_powertrain.dbc, honda_civic_touring_2016_can_generated.dbc
* Add escaping to nested quotes in comment. (Did run generator after fixing).
* Convert files from latin1 to UTF-8 to fix decoding issue of the degrees rune.
=> Syntax and encoding fixes

chrysler_pacifica_2017_hybrid_private_fusion.dbc
https://github.com/commaai/openpilot/blob/devel/selfdrive/can/parser.cc#L269
```
// Assumes all signals in the message are of the same type (little or big endian)
// TODO: allow signals within the same message to have different endianess
auto& sig = message_states[cmsg.getAddress()].parse_sigs[0];
if (sig.is_little_endian) {
p = read_u64_le(dat);
} else {
p = read_u64_be(dat);
}
```
=> change chrysler radar to all big endian to avoid OP can parser bug

subaru_global_2017.dbc
Minor fix, with 3-bit units signal metric units decimal value is 6 on XV 2018:
=> Update metric value for Dash_Units

chrysler_pacifica_2017_hybrid.dbc
This doesn't matter for our use in OP, but 7 bits is more accurate.
The signal might be 8 bits, but I haven't seen the 8th bit set in a drive, so leaving it at 7 just in case.
=> chrysler: increase size of ACCEL_134

mazda_cx5_gt_2017.dbc
I found out that the driver torque signal is actually 8 bits
instead of 16, the other 8 bits is a separate signal.
Also fixed the torque motor signal
Added mobile start CAN msgs
Added new brake warning signal and a few other signals
Signed-off-by: Jafar Al-Gharaibeh <to.jafar@gmail.com>
=> Mazda: Fix torque signal and add new CAN msgs

generator/honda/_bosch_2018.dbc, honda_accord_lx15t_2018_can_generated.dbc, honda_accord_s2t_2018_can_generated.dbc, honda_civic_hatchback_ex_2017_can_generated.dbc, honda_civic_sedan_16_diesel_2019_can_generated.dbc, honda_crv_ex_2017_can_generated.dbc, honda_crv_hybrid_2019_can_generated.dbc, honda_insight_ex_2019_can_generated.dbc
This pull request is joint with jpancotti.
This seeks to add information about the Honda-Bosch camera system lane line detection signals. It includes values to support a degree three polynomial lane line model (LINE_OFFSET, LINE_ANGLE, LINE_CURVATURE). Line curvature rate is currently listed as LINE_PARAMETER because it is unknown if this is a low-quality curvature rate value or if it is something else. Have seen it spike up in magnitude for curbs, so it may be some kind of line upward / downward slope or line height value. Other signals include an indicator for solid / dashed line texture, line detection probability, line distance visible, a value related to line thickness. Many signal values are still undecoded. Please see the comments in the DBC. There may also be some additional …
=> Add Honda-Bosch lane line detection signals.

generator/honda/_dual_can_nidec_2018.dbc, honda_fit_hybrid_2018_can_generated.dbc
After _dual_can_nidec_2018.dbc was created following commits were done on
_honda_2017.dbc
- 0132110 : Reverse engineer AEB in Honda
- 7bb1e33 : honda nidec AEB values
- cb27d6e : Honda Nidec: add new ACC_HUD signals to all other cars…
- fa5dc68 : Fix honda dbc files after steer torque addition
Replicating them in _dual_can_nidec_2018.dbc which is basically almost similar to _honda_2017.dbc
But some messages have different structure. (Specially BO_ 506 BRAKE_COMMAND)
=> fix: Replicate changes done on _honda_2017.dbc

subaru_crosstrek_2018.dbc, subaru_global_2017.dbc
Added following signals:
- Transmission Gear and values
- ES_Distance Cruise buttons
- ES_Distance Close_Distance
- ES_Distance ES_Cruise_Throttle
- BodyInfo Wipers
- ES_DashStatus Cruise_Fault
- ES_DashStatus Cruise_State
- STOP_START State
- various filler signals to allow can message copy/rewrite while developing stop and go POC and researching options for long control
=> Fixed signals order and added new signals for subaru global

hyundai_kia_generic.dbc
Values now updated for 2020 Sonata - Older vehicles use MIN/MAX (Name Change) + Jerklimit/ComfortBand Offset (Offset Change)
=> Update SCC ECU Messages for OP Long Dev.

generator/toyota/_toyota_2017.dbc, lexus_ct200h_2018_pt_generated.dbc, lexus_gs300h_2017_pt_generated.dbc, lexus_is_2018_pt_generated.dbc, lexus_nx300h_2018_pt_generated.dbc, lexus_rx_350_2016_pt_generated.dbc, lexus_rx_hybrid_2017_pt_generated.dbc, toyota_avalon_2017_pt_generated.dbc, toyota_camry_hybrid_2018_pt_generated.dbc, toyota_corolla_2017_pt_generated.dbc, toyota_highlander_2017_pt_generated.dbc, toyota_highlander_hybrid_2018_pt_generated.dbc, toyota_nodsu_hybrid_pt_generated.dbc, toyota_nodsu_pt_generated.dbc, toyota_prius_2017_pt_generated.dbc, toyota_rav4_2017_pt_generated.dbc, toyota_rav4_hybrid_2017_pt_generated.dbc, toyota_sienna_xle_2018_pt_generated.dbc
Not sure if these names are accurate. Also not quite sure of their effect other than existing openpilot's usage (or non-usage). These are the best names I can guess to give them for now. They're better than `SET_ME_1` and/or nothing at least?
So, might as well give these signals a name, even if it might not be right, and make some comments on them. Hopefully it makes looking at these in Cabana a little less mysterious.
Unfortunately, merging this in will necessitate some changes to openpilot for tests and the toyota CAN for the existing `SET_ME_1` signal in the accel command: https://github.com/commaai/openpilot/blob/ad2c54e9916301d63907d96c3e9dec046bd016b1/selfdrive/car/toyota/toyotacan.py#L37 . `ACCEL_CMD_ALT` can be left unimplemented as a value of `0` for it is accepted fine like …
=> Toyota ACC_CONTROL PERMIT_BRAKING and ACCEL_CMT_ALT speculated definition

subaru_crosstrek_2018.dbc, subaru_global_2017.dbc
Added new messages and signals, mostly related to testing and developing Openpilot longitudinal control on global platform (Crosstrek 2018):
- Brake_Status (Brake pedal and ES_Brake status feedback for Eyesight)
- Cruise_Status (second message with CruiseControl status info)
- AC_State (A/C state)
New and updated signals:
- Throttle Throttle_Combo
- Transmission RPM
- Brake Pedal Brake_Lights
- ES_Brake Cruise_*
- ES_Distance Cruise_*
- ES_Status Cruise_*
- Dashlights Counter (both crosstrek and global dbc)
- BodyInfo Brake
- ES_DashStatus Conventional_Cruise
- ES_DashStatus Cruise_Soft_Disable
- Steering_Torque Steer_Warning
- Brake_Pedal Speed
- ES_LKAS_State LKAS_*
=> Subaru DBC update

generator/toyota/_comma.dbc, lexus_ct200h_2018_pt_generated.dbc, lexus_gs300h_2017_pt_generated.dbc, lexus_is_2018_pt_generated.dbc, lexus_nx300_2018_pt_generated.dbc, lexus_nx300h_2018_pt_generated.dbc, lexus_rx_350_2016_pt_generated.dbc, lexus_rx_hybrid_2017_pt_generated.dbc, toyota_avalon_2017_pt_generated.dbc, toyota_camry_hybrid_2018_pt_generated.dbc, toyota_corolla_2017_pt_generated.dbc, toyota_highlander_2017_pt_generated.dbc, toyota_highlander_hybrid_2018_pt_generated.dbc, toyota_nodsu_hybrid_pt_generated.dbc, toyota_nodsu_pt_generated.dbc, toyota_prius_2010_pt.dbc, toyota_prius_2017_pt_generated.dbc, toyota_rav4_2017_pt_generated.dbc, toyota_rav4_hybrid_2017_pt_generated.dbc, toyota_sienna_xle_2018_pt_generated.dbc
Fix duplicate signal names inside one message (_comma.dbc and generated files)
=> Fix duplicate signal names inside one message

gm_global_a_lowspeed_1818125.dbc
`ms arc` is not a standard abbreviation for milliarcseconds and is ambiguous for `milliseconds * arcseconds`. The correct abbreviation is `mas`.
Also, `ltres` is not an abbreviation for liters, and is inconsistent since `ltres`, `l`, and `liters` are all used in this file.
=> Fix non-standard units in GM global A lowspeed

chrysler_pacifica_2017_hybrid.dbc
This message appears to be an indication of current cruise state, both ACC and Non-ACC modes as well as engaged/disengaged and off states. 
Found from this route - 3c946decd6bc40b9|2020-12-23--09-52-15 
Drive starts with all cruise off. Around 64 seconds in Cruise Control is turned on (non acc). Around 98 seconds Cruise Control is engaged, disengaged at ~128 seconds, and Cruise control is turned off ~146 seconds. 
ACC is turned on ~188 seconds, ~237 seconds ACC is engaged, ~307 ACC is disengaged and ~361 ACC is turned off. 
Plots attached
=> Pacifica: Add cruise state indicator

hyundai_kia_generic.dbc
first step for controlling ACC speed using `HDA_VSetReq` signal
some of the modified signals are currently used by openpilot
=> hyundai: update LFAHDA_MFC for HDA

generator/toyota/_toyota_2017.dbc, lexus_ct200h_2018_pt_generated.dbc, lexus_gs300h_2017_pt_generated.dbc, lexus_is_2018_pt_generated.dbc, lexus_nx300_2018_pt_generated.dbc, lexus_nx300h_2018_pt_generated.dbc, lexus_rx_350_2016_pt_generated.dbc, lexus_rx_hybrid_2017_pt_generated.dbc, toyota_avalon_2017_pt_generated.dbc, toyota_camry_hybrid_2018_pt_generated.dbc, toyota_corolla_2017_pt_generated.dbc, toyota_highlander_2017_pt_generated.dbc, toyota_highlander_hybrid_2018_pt_generated.dbc, toyota_nodsu_hybrid_pt_generated.dbc, toyota_nodsu_pt_generated.dbc, toyota_prius_2017_pt_generated.dbc, toyota_rav4_2017_pt_generated.dbc, toyota_rav4_hybrid_2017_pt_generated.dbc, toyota_sienna_xle_2018_pt_generated.dbc
See https://github.com/commaai/openpilot/pull/2708
We're still missing a few values. Are there also values for adaptive hold up and hold down? 11 & 12?
=> add more Toyota CRUISE_STATE values

hyundai_kia_generic.dbc
length was wrong and found checksum/counter
this message seems to be full of two bit signals
I don't understand what this message is, but power steering doesn't work without it and it gates parsing of EMS16, 366_EMS and LVR12 in the firmware
=> hyundai: add P_STS counter and checksum

hyundai_kia_generic.dbc
seems clearly wrong looking at stock drive, updating the scale/offset to match specified range makes sense
=> hyundai: fix scc14 comfort band/jerk

hyundai_kia_generic.dbc
When I launch cantools with hyundai_kia_generic.dbc:
```
$ cantools monitor -c can0 hyundai_kia_generic.dbc
```
**Errors occure:** 
- error: DBC: "Invalid syntax at line 1568, column 10: "BO_ 1191 >>!<<4a7MFC: 8 XXX""
- error: DBC: "Invalid syntax at line 1604, column 9: "BO_ 870 >>!<<366_EMS: 8 EMS""
- error: DBC: "Invalid syntax at line 1611, column 9: "BO_ 854 >>!<<356: 8 XXX""
**Solution:**
- Rename the message so that they don't start with numbers.
=> Fix errors when using cantools with hyundai_kia_generic.dbc

can/common.h, can/parser.cc
CanParser doesn't seem to be used in multiple threads.added a cached buffer to avoid memory allocation
=> update_string: use cached buffer

FORD_CADS.dbc
This DBC file is for the ford MRR/CADS (Ford nomenclature is CADS) used since 2018 in basically everything (seen in fiesta, focus and f150). Whilst I haven't checked I think it is highly likely that this will be the radar used in the new fords with the "Assist 2.0" system. This radar is manufactured by Delphi automotive, seems to be an evolution of the previous ESR that older fords used such as the fusion/Mondeo. 
This DBC also contains the messages for calibration and fault logging but I haven't experimented with using them.
I have tested this DBC extensively with a ford radar part number H1BT-9G768-AG off a fiesta as well as someone else testing it with a focus radar (JX7T-9G768-AC) and have confirmed it to be correct.
Adding this would be necessary for future ford work however this …
=> Ford MRR/CADS Support

cadillac_ct6_powertrain.dbc, gm_global_a_powertrain.dbc
Very useful for INDI, and related to https://github.com/commaai/openpilot/issues/20232 
Tasks complete:
- ~~spin wheel to stops at 90deg/sec~~ Good: rate matches intended & measured angle over time.
- ~~try to decode last byte, probably checksum~~ Not able now.
- ~~merge / generate GM and Cadillac~~ Not now.
=> GM steering rate scale & limits fix

vw_golf_mk4.dbc
Used by the Volkswagen community PQ35/PQ46/NMS port. Nothing comma-upstream uses this, so there will not yet be a corresponding openpilot PR.
LDW_1 still needs to be cleaned up and synced with the MQB version, but I'll have to do that in a future PR.
=> VW PQ: New and updated CAN messaging

can/parser.cc
make it easy to track down the address(es) causing can receive errors
=> log missing addrs that are validated

generator/subaru/_subaru_global.dbc, generator/subaru/_subaru_preglobal_2015.dbc, generator/subaru/subaru_forester_2017.dbc, generator/subaru/subaru_global_2020_hybrid.dbc, generator/subaru/subaru_outback_2015.dbc, generator/subaru/subaru_outback_2019.dbc, subaru_forester_2017_generated.dbc, subaru_global_2017_generated.dbc, subaru_global_2020_hybrid_generated.dbc, subaru_outback_2015_generated.dbc, subaru_outback_2019_generated.dbc
This PR:
- adds filler signals for Global and Preglobal Throttle message (used for stop and go implementation)
- unifies some Preglobal signal names with Global
- adds new Preglobal Dash_State2 message for ACC mph/kph units
- adds new 2020 Crosstrek Hybrid Brake_Hybrid message
=> Subaru Preglobal signals unification, new messages

vw_mqb_2010.dbc
Add an EPS HCA status VAL enum. I'm planning to use this to fix a bug with VW MQB steering fault handling.
While I'm here, clean up some signal comments to match the recent EPS_01 -> LH_EPS_03 refactor.
=> VW MQB: EPS HCA status enum, comment cleanup

vw_mqb_2010.dbc
Add signals necessary for detecting comfort/convenience turn signal operation.
=> VW MQB: Add detail to Blinkmodi_02

generator/subaru/_subaru_global.dbc, generator/subaru/_subaru_preglobal_2015.dbc, subaru_forester_2017_generated.dbc, subaru_global_2017_generated.dbc, subaru_global_2020_hybrid_generated.dbc, subaru_outback_2015_generated.dbc, subaru_outback_2019_generated.dbc
This PR adds new Dashlights UNITS signal for Subaru Global models and changes Preglobal Dash_State2 UNITS signal. Both have been in use in subaru-community branch since beginning of July and they have been working reliably for all supported models.
=> Subaru ACC speed units signals update

cadillac_ct6_powertrain.dbc, gm_global_a_powertrain.dbc
With these changes, my 2019 Chevy Bolt reports the correct Longitude.
=> Updated Longitude with correct offset.

can/parser_pyx.pyx
explicit `d[foo] = {}` not needed if `d` is `defaultdict(dict)`
=> clean up CANDefine constructor

hyundai_kia_generic.dbc
This PR adds the message containing speed limit data that is shown on some Hyundai navigation systems, gauge clusters and heads up displays.
=> Add LFA button and speed limit signal for newer Hyundai cars.

generator/subaru/_subaru_global.dbc, subaru_global_2017_generated.dbc, subaru_global_2020_hybrid_generated.dbc
This PR adds and fixes signals in Subaru Global ES_DashStatus and ES_LKAS_State messages, mainly so we can filter out some confusing stock ACC and LKAS dash notification messages while openpilot is active. I will open related openpilot and panda PR-s soon
=> Subaru Global Dash state and LKAS messages

vw_golf_mk4.dbc
mMotor_Bremse used to control braking on cars that don't support ACC.
mAWV used to control ACC led in dashboard.
=> Add PQ Braking and ACC led control CAN messages

volvo_v40_2017_pt.dbc, volvo_v60_2015_pt.dbc
Just added signals for brakepress and turnsignal on v40. Then a small asthetic fix for the byter order in one of the messages.
=> Turn signal and brakepress signal update for v40 and byte order fix

vw_golf_mk4.dbc
Two fixes, prerequisites for commaai/panda#762.
1. Fix the overall message length, which was easy to find
2. Fix invalid endianness on the counter signal, which took considerably longer to find
The second problem caused some very strange CAN packer output. ISTM adding an assert somewhere might be a good idea.
=> VW PQ: Corrections to Lenkhilfe_3

generator/subaru/_subaru_global.dbc, generator/subaru/_subaru_preglobal_2015.dbc, generator/subaru/subaru_forester_2017.dbc, subaru_forester_2017_generated.dbc, subaru_global_2017_generated.dbc, subaru_global_2020_hybrid_generated.dbc, subaru_outback_2015_generated.dbc, subaru_outback_2019_generated.dbc
This PR:
- Adds Engine Stop-Start signals for global
- Renames preglobal ES_ThrottleCruise message to ES_Distance to match global message and signals
- Fixes/updates preglobal Car_Follow signal in ES_Distance (used for SNG)
- Adds Brake, Cruise_Activated, Car_Follow and Far_Distance signals to ES_DashStatus message for Forester
I will submit openpilot PR for ES_Distance change and separate PR for adding SNG support
=> Subaru signals update

generator/toyota/_toyota_2017.dbc, lexus_ct200h_2018_pt_generated.dbc, lexus_gs300h_2017_pt_generated.dbc, lexus_is_2018_pt_generated.dbc, lexus_nx300_2018_pt_generated.dbc, lexus_nx300h_2018_pt_generated.dbc, lexus_rx_350_2016_pt_generated.dbc, lexus_rx_hybrid_2017_pt_generated.dbc, toyota_avalon_2017_pt_generated.dbc, toyota_camry_hybrid_2018_pt_generated.dbc, toyota_corolla_2017_pt_generated.dbc, toyota_highlander_2017_pt_generated.dbc, toyota_highlander_hybrid_2018_pt_generated.dbc, toyota_nodsu_hybrid_pt_generated.dbc, toyota_nodsu_pt_generated.dbc, toyota_prius_2017_pt_generated.dbc, toyota_rav4_2017_pt_generated.dbc, toyota_rav4_hybrid_2017_pt_generated.dbc, toyota_sienna_xle_2018_pt_generated.dbc
This PR is not mission critical, just adding more signal definitions.
In Japan, Toyota has this service called ITS Connect, if RADAR Cruise detects an ITS Connect capable car ahead, it will display the lead car with a green ring and two wireless indicators around it.
It's called Communication Enabled Radar Cruise Control (https://global.toyota/jp/download/10064634/)
=> Toyota: add ITS Connect Lead Signal

generator/toyota/_toyota_nodsu_common.dbc, generator/toyota/toyota_nodsu_hybrid_pt.dbc, generator/toyota/toyota_nodsu_pt.dbc, toyota_nodsu_hybrid_pt_generated.dbc, toyota_nodsu_pt_generated.dbc
I moved the common signals to `_toyota_nodsu_common.dbc`, and fixed the comments for the `BRAKE_MODULE` having the wrong address.
=> Toyota: clean up nodsu DBCs

generator/toyota/_toyota_2017.dbc, lexus_ct200h_2018_pt_generated.dbc, lexus_gs300h_2017_pt_generated.dbc, lexus_is_2018_pt_generated.dbc, lexus_nx300_2018_pt_generated.dbc, lexus_nx300h_2018_pt_generated.dbc, lexus_rx_350_2016_pt_generated.dbc, lexus_rx_hybrid_2017_pt_generated.dbc, toyota_avalon_2017_pt_generated.dbc, toyota_corolla_2017_pt_generated.dbc, toyota_highlander_2017_pt_generated.dbc, toyota_highlander_hybrid_2018_pt_generated.dbc, toyota_nodsu_hybrid_pt_generated.dbc, toyota_nodsu_pt_generated.dbc, toyota_prius_2017_pt_generated.dbc, toyota_rav4_2017_pt_generated.dbc, toyota_rav4_hybrid_2017_pt_generated.dbc, toyota_sienna_xle_2018_pt_generated.dbc
added signal reflects camera parameters from head unit
3 = minimal guidelines (a single red line on the display)
2 = static guidelines (a cross with lines indicating vehicle edges on the display)
1 = active guidelines
=> Toyota: add reverse camera state

generator/toyota/_toyota_2017.dbc, lexus_ct200h_2018_pt_generated.dbc, lexus_gs300h_2017_pt_generated.dbc, lexus_is_2018_pt_generated.dbc, lexus_nx300_2018_pt_generated.dbc, lexus_nx300h_2018_pt_generated.dbc, lexus_rx_350_2016_pt_generated.dbc, lexus_rx_hybrid_2017_pt_generated.dbc, toyota_avalon_2017_pt_generated.dbc, toyota_corolla_2017_pt_generated.dbc, toyota_highlander_2017_pt_generated.dbc, toyota_highlander_hybrid_2018_pt_generated.dbc, toyota_nodsu_hybrid_pt_generated.dbc, toyota_nodsu_pt_generated.dbc, toyota_prius_2017_pt_generated.dbc, toyota_rav4_2017_pt_generated.dbc, toyota_rav4_hybrid_2017_pt_generated.dbc, toyota_sienna_xle_2018_pt_generated.dbc
Expanding Toyota's BCM signals.
`METER_SLIDER_BRIGHTNESS_PCT`: combination meter's brightness value, ranging from 12% to 100%. Changes based on the brightness knob/slider's position.
`METER_SLIDER_LOW_BRIGHTNESS`: set to 1 when combination meter display is in low brightness mode, dash lights are not affected. Footwell lights are turned off if this is 1. Example:
`METER_SLIDER_DIMMED`: set to 1 when the slider is not full. This is different to the signal on 0x620, that signal is only turned on when the headlights are on, this signal is turned on when the meter adjustment knob/slider isn't at max.
Documented behaviours are observed on my 2018 Prius.
=> Toyota: expand BCM signals

generator/gm/gm_global_a_powertrain.dbc, gm_global_a_powertrain_generated.dbc
The signal specification for EngineRPM was 2 bits too short, and the value was being truncated at 4096 RPM. When this happened, the RPM appeared to wrap around to zero.
Updating the dbc to increase the field to the full 16-bits resolves the issue, and the correct RPM value is available.
Note that this signal is not presently used anywhere in OP - the bug was discovered by @twilsonco (thanks!).
=> GM bugfix: ECMEngineStatus.EngineRPM value incorrect over 4096 due to truncation

generator/gm/gm_global_a_powertrain.dbc, gm_global_a_powertrain_generated.dbc
The existing signal used to determine the gear shifter position does not differentiate between "D" and "L" and does not include the Manual Mode available on some larger vehicles, nor is Neutral included.
This new signal has a distinct value for each shifter position. Differentiating between "D" and "L" is important especially for EVs and Hybrids where "L" mode is also known as single pedal mode. In this mode the gas pedal will perform regenerative braking.
The message - 501 - is present in all the current fingerprints.
The main value - PRNDL2 Actually supplies all of Park, Reverse, Neutral, Drive and "L" as opposed to the first identified. In EV/Hybrids, "L" refers to single-pedal mode. This signal's meaning changes slightly depending on the value of the ManualMode flag. The details are …
=> GM: add new ECMPRDNL2 message with more detailed transmission / gear status

can/common.h, can/common.pxd, can/common_dbc.h, can/parser.cc, can/parser_pyx.pyx
Was set with 0 before, and setting with logMonoTime doesn't give us any more information as it's guaranteed that we receive messages in the same order here: https://gist.github.com/sshane/93d1adab1570dbbf1c2c1fadcfd227b4
=> CANParser: remove ts field

can/common.h, can/common.pxd, can/common_dbc.h, can/parser.cc, can/parser_pyx.pyx, can/tests/test_packer_parser.py
- Only returns updated values from cpp's update_vl/query_latest, as before
- Only keeps one copy of the data under the address
- Converts message name into address only when accessing data
- The updated values data is kept track of in C++ CANParser for practically free
- Then when the Cython `updated` field is accessed, only then do we pull from that C++ map and access the message/signal we need
Test includes updating strings/parsing, updating the Cython CANParser's fields, and then a Toyota radar interface to simulate grabbing messages by string.
- Before #548: on average `0.25845228492` s
- After #548: on average `0.896` s
- This PR: on average `0.198003333` s
Just the `__pyx_convert_vector_to_py_double` operation for converting the updated_vals vector from C++ to Python raises the …
=> CANParser: add field for all values from a cycle

can/parser_pyx.pyx, can/tests/test_packer_parser.py
Don't clear `vl_all` inside `update_string` so we don't throw away any updated values before returning to the CANParser user
Average before: `(.3018515+.30946+.295825+.289596+.288537+.2926395+.28401279+.28353)/8=0.293181474` seconds
Average now: `(.27749109+.303485+.2765805+.295201+.26981163+.270950555)/6=0.282253296` seconds
=> CANParser: fix missing updated values

requirements.txt
I've been scratching my head about building Plotjuggler recently and found there was a package which was deprecated that opendbc builds with. The latest version of Plotjugger fails to build due to the requirements.txt in opendbc. 
**Steps to reproduce the issue:**
1. Download a clean installation of Plotjuggler. Consider modifying the command which runs docker in build.sh to use "--no-cache".
2. Initialize and update submodules.
3. run build.sh
**Error:**
markupsafe can't find softunicode
**Reason for this problem:**
Markupsafe has deprecated soft unicode
https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0
In requirements.txt of opendbc:
Jinja2==2.11.3
Jinja2 is looking for soft_unicode, so obviously it crashes.
**Fix:**
Update Jinja2 to a version which supports …
=> Update Jinja2 to fix markupsafe error

generator/toyota/toyota_nodsu_pt.dbc, toyota_nodsu_pt_generated.dbc
Dashcam LTA route:
4aa5d874f367adbc|2022-02-20--22-59-18
“Stock” LTA OP
4aa5d874f367adbc|2022-02-21--18-22-18
"Broken" OP LTA route (would not steer):
4aa5d874f367adbc|2022-02-21--18-37-54
Dashcam with disablements (LTA OEM steer overrides)
4aa5d874f367adbc|2022-02-22--14-47-21
Dadcam mode TSS2.5 stock
f15e3c37c118e841|2022-02-18--13-58-56
=> Toyota: comments for LTA steering signals

can/packer.cc
This was removed in #573 but is still used in plotjuggler
=> Put back parser::lookup_message

can/dbc.py
Required to parse certain German Engineered™ signal comments.
Examples to come:
```
CM_ SG_ 385 VZE_Anzeigemodus "Steuert die verschiedenen Möglichkeiten der Anzeige, vor allem die Aktivierung sowie die erweiterten Anzeigen im Kombi";
CM_ SG_ 385 VZE_Hinweistext "Über Index wird ein Hinweistext beschrieben, der durch das Kombi dargestellte werden soll.
Wertebereich lt. Hashtabelle";
CM_ SG_ 385 VZE_Statuszaehler_1 "Steuerungssignal zur Steuerung des Distanzzählers von Verkehrszeichen 1";
CM_ SG_ 385 VZE_Statuszaehler_2 "Steuerungssignal zur Steuerung des Distanzzählers von Verkehrszeichen 2";
CM_ SG_ 385 VZE_Statuszaehler_3 "Steuerungssignal zur Steuerung des Distanzzählers von Verkehrszeichen 3";
```
=> Allow UTF-8 characters in DBC files

vw_mqb_2010.dbc
Add a duplicate enum value for Tiptronic in sport/race mode, which the transmission handles a little differently from the manumatic program used in normal and eco modes. Fixes "gear not D" when trying to engage while in sport/race Tip mode.
Verified the different enum value in `3cfdec54aa035f3f|2022-04-08--20-06-57`, and also against the official DBC enum, which we don't use in openpilot to maintain code commonality with other car ports.
`VAL_ 173 GE_Fahrstufe 0 "Zwischenstellung" 1 "Init" 5 "Position_P" 6 "Position_R" 7 "Position_N" 8 "Position_D" 9 "Position_S" 10 "Effizienz" 13 "Tipp_in_S" 14 "Tipp_in_D" 15 "Fehler" ;`
No changes required to openpilot, other than an opendbc bump.
=> VW MQB: Detect sport-manumatic shift program

can/parser.cc
I was getting a build error for this missing import...
```
opendbc/can/parser.cc:111:32: error: no member named 'numeric_limits' in namespace 'std'
bus_timeout_threshold = std::numeric_limits<uint64_t>::max();
~~~~~^
opendbc/can/parser.cc:111:47: error: unexpected type name 'uint64_t': expected expression
bus_timeout_threshold = std::numeric_limits<uint64_t>::max();
^
opendbc/can/parser.cc:111:58: error: no member named 'max' in the global namespace
bus_timeout_threshold = std::numeric_limits<uint64_t>::max();
~~^
3 errors generated.
scons: *** [opendbc/can/parser.os] Error 1
scons: building terminated because of errors.
```
I'm using Ubuntu 22.04 (sorry) with clang 14.0.0-1ubuntu1, if that matters
=> add missing import for std::numeric_limits<...>::max()

generator/toyota/_toyota_2017.dbc, toyota_new_mc_pt_generated.dbc, toyota_nodsu_pt_generated.dbc, toyota_tnga_k_pt_generated.dbc
The `DISTANCE` signal is used to cycle through different following distances, the following distance goes from long to medium to short on every instances where the signal is set to `1`, I misinterpreted the signal before and put the wrong description in the dbc file, fixing it now.
PR is also rearranging `ACC_CONTROL` in numerical order.
=> Toyota: fix description of DISTANCE signal

vw_mqb_2010.dbc
We will need `Kombi_03.KBI_Variante` for openpilot longitudinal, to identify analog vs digital/full-screen instrument clusters, because they expect the lead-car distance HUD value to be scaled differently.
=> VW MQB: Populate Kombi_03 signals

generator/gm/gm_global_a_powertrain.dbc, gm_global_a_powertrain_generated.dbc
GM port / dbc only had a signal for Electronic parking brakes - in vehicle with manual parking brakes (Suburban, Tahoe, trucks)  the entire message used for EPBs is missing and there is only a manual brake.
This update to the GM powertrain dbc adds a new flag to the VehicleIgnitionAlt message that returns true for both electronic and manual parking brakes.
**I coordinated a button press with depressing the parking brake - this first image shows this visual alignment from the Suburban:**
**I then confirmed with verylukyguy's Acadia (that has an EPB) that the flag goes high for both Electronic and Manual parking brakes:**
=> GM: Add ParkBrake signal for manual parking brakes

generator/toyota/_toyota_2017.dbc, toyota_new_mc_pt_generated.dbc, toyota_nodsu_pt_generated.dbc, toyota_tnga_k_pt_generated.dbc
Toyota applies an offset to the speedometer, the value after the offset is available over CAN.
Edit:
This signal might actually be 16-bit, but 255 seems to be a pretty reasonable max speed for a roadworthy vehicle. Besides, I can't test this theory anyway as I drive a Prius and GTS's test only goes to 180km/h.
:D
This signal is always in the vehicle's unit of measurement, just like `UI_SET_SPEED` in `PCM_CRUISE_SM`. If any of you want to get your comma device's display speed to sync up with your vehicle's display speed, this is the signal to use.
=> Toyota UI Display Speed

can/dbc.cc
Specifically for the counter and checksum checks, nice to have
```python
In [2]: from opendbc.can.packer import CANPacker
...: CANPacker("toyota_nodsu_pt_generated")
terminate called after throwing an instance of 'std::runtime_error'
what():  [toyota_nodsu_pt_generated:524]  CHECKSUM starts at wrong bit
```
=> dbc parser: add line number to errors

generator/toyota/_toyota_2017.dbc, toyota_new_mc_pt_generated.dbc, toyota_nodsu_pt_generated.dbc, toyota_tnga_k_pt_generated.dbc
Used by the stock PCM adaptive cruise control to determine how close the lead should be followed. This changes with each press of the distance button, and cycles from 1 to 2 to 3.
=> Toyota: Follow Distance Signal

can/dbc.cc
Cherrypicked from #633 for independent consideration.
There's no reason we have to do these checks, other than we've always done them. They are now interfering with VW PQ, which has a few four-bit aligned counters, and a genuinely unaligned counter in Getriebe_1. Checksums and counters start at the bit the vehicle manufacturer chooses, we can't change them if we don't like them.
=> remove checksum and counter alignment checks

acura_ilx_2016_can_generated.dbc, acura_rdx_2018_can_generated.dbc, acura_rdx_2020_can_generated.dbc, generator/honda/_bosch_2018.dbc, generator/honda/_dual_can_nidec_2018.dbc, generator/honda/_honda_common.dbc, generator/honda/_nidec_2017.dbc, honda_accord_2018_can_generated.dbc, honda_civic_hatchback_ex_2017_can_generated.dbc, honda_civic_touring_2016_can_generated.dbc, honda_clarity_hybrid_2018_can_generated.dbc, honda_crv_ex_2017_can_generated.dbc, honda_crv_executive_2016_can_generated.dbc, honda_crv_touring_2016_can_generated.dbc, honda_fit_ex_2018_can_generated.dbc, honda_fit_hybrid_2018_can_generated.dbc, honda_insight_ex_2019_can_generated.dbc, honda_odyssey_exl_2018_generated.dbc, honda_odyssey_extreme_edition_2018_china_can_generated.dbc
For Nidec:
- Renames unused `HUD_DISTANCE_3` to `ACC_ON` used by Bosch
- Add "kph" unit to `CRUISE_SPEED`
For Bosch:
- Adds `PCM_SPEED`, `PCM_GAS`, `CHIME`, `ICONS` signals
- Renames `SET_TO_1` to `FCM_OFF`, `FCM_OFF` to `FCM_OFF_2`
=> Move common ACC_HUD message to _honda_common

chrysler_pacifica_2017_hybrid.dbc
Some easy to verify signals moved from https://github.com/commaai/opendbc/pull/628. Posted verification data there. Purpose of this PR is for support of the upcoming RAMs, these signal definitions are identical with the only difference being the address, simplifies panda safety and openpilot
=> Chrysler: use universal gas and brake signals

generator/subaru/_subaru_global.dbc, generator/subaru/_subaru_preglobal_2015.dbc, generator/subaru/subaru_forester_2017.dbc, generator/subaru/subaru_global_2017.dbc, generator/subaru/subaru_outback_2015.dbc, generator/subaru/subaru_outback_2019.dbc, subaru_forester_2017_generated.dbc, subaru_global_2017_generated.dbc, subaru_global_2020_hybrid_generated.dbc, subaru_outback_2015_generated.dbc, subaru_outback_2019_generated.dbc
This PR adds scaling factors to ACC Close_Distance (<5m) and Far_Distance (5-75m, 5m steps) signals for converting the raw values to meters. Close_Distance signal is used as input for SnG (https://github.com/commaai/openpilot/pull/23025)
=> Subaru: Use SI units for ACC distance signals

chrysler_ram_hd_generated.dbc, generator/chrysler/.gitignore, generator/chrysler/_stellantis_common_ram.py, generator/chrysler/chrysler_ram_dt.dbc, generator/chrysler/chrysler_ram_hd.dbc
This adds the needed messages to incorporate the Ram HD trucks. 
I have changed the names of 678 and 658 to more accurate names. 
Updated signals to uppercase to be uniform.
=> Chrysler: add Ram HD

generator/gm/gm_global_a_powertrain.dbc, gm_global_a_powertrain_generated.dbc
Added signals for Rolling Counter and Checksum to ASCMSteeringButton message.
Needed if OP is going to send button presses to the camera (To hopefully disengage the ACC)
=> GM: add counter and checksum for ASCMSteeringButton

cadillac_ct6_powertrain.dbc, generator/gm/gm_global_a_powertrain.dbc, gm_global_a_powertrain_generated.dbc
Will need to fix openpilot
Not sure why were doing this in openpilot when: `(int(target_speed_kph * 16) & 0xfff) == int(target_speed_kph / .0625)`
=> GM: fix set speed scaling

generator/gm/gm_global_a_powertrain.dbc, gm_global_a_powertrain_generated.dbc
Add and cleanup some signals in GM Powertrain DBC
* ECMVehicleSpeed contains signals based on the left and right tire - add VehicleSpeedLeft and comment regarding spin of right tire.
* ECMEngineStatus contains a signal for the active state of standard Cruise Control: added CruiseActive
* Cleaned up AEBCmd signal names to better align with other messages (Message is not yet in use)
* Added AEBCmd2
* Corrected size of AEBCmd
The operation of the AEB message is still being reverse engineered: having the updated definition will aid in analysis in plotjugger and Cabana
=> GM: Add signals, correct AEB signal sizes and standardize names

Dockerfile, requirements.txt
Fix for https://github.com/commaai/opendbc/issues/663
The dockerfile doesn't work on ARM arch because some of the python dependencies build from source for ARM.
Pycapnp has a bug that prevents building from source in version 1.0.0. The bug is fixed in version 1.1.0. of pycapnp. Info on pycapnp bug: https://github.com/capnproto/pycapnp/issues/240
Furthermore, pycapnp needs to build its own dependency libpcap. This requires cmake, which isn't installed in the container. So we need to add that.
This PR makes two changes to fix the build on arm:
1) In requirements.txt, bump the pinned version of pycapnp from 1.0.0 to 1.1.0.
2) In the dockerfile: add cmake to apt-get at beginning of Dockerfile. This is necessary so pycapnp can build its dependency libcapnp.
If the project maintainers are …
=> add cmake to docker to fix build on arm

generator/gm/gm_global_a_powertrain.dbc, gm_global_a_powertrain_generated.dbc
As part of the process to fill out the standard CC messages, a Message containing the CC SetSpeed in Km/h was discovered, and it scales / operates much the same as the ACC equivalents - the value must be divided by 16 to get km/h.
Note: While there are other pieces to the message, no other meanings could be decoded.
The attached CC was initially set to 69. Each step up and down is the result of a single press of the SET or RESUME buttons. Turning off the CC system resets the speed value back to zero.
This allows OP to get the set-speed from either type of Cruise Control, in essentially the same way
=> GM: Add Standard Cruse Message, SetSpeed signal

ford_lincoln_base_pt.dbc
Found another unknown signal in the `IPMA_Data` message which goes high after about 90 seconds in this route: `59a107f5793d9cc0|2022-08-07--00-13-33`
=> ford: another mystery bit

ford_lincoln_base_pt.dbc
The signal ranges seem to be "off center" in the Ford DBC... This might be causing the steering control issues.
Show above is the LCA message when the system can't detect any lane lines. You can see that the path angle signal is non zero.
Example segments:
`59a107f5793d9cc0|2022-08-06--14-11-17--0` at 2.5 seconds
`59a107f5793d9cc0|2022-08-07--00-13-33--0` at 2.9 seconds
`86d00e12925f4df7|2022-08-11--16-45-58--0` at 10.6 seconds
=> Ford: fix steering command signal ranges

generator/toyota/_toyota_2017.dbc, toyota_new_mc_pt_generated.dbc, toyota_nodsu_pt_generated.dbc, toyota_tnga_k_pt_generated.dbc
Some notes:
- Message exists on all Toyota and Lexus. Signal on all Toyota and Lexus is never 0 (unlike `UI_SETTING->UNITS` or `RSA2->SPUNT`, which then fall back to msg `AVN1S21`)
- Signal seems to be identical to `AVN1S21->A_SPDUNT` on cars that have 0x435 on the bus (not all)
- Describes not only units, but gas mileage represenation preference (for ex. `litres per 100km vs km per litre`, why there's four values)
=> Toyota: add universal units signal

can/parser.cc, can/tests/test.dbc, can/tests/test_packer_parser.py
This PR adds test for one edge case found while debugging why Eyesight started faulting after https://github.com/commaai/opendbc/commit/859fea7ded706516f4b963218a3c9cf543f39c2a on subaru longitudinal branch (https://github.com/commaai/openpilot/pull/25345). Fault did not occur when I disabled Brake_Status and CruiseControl filtering in panda fwd hook and allowed stock messages to pass through. 
Brake_Status signal values debug output from subarucan showed that Signal1 output value changed after the https://github.com/commaai/opendbc/commit/859fea7ded706516f4b963218a3c9cf543f39c2a:
```
working
--
send brake_status
{'Brake': 0.0,
'CHECKSUM': 193.0,
'Counter': 1.0,
'ES_Brake': 0,
'Signal1': 57174604644354.0,
'Signal2': 4.0,
'Signal3': 0.0}
--
fault
--
send brake_status
{'Brake': 0.0, …
```
=> Add test for Subaru Brake_Status Signal1 large value

hyundai_canfd.dbc
This signal is signed, but only for the Tucson Hybrid. Its zero is -4 to -5. Confirms the signal is 2 bytes.
=> HKG CAN-FD: BRAKE_POSITION is signed

hyundai_canfd.dbc
DriverBrakingLowSens is also based on `BRAKE->BRAKE_POSITION`, but is much less sensitive
=> HKG CAN-FD: rename brake signal

Dockerfile
treat cereal the same as opendbc, remove .git for both
=> [docker] rm cereal .git folder

generator/gm/gm_global_a_powertrain.dbc, gm_global_a_powertrain_generated.dbc
used a script to find all bits similar to CS.brakePressed, ended up finding bits and continuous signals. may be helpful in resolving some more faults
=> GM: add new undefined brake-related signals

generator/gm/gm_global_a_powertrain.dbc, gm_global_a_powertrain_generated.dbc
To fix a fault where you can engage while backing up after going into D (before you stop)
=> GM: add bits for moving backwards

can/dbc.cc
Fixes compilation with `clang version 14.0.6`.
```
opendbc/can/dbc.cc:184:50: error: no template named 'ostream_iterator' in namespace 'std'; did you mean 'ostreambuf_iterator'?
std::copy(words.begin(), words.end(), std::ostream_iterator<std::string>(s, " "));
~~~~~^~~~~~~~~~~~~~~~
ostreambuf_iterator
```
=> add missing iterator include

generator/toyota/_toyota_2017.dbc, toyota_new_mc_pt_generated.dbc, toyota_nodsu_pt_generated.dbc, toyota_tnga_k_pt_generated.dbc
All these describe the same signal. Can be 1 when msgs are blocked which causes the PCM to disallow engagement. Right now we silently disengage if this happens
=> Toyota: add ACC faulted signals

requirements.txt
A bug (https://github.com/PyCQA/pylint/issues/3098) was fixed in 2.5.0 relating to detecting abstract subclasses, bump to 2.5.2 like panda.
@adeebshihadeh somehow the panda docker is installing 2.4.3 in CI, causing a PR to fail static analysis which shouldn't, can that be affected by opendbc's pylint version? That's why I'm bumping it
=> Bump pylint version

requirements.txt
pylint 2.12.0 has a fix for relative imports introduced in 2.5.1, bump to the openpilot version instead.
Likely introduced here: https://github.com/PyCQA/pylint/commit/a6d7ffc4679b0ad2258cf6c31c6dfbeeb2b331ef
Related issues:
- https://github.com/PyCQA/pylint/issues/5131
- https://github.com/PyCQA/pylint/issues/2967
=> Bump pylint

mazda_2017.dbc
Vehicle acceleration of x and y axis is in BRAKE message with different resolution. I assume it is NED frame.
Verified with Comma 3 accelerometer data:
=> Mazda: Add vehicle acceleration of x and y axis (NED)

mazda_2017.dbc
Add MRCC vehicle ahead distance display on gauge.
Ref: https://www.mazdausa.com/static/manuals/2023/cx-5/contents/05282601.html
=> Mazda: add MRCC vehicle ahead distance on gauge

can/common.pxd, can/common_dbc.h, can/parser.cc, can/parser_pyx.pyx
Reverts https://github.com/commaai/opendbc/pull/557 and fills out field with logMonoTime of `can` service packet
=> CANParser: add timestamp field

generator/gm/gm_global_a_powertrain.dbc, gm_global_a_powertrain_generated.dbc
=> GM: add friction brake unavailable signal

vw_golf_mk4.dbc
The scaling and offsets for the ACC acceleration comfort band/jerk limit values were flipped. This appears to be data entry error on my part back from #380. Add the VAL enums while I'm here.
This would ordinarily create a process_replay delta if using openpilot longitudinal, because we're no longer sending garbage for comfort band/jerk limit. But VW PQ is dashcam-only with no process_replay route at present. So, this can be merged whenever.
Thanks to @CineXWorm for identifying the issue.
=> VW PQ: Corrected scaling/offsets in ACC_System

vw_golf_mk4.dbc
Corrections for the `Motor_Bremse` brake command message. Some scaling values on the brake percentage and brake pressure signals were off.
The original values are from #422 and may trace back to reverse-engineering or typographical errors. I verified the new values against authoritative data sources.
No urgent need to bump the openpilot submodule reference, this isn't used by upstream openpilot.
Resolves #788. Thanks to @FLcruising for highlighting the issue.
=> VW PQ: Corrected scaling/offsets in Motor_Bremse

vw_golf_mk4.dbc
Fix a bug with the width of the ACA_PrioDisp signal. This will be necessary to fix a known issue with OP long on PQ, wherein the instrument cluster gets "stuck" displaying the lead car and won't allow the driver to switch to other views.
Also fix the name of the message, which is a typographical error on my part from #380. Turns out i before e except after c and also except German. Unfortunately this one is going to require openpilot and panda touches, holding in Draft till I have those.
Added VALs applicable to this message while I'm here.
=> VW PQ: Misc corrections in ACC_GRA_Anzeige

generator/gm/gm_global_a_powertrain.dbc, gm_global_a_powertrain_generated.dbc
See this image, where the driver of a 2023 Bolt EV toggled single pedal mode on and off a few times while driving. I have also confirmed this is accurate with a 2022 Bolt EUV. You should easily be able to verify this with your own EUV.
=> Add single pedal mode signals for Bolt EV/EUV

can/common_dbc.h, can/dbc.cc
=> dbc.cc: put check for duplicate message name behind flag

hyundai_2015_ccan.dbc
The scale of signal `CF_Ems_IsgStat2` should be 1.0 instead of 2.0 because two bits are assigned for the signal. Otherwise, the range of the signal must be [0.0|6.0] rather than [0.0|3.0].
=> hyundai_2015_ccan.dbc: fix signal scale

generator/honda/honda_civic_ex_2022_can.dbc, honda_civic_ex_2022_can_generated.dbc
Since this DBC is (hopefully) going to be used for the entire radarless platform, add the brake module message for the 2023 HR-V, which is what its PCM uses to disengage (there's lots of false positives for the other brake signals). Also has a cruise fault signal, and does _**NOT**_ exist on the 2022 Civic
=> honda_civic_ex_2022: add BRAKE_MODULE

.github/workflows/tests.yml, Dockerfile, requirements.txt
Prep for running unit tests with sanitizers
=> CI: split up jobs + update requirements

can/dbc.cc
related issue: https://github.com/commaai/openpilot/issues/28197
the std::string conversion functions `std::stod`, `std::stoi` `std::stoul` is locale dependent.   It cannot correctly convert the strings in dbc files to number in some locale. for example, `std::stod` will convert 0.005 to 0 in the `ru_RU.UTF-`8
=> dbc:  force C locale for numbers.

can/dbc.cc
Missing include is causing build issues on macos
=> dbc: add missing include for setlocale

can/parser_pyx.pyx
If message name in `signals` was wrong you'd get a key error:
```python
Traceback (most recent call last):
File "/home/batman/.pyenv/versions/3.8.10/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-3-544abaa78a23>", line 2, in <module>
cp = CANParser("nissan_x_trail_2017_generated", signals=[("GAS_PEAL", "CRUISE_THROTLE")], checks=[("CRUISE_THROTTLE", 10)])
File "opendbc/can/parser_pyx.pyx", line 67, in opendbc.can.parser_pyx.CANParser.__init__
s = (s[0], msg_name_to_address[s[1]])
KeyError: 'CRUISE_THROTLE'
```
and if message name in `checks` was wrong you'd get an incorrect print:
```python
Traceback (most recent call last):
File …
```
=> parser: fix wrong message name check/print

generator/subaru/_subaru_global.dbc, subaru_global_2017_generated.dbc, subaru_global_2020_hybrid_generated.dbc
Looks like EyeSight communicates AEB preparation by setting Brake_Pressure commonly along with LKAS_Alert=2 (meaning FCW):
It also winds down brake pressure on disable if it was already braking hard, so we don't want to mark this as AEB:
Here is a real AEB, disabled, with user pressing brake. Signal2 is 8 while it's actuating which looks good. The alert stays on for much longer, so we don't want to use that.
Here is an AEB after user pressed brake to cancel cruise. Only showed FCW while actuating, AEB UI after:
Signal2 is 4, Signal3 is 2, looks like it's related to AEB prepare, not AEB actuation? Won't be logged as AEB:
Here's one more unknown signal value for Signal2:
And finally, here is AEB actuation without any message (only FCW alert):
=> Subaru: add AEB actuation signal

generator/toyota/_toyota_2017.dbc, toyota_new_mc_pt_generated.dbc, toyota_nodsu_pt_generated.dbc, toyota_tnga_k_pt_generated.dbc
this was thought to be a 1 bit message, however after some testing, it's actually 3 bits. It displays two different messages, one is LDA unavail below 50k/h, the other one is LDA unavail below this speed.
=> Toyota: fix length and description of LDA messages

hyundai_kia_generic.dbc
Adds the readout for the Hyundai and Kia Idle Stop & Go system states
This has only been verified to be correct on the Kia Ceed 2019, but based on other values lining up correctly it is fairly certain this is applicable to other cars with this system.
=> Add ISG state to HK generic

can/parser_pyx.pyx, can/tests/test_packer_parser.py
resolve: https://github.com/commaai/opendbc/issues/869#issuecomment-1615219925
throw a runtime error if signal not exist:
`RuntimeError: could not find signal 'ACCEL_CMD1' in 'ACC_CONTROL', DBC b'toyota_new_mc_pt_generated'`
=> CANParser: check if signals exist

generator/toyota/toyota_nodsu_pt.dbc, toyota_nodsu_pt_generated.dbc
If TSS/LSS 2.5, this signal is always 1.0. If TSS 2.0, it's usually 3, but can be 0 with these exceptions:
- Highlander & Highlander Hybrid is 0 instead of 3 if TSS 2.0 (checked a few VINs for model years and cross referenced with TSS applicability chart)
- Lexus NX is also 0 if TSS 2.0 (LSS+ 3.0 is 2022 MY, have only seen 2021 MY)
- Alphard is also 0 (not US market car)
There's also one exception to the rule of all TSS 2.0 cars having this signal at either 0 or 3:
- RAV4 & RAV4 Hybrid 2022 (non-LTA, TSS 2.0) have the signal at 1. Interestingly, they also are the only cars we've seen use LKA_ACTIVE in the LTA signal, but still accept LKA.
=> Toyota: add comment for LTA signal

hyundai_kia_generic.dbc
found new signal. 
SG_ SpeedLim_Nav_General : 29|1@0+ (1,0) [0|1] "" XXX
SG_ SpeedLim_Nav_Cam : 30|1@0+ (1,0) [0|1] "" XXX
SpeedLim_Nav_Cam is 1 when the SpeedLim_Nav_Clu data is info about speed camera.
SpeedLim_Nav_General is 1 when the SpeedLim_Nav_Clu data is info about road, not speed camera.
route : 1edd7a8340016f2c|2023-07-06--17-44-12--0
=> HYUNDAI : update speed camera signal

can/tests/test_packer_parser.py
already calls the first argument with subsequent arguments
=> test parser: cleanup test

can/packer.cc
This might just be required on Ubuntu 22.04? (clang 14)
=> packer: import stdexcept

can/packer_pyx.pyx, requirements.txt
Cython 3.0.0 breaks opendbc, but now it wants to upgrade by default in the CI. Force to <3.0.0
=> CI: Fix panda CI by not upgrading Cython

can/common.h, can/common.pxd, can/packer.cc, can/packer_pyx.pyx, can/tests/test_packer_parser.py
This reverts commit 1c43e1cbd689c9d61121cdcea6c132c655697a14.
=> Revert "CANPacker: refactor to avoid undefined signals (#891)"

hyundai_santafe_2007.dbc, opel_omega_2001.dbc
Hyundai SantaFe 2007 2.7V6 4AT:
Now the signals have understandable names and all ones have been checked on my car.
Useless signals are removed at all.
Opel Omega B 2001 3.2V6 5MT:
New database for GM's Vectra B/Omega B with V6 engines.
=> Hyundai SantaFe CM and Opel Omega B databases added

generator/toyota/_toyota_2017.dbc, toyota_new_mc_pt_generated.dbc, toyota_nodsu_pt_generated.dbc, toyota_tnga_k_pt_generated.dbc
The naming of this message is confusing. On Toyotas, the MFD and HUD's behaviour for displaying ACC status is entirely controlled by `0x343`, and this ID is for controlling how the MFD and HUD handle PCS alerts.
Also fixed a few inconsistencies in the definition section.
=> Toyota: rename ACC_HUD to PCS_HUD

generator/toyota/_toyota_2017.dbc, toyota_new_mc_pt_generated.dbc, toyota_nodsu_pt_generated.dbc, toyota_tnga_k_pt_generated.dbc
- The signal defined in https://github.com/commaai/opendbc/pull/627 does not work for cars that use AEB message for longitudinal (i.e., `CAR.LEXUS_IS`, `CAR.LEXUS_RC`).
- Each press of the distance button cycles the signal from 1 to 2 to 3.
- Route ID: `fc2bfdcd52ca066f|2023-08-08--14-36-52`
=> Toyota: Follow distance signal for unsupported DSU cars

can/common.pxd, can/tests/test_dbc_exceptions.py
Right now, when `update_strings` is called with some corrupted/arbitrary bytes, cpp exception is thrown which crashes the process. With this, exception will be propagated as `RuntimeError`
=> parser: update_strings propagate cpp exceptions in py bindings

generator/subaru/subaru_global_2017.dbc, subaru_global_2017_generated.dbc
Subaru Global Transmission RPM signal had an unrelated bit that switches on at about 60kph
Before:
Transmission RPM vs Engine RPM
Transmission RPM vs Cruise RPM
After:
Transmission RPM vs Cruse RPM / Engine RPM
Route: `8de015561e1ea4a0|2023-08-12--13-09-08` (One Mile Challenge run 1, 0-184kph)
=> Subaru: Remove unrelated bit from transmission RPM signal

can/common.pxd, can/parser.cc, can/tests/test_packer_parser.py
runtime error if message is checked twice
resolves: https://github.com/commaai/opendbc/issues/914
=> Parser: disallow duplicate message checks

can/common_dbc.h
it's not used after https://github.com/commaai/opendbc/pull/602
=> common_dbc.h: remove ARRAYSIZE

can/packer.cc
sig.name is already a std::string after https://github.com/commaai/opendbc/pull/602
=> CanPacker: removing unnecessary string copying

can/common.pxd
From:
```python
...terminate called after throwing an instance of 'std::runtime_error'
what():  [chrysler_ram_hd_generated.dbc:121] Duplicate message name: CRUISE_BUTTONS
Aborted (core dumped)
```
to:
```python
======================================================================
ERROR: test_parse_all_dbcs (test_dbc_parser.TestDBCParser.test_parse_all_dbcs) (dbc='chrysler_ram_hd_generated')
Dynamic DBC parser checks:
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/batman/openpilot/opendbc/can/tests/test_dbc_parser.py", line 24, in test_parse_all_dbcs
CANParser(dbc, [], 0)
File "opendbc/can/parser_pyx.pyx", line 32, in opendbc.can.parser_pyx.CANParser.__init__
RuntimeError: [chrysler_ram_hd_generated.dbc:121] Duplicate …
```
=> CANParser: capture C++ DBC parser exceptions

gm_global_a_lowspeed.dbc
https://github.com/commaai/opendbc/assets/63013446/34f7537b-125b-4b43-85e7-7cacbce6df41
I added the bits for the blind spot monitoring light indicator, The message has some more info in it as well that I could not figure out exactly what it's for. Captured messages using a White panda hooked up to the aux port of my c3
=> Update gm_global_a_lowspeed.dbc to include BOLT EUV Blindspot indicator

can/common.h, can/parser.cc
Split from https://github.com/commaai/opendbc/pull/971, makes reading the parser.cc file much eaiser.
Probably called sec because we originally passed in `sec_since_boot() * 1e9` in the first CANParser commit:
=> CANParser: rename timestamp variables

can/parser.cc, can/tests/test_packer_parser.py
Previously, if the COUNTER and CHECKSUM signals were at the end of the message in the DBC, we could freely update `vl` and `vl_all` all we want (regardless of if those two signals were valid or not). If the two were at the beginning of the message, it would not update any values which makes more sense and matches panda's behavior of processing each message as they come in, with validity checks.
However another issue was that if CHECKSUM was before COUNTER and the checksum was invalid it would never actually update the last message counter, causing more mismatches when we later got valid checksums.
Both cases now match panda behavior, avoiding mismatches found in https://github.com/commaai/openpilot/pull/30443
Todo:
=> CANParser: process all signals before updating values

generator/honda/honda_civic_touring_2016_can.dbc, honda_civic_touring_2016_can_generated.dbc
fix cabana parsing error.
remove the CM_SG_ 450, there is already a value description for 4550 EPB_STATE:
> VAL_ 450 EPB_STATE 3 "engaged" 2 "disengaging" 1 "engaging" 0 "disengaged" ;
=>  honda_civic_touring_2016_can_generated.dbc: remove   `CM_ SG_ 450`

can/packer_pyx.pyx, can/parser_pyx.pyx
test_car_interfaces with 300 examples:
```
system base: 66.1G
no dealloc: 92.8G
packer dealloc: 75.5G
packer + parser dealloc: 71.9G
```
=> CAN packer/parser: clean up after alloc

hyundai_canfd.dbc
Properly defines the signal for the relative speed to the tracked lead car. This has been confirmed on camera-based SCC CAN-FD platforms.
Segment ID in screenshot: `5a681a11ff756d93|2023-11-18--10-35-23--0`
=> Hyundai CAN-FD: Lead Relative Speed

.github/workflows/repo.yml, .github/workflows/tests.yml
Switch to the v4 checkout instead of v3 as that is now deprecated and gives a warning in the job status on github.
https://github.com/marketplace/actions/checkout
=> Update from deprecated github action

vw_mqb_2010.dbc
Add support for HCA preemption to the `LH_EPS_03.EPS_HCA_Status` value enum.
=> VW MQB: Support for preempted HCA state

can/parser_pyx.pyx
Issue: The following two code blocks consume nearly two-thirds of cython's update_string()'s runtime:
```
for v in self.vl_all.values():
for l in v.values():  # no-cython-lint
l.clear()
```
```
while it != new_vals.end():
cv = &deref(it)
cv_name = <unicode>cv.name
self.vl[cv.address][cv_name] = cv.value
self.vl_all[cv.address][cv_name] = cv.all_values
self.ts_nanos[cv.address][cv_name] = cv.ts_nanos
updated_addrs.insert(cv.address)
preinc(it)
```
Resolve:
1. Clear only the address key's value instead of all key-value pairs, as the name key's value refers to the address. This change halves the execution time of the first block of code.
2. Since the vector return from CanParser::update_strings() groups data by address, caching dictionary references for each address key reduces redundant …
=> CANParser: 2x faster parsing

vw_mqb_2010.dbc
Updates to `TSK_06` and `TSK_07`, new message `TSK_08`, with VAL enums.
Holding in Draft while we figure out how to detect switchable CC/ACC modes on the cars that support it. It's unclear how we'll detect that yet, and if it's in `TSK_07` or `TSK_08` I'll need to add checksum support code.
=> VW MQB: Additional TSK support

.pre-commit-config.yaml, can/common.h, can/logger.h, can/parser.cc
1. Eliminate the dependency on cereal/logger.h and use own logger.h instead.
2. Support cloudlog_rl in logger.h, resolve https://github.com/commaai/opendbc/issues/1003
=> improve logging

can/packer.cc, can/tests/test_packer_parser.py
Fix multiple counters assignments when `COUNTER` is not the last signal. 
For example, `counters[address] `could be incorrectly set to the 'SIGNED' value (1) in make_can_msg():
```
msg = packer.make_can_msg("CAN_FD_MESSAGE", 0, {
"COUNTER": 10,
"SIGNED" : 1,
})
```
=> CANPacker: fix incorrect  `counters` assignment

can/tests/test_packer_parser.py
https://github.com/commaai/opendbc/pull/942 would now throw an uncaught [out_of_range C++ exception](https://cplusplus.com/reference/map/map/at/) for the packer when given unexpected message names
We probably do want to throw an exception (or at least log it), but we need really good discovery tests to catch anything before it becomes an exception in a user's car
=> assert expected openpilot undefined message behavior

can/packer.cc
split from https://github.com/commaai/opendbc/pull/942
from
```
cp.make_can_msg('test', 0, {'hi': 2})
undefined signal hi - 0
Out[3]: [0, 0, b'', 0]
cp.make_can_msg(999, 0, {'hi': 2})
undefined signal hi - 999
Out[4]: [999, 0, b'', 0]
```
to
```
cp.make_can_msg('test', 0, {'hi': 2})
opendbc/can/packer.cc: undefined address - 0
Out[3]: [0, 0, b'', 0]
cp.make_can_msg(999, 0, {'hi': 2})
opendbc/can/packer.cc: undefined address - 999
Out[4]: [999, 0, b'', 0]
```
=> packer: log undefined address/signal as error

can/common.h, can/common.pxd, can/common_dbc.h, can/dbc.cc, can/packer.cc, can/packer_pyx.pyx, can/parser.cc, can/parser_pyx.pyx
Both the Cython and C++ code currently build their own message lookup tables independently each time they are run. This redundancy leads to code duplication and decreased initialization performance. To improve efficiency, it would be better to create the message lookup table once and share it among all instances.
this pr builds the message lookup table once in DBC, it can simplify the cython code, and improve the runtime performace.
~For ease of review. This PR only refactored the packer related code. The parser related is put in the next PR. https://github.com/commaai/opendbc/pull/943~ already implemented in this PR.
this pr may also resolve: https://github.com/commaai/opendbc/issues/500, https://github.com/commaai/opendbc/issues/902
=> build message lookup table in DBC

can/common.cc, can/common.h, can/packer.cc, can/parser.cc
This PR introduces a static initializer to set up CRC lookup tables directly at module load time, ensuring thread-safe initialization and preventing race conditions.
Benefits
1. Ensures thread-safe initialization.
2. Eliminates the need for explicit initialization calls.
3. Prevents multiple initializations and race conditions.
=> Initializes CRC lookup tables at module initialization

can/SConscript
prereq for: https://github.com/commaai/openpilot/pull/32909
Good reference: http://clarkkromenaker.com/post/library-dynamic-loading-mac/#:~:text=On%20Mac%20and%20Linux%2C%20the,path%20embedded%20inside%20the%20executable.
MacOS linking to dynamic library on scons is very weird, and RPATH is not well supported on macOS.
reference:
Similar trouble I encounter: https://github.com/SCons/scons/issues/3128
Weird behaviour on macOS for rpath: https://github.com/SCons/scons/issues/2127
Edit:
Uses `@loader_path` instead, for relative path to the file referencing the dynamic lib
=> Sconscript: enable openpilot compilation for macOS

.github/workflows/tests.yml, can/tests/test_checksums.py, can/tests/test_dbc_exceptions.py, can/tests/test_dbc_parser.py, can/tests/test_define.py, can/tests/test_packer_parser.py, can/tests/test_parser_performance.py, requirements.txt
Part of https://github.com/commaai/openpilot/issues/32941
=> Convert tests to pytests

can/parser.cc
added here: https://github.com/commaai/opendbc/commit/87af8c4ac192e263bdd4e832d71bb10f480172ec
it's the same thing
After https://github.com/commaai/opendbc/pull/934 we can clean a bunch more up here
=> parser: declutter nanos usage

opendbc/car/gm/carcontroller.py, opendbc/car/structs.py
We can't add fields without them being in cereal or openpilot CI will fail on the conversion. We will want to split this co-dependence in the future.
Reverts commaai/opendbc#1185
=> Revert "GM: implement allow throttle/brakes"

examples/joystick.py, examples/kbhit.py, opendbc/car/panda_runner.py, pyproject.toml
=> simple joystick example

.gitignore, examples/longitudinal-profiles.py, opendbc/car/panda_runner.py, pyproject.toml
```
SKIP_FW_QUERY=1 FINGERPRINT="TOYOTA_COROLLA_TSS2" ./longitudinal-profiles.py
```
=> longitudinal profile runner

opendbc/dbc/generator/toyota/_toyota_2017.dbc, opendbc/dbc/toyota_new_mc_pt_generated.dbc, opendbc/dbc/toyota_nodsu_pt_generated.dbc, opendbc/dbc/toyota_tnga_k_pt_generated.dbc
Ported over a bunch of messages from `toyota_2017_ref_pt.dbc` that had large diffs comparing ACC and no ACC routes on our Lexus.
=> Toyota: more ACC-related definitions

opendbc/car/honda/carcontroller.py, opendbc/car/honda/values.py, opendbc/car/subaru/values.py, opendbc/car/tests/test_lateral_limits.py
Split from https://github.com/commaai/opendbc/pull/1231
=> Test all torque cars' lateral limits

opendbc/dbc/vw_mqb_2010.dbc
Updates, fixes, and additions in support of #1235. The additional signals aren't used by openpilot, but are used by the car, and must be replicated by the CAN packer to recreate the car's messages for CI testing.
=> VW MQB: Various message and signal updates

opendbc/dbc/generator/toyota/_toyota_2017.dbc, opendbc/dbc/toyota_new_mc_pt_generated.dbc, opendbc/dbc/toyota_nodsu_pt_generated.dbc, opendbc/dbc/toyota_tnga_k_pt_generated.dbc
Contains signals that describe how much force is being applied for positive acceleration.
I think `FDRVREAL` is the more accurate version, as that includes these RPM drops from down shifting, and it also exhibits delayed response in some cases. Perhaps `FDRV` is more of a request or ideal value.
Lexus ES route: 57048cfce01d9625/000000f5--a32b2b7add
Here is each divided by CP.mass to get an acceleration (+ pitch compensated):
=> Toyota: add ENG2F41

opendbc/dbc/generator/toyota/_toyota_2017.dbc, opendbc/dbc/toyota_new_mc_pt_generated.dbc, opendbc/dbc/toyota_nodsu_pt_generated.dbc, opendbc/dbc/toyota_tnga_k_pt_generated.dbc
Same as drive force (https://github.com/commaai/opendbc/pull/1246) but only for friction brakes. Now to find for Lexus!
You can see it mostly matches `PCM_CRUISE->ACCEL_NET` using the mass we have in CarParams, but in some cases it shows `ACCEL_NET` doesn't always capture every brake usage (it *did* brake here):
08e4c2a99df165b1/0000027e--b51d0c81a8/31:36
=> Toyota: add brake force signal for hybrids

opendbc/can/tests/test_checksums.py
Prepare for additional car ports to have explicit CRC/checksum test coverage.
* abstract VW test code to allow usage by any car port
* unused argument cleanup, type fixes
* vw -> volkswagen for consistency
* PEP8 function naming
=> test_checksums refactor

opendbc/can/common.cc, opendbc/can/common.h, opendbc/can/common.pxd, opendbc/can/common_dbc.h, opendbc/can/dbc.cc, opendbc/can/tests/test_checksums.py, opendbc/dbc/fca_giorgio.dbc
* Checkpoint / initial DBC, working and driving on Alfa Romeo Stelvio and Giulia
* CHECKSUM and COUNTER support, with test coverage
Brand port to follow.
=> FCA Giorgio: CAN database

opendbc/car/toyota/carcontroller.py, opendbc/car/toyota/carstate.py
Only for positive accel (given pitch). Now doesn't apply too much gas going down hills, or too little going up them.
Lexus ES TSS2 routes:
This branch:
Downhill with PCM + pitch compensation: https://connect.comma.ai/57048cfce01d9625/00000123--c1523da2eb
Uphill with PCM + pitch compensation: https://connect.comma.ai/57048cfce01d9625/00000124--db7c9676fb
Current master:
Downhill with PCM compensation: https://connect.comma.ai/57048cfce01d9625/00000125--1231d30430
Uphill with PCM compensation: https://connect.comma.ai/57048cfce01d9625/00000126--47613d0ae6
=> Toyota: pitch compensate new long tune

opendbc/car/toyota/interface.py
Lexus ES route on this branch: https://connect.comma.ai/57048cfce01d9625/00000130--7556579cf1
Less start from stop windup:
This branch is on the right.
Much less windup and request overshoot in creep tests:
---
Report: [LEXUS_ES_TSS2_57048cfce01d9625_00000130--7556579cf1.zip](https://github.com/user-attachments/files/17081341/LEXUS_ES_TSS2_57048cfce01d9625_00000130--7556579cf1.zip)
=> Toyota: lower long integral for new tune

opendbc/car/toyota/carcontroller.py
Would cause unwanted windup and acceleration when exiting standstill via resume button
=> Toyota PCM compensation: don't compensate in standstill

opendbc/car/toyota/carcontroller.py, opendbc/car/toyota/carstate.py
Re-open of https://github.com/commaai/opendbc/pull/1253. Compensates using PCM negative acceleration (brake) request (not actual applied value). This means while we can't attempt to undo any lag/jerk limits in the PCM (which doesn't seem possible anyway), we can still undo the internal PCM windup when requesting brake.
---
---
Lexus ES master: 57048cfce01d9625/00000130--7556579cf1
Lexus ES w/ this branch: 57048cfce01d9625/00000136--215ea510b2
=> Lexus ES TSS2: reduce braking overshoot

opendbc/car/toyota/carcontroller.py
The biggest innacuracy was coming to a final stop, we were not braking enough; probably due to lack of integral on compensation:
https://connect.comma.ai/57048cfce01d9625/00000137--ab0a0ba374
=> Toyota: don't apply PCM compensation in the stopping state

opendbc/car/toyota/carcontroller.py
If you switch from a high negative aceleration request to a positive one, sometimes the gas has to "unwind" from the negative acceleration value. Which doesn't make sense, but is what happens.
If you rate limit your request or send zero for one frame, then it is fine and the gas starts from 0 immediately.
=> Lexus: prevent lagged gas after heavy braking

opendbc/car/toyota/carcontroller.py
Reverts commaai/opendbc#1266. That PR only marginally improves the unwind of brakes, need to merge https://github.com/commaai/opendbc/pull/1265 and re-evaluate the rate limit
=> Revert "Lexus: prevent lagged gas after heavy braking"

opendbc/car/volkswagen/values.py
Temporarily revoking official support for the 2024 Volkswagen Jetta. CARS.md will be regenerated when openpilot bumps opendbc. The process for doing that is in flux.
**Background**
We added support for the 2024 Volkswagen Jetta in commaai/openpilot#30979. It was valid at the time, but it turns out MY2024 Jetta has an annoying  mid-year production split.
Cars produced starting February 19 switched to a new gateway. It's still ostensibly in the 3Q0 family, but uses the new MQBevo style connector, for which we don't have a harness.
We can re-add all MY 2024 Jetta when commaai/openpilot#33380 is available and we start converting most VW default installs back to using a camera harness.
**Split:**
**Early MY 2024 gateway**
**Late MY 2024 gateway**
=> VW MQB: Temporarily remove 2024 Volkswagen Jetta

opendbc/car/toyota/carcontroller.py
Try 2 of https://github.com/commaai/opendbc/pull/1266. Applies to all of Toyota, but only tested on Lexus. This is a safe change regardless.
When `CLUTCH->ACCEL_NET` is positive, it describes the acceleration the engine is actually applying. When you go from a negative to a positive acceleration request with a high delta, this `CLUTCH` signal sometimes unwinds from the negative request, even though it has no meaning under 0 m/s^2. You essentially are doing nothing for this time causing a delayed gas response. Here is a screenshot explaining this visually:
Route: 57048cfce01d9625/0000018e--0c9e84091e
<details><summary>View image</summary>
</details>
This does not seem to affect start from stop events, in the maneuver test at least.
---
Here is what it looks like when you rate limit your …
=> Toyota: prevent lagged gas after heavy braking

opendbc/car/hyundai/carstate.py
**Prerequisite of**
- https://github.com/commaai/opendbc/pull/1131
**Related**
- https://github.com/commaai/openpilot/pull/33647
=> Hyundai CAN-FD: Use `ACCELERATOR` for EV gear shifter positions

opendbc/car/hyundai/interface.py
Remove no-op code: set flags if in relevant group, but only in that group because the flags are already set.
Offline validation:
* `pytest opendbc` passes
* `pytest selfdrive/car/tests` passes
* `selfdrive/test/process_replay/test_processes.py` just in case I'm blind, no change to carParams
=> HKG: Cleanup EV and HYBRID flag setting

opendbc/car/hyundai/interface.py
Refactored for clarity, in preparation for merging additional car support. Null effect change.
Offline validation:
* `pytest opendbc` passes
* `pytest selfdrive/car/tests` passes
* `selfdrive/test/process_replay/test_processes.py`, no changes to carParams or anything else
=> HKG: Interface refactor

opendbc/car/hyundai/interface.py, opendbc/car/hyundai/tests/test_hyundai.py, opendbc/car/hyundai/values.py
Set the alternate lateral limits flag at the platform config level, and get rid of the separately maintained list of cars.
=> HKG: Refactor alternate lateral limits

opendbc/car/hyundai/fingerprints.py, opendbc/car/hyundai/values.py
Add firmware versions for the Genesis GV60 (Performance Trim) 2022. Expand supported model-year range down to 2022.
**Route ID**
- Stock longitudinal: `b26e6868ffe5ea08/00000000--946587db7a`
- openpilot longitudinal: `b26e6868ffe5ea08/0000000a--64b0ced90d`
Thanks to the community 2022 Genesis GV60 (Performance Trim) bigal_00666 (Discord).
=> HKG: Add FW version and update model year for Genesis GV60 2022

opendbc/car/toyota/carcontroller.py, opendbc/car/toyota/toyotacan.py
Before PCM accel compensation, we couldn't ship 2 m/s^2 because of the overshooting, but that's fixed with PCM compensation. A similar overshooting problem with `PERMIT_BRAKING` occurs, but our compensation should counteract that now.
We just need to be careful about not braking when we really should, but we do pitch compensation now so that should be fine as well. The stock system uses this bit often when accelerating, so it's not some unused API.
---
Start from stop shows almost instant acceleration from a stop, which is also clearly visible in the speed plot as being more linear:
`come to stop` maneuver is the same.
`start from stop` maneuver is greatly improved:
Creep test is also a bit better:
brake step response also looks the same, as does gas step response at high speed.
---
Full …
=> Lexus ES TSS2: improve start from stop response time

opendbc/car/volkswagen/values.py
Supported year range was improperly formatted. This was missed by tests in the past, because we don't currently generate CarDocs for cars in dashcam mode, but was exposed by #1286.
=> VW PQ: Fix CarDocs year range for Jetta

opendbc/car/nissan/carcontroller.py, opendbc/car/nissan/nissancan.py, opendbc/car/nissan/values.py
continue from https://github.com/commaai/openpilot/pull/33020
=> Nissan/carcontroller: add max steering angle safeguard for nissan

opendbc/car/__init__.py, opendbc/car/chrysler/carstate.py, opendbc/car/ford/carstate.py, opendbc/car/gm/carstate.py, opendbc/car/honda/carstate.py, opendbc/car/hyundai/carstate.py, opendbc/car/interfaces.py, opendbc/car/mazda/carstate.py, opendbc/car/nissan/carstate.py, opendbc/car/toyota/carstate.py
**Description**
- Introduce `ButtonTracker` class to encapsulate button state tracking and button event creation
- Move `create_button_events` function into `ButtonTracker` class
- Simplify car state updates by reducing button event handling to a single line
=> Car Interfaces: Refactor button state tracking with `ButtonTracker`

opendbc/car/hyundai/carstate.py
Split from https://github.com/commaai/opendbc/pull/1318
It's fine to publish all the time, as it was originally adding enable events in the same code block: https://github.com/commaai/openpilot/pull/24678
=> Hyundai: always publish cruise and main buttons

opendbc/car/hyundai/hyundaican.py
**Description**
`hda_set_speed` has not been used since the first Hyundai was supported. The other values are not required for opnepilot lateral and longitudinal control.
**Offline Validation**
=> Hyundai: Cleanup unused parameter in `create_lfahda_mfc`

opendbc/dbc/generator/toyota/toyota_rav4_prime.dbc, opendbc/dbc/toyota_rav4_prime_generated.dbc
Long control is out of scope for initial RAV4 Prime support in #1287, but in the course of validation, we identified the new ACC control message.
Much like STEERING_LTA now has a SecOC-signed companion STEERING_LTA_2 with mostly just the actuation commands moved, ACC_CONTROL now has a SecOC-signed companion ACC_CONTROL_2 with just the acceleration value moved.
The message comes in from the bus 2 side, just like ACC_CONTROL, and the SecOC solve should be generally applicable. Long control is almost certainly possible with a few hours spent on control and Panda safety.
=> Toyota: DBC message for SecOC longitudinal control

opendbc/car/toyota/values.py
Weight and wheelbase specifications obtained from https://web.archive.org/web/20221005134205/https://www.toyota.com/rav4prime/2022/features/mpg_other_price/4544/4550. Steering ratio obtained from https://www.toyota.com/content/dam/toyota/brochures/pdf/2022/rav4_ebrochure.pdf.
=> Toyota: Fix RAV4 Prime mass and wheelbase

opendbc/car/ford/carcontroller.py
The two signals for Ford `LateralMotionControl` (CAN) and `LateralMotionControl2` both  accept four individual signals for steering actuation. Currently, only the curvature value is supplied.
This is simply to bring transparency to the remaining three signals and why they're zeroed out.
=> Ford: Provide detail for zeroed out signals on LateralMotionControl and LateralMotionControl2 signals

opendbc/car/tesla/carcontroller.py
The Autopilot computer sends the `ACC_ON` state to the Drive Interface (DI). The DI then manages the actual ACC state.
`ACC_ON` simply indicates that ACC is ready to engage, but not yet active. 
In the example from the stock route `35f334fe58c5cdc5/00000001--d8d176b1af`, the `ACC_ON` state is active even though the DI_cruiseState is not set to "ENABLED". It's the action of pressing "Resume" on the stalk that actually activates ACC.
With this change, we no longer have to adhere to the Autopilot computer's restrictions to enable ACC.
=> Tesla: don't copy DAS_accState

opendbc/car/tesla/carcontroller.py, opendbc/car/tesla/teslacan.py
Setting the speed to anything other than 0 when we are not engaged puts the Driver Interface (DI_cruiseState) in the UNAVAILABLE state. This stops us from engaging while the car is at a standstill.
=> Tesla: setSpeed to 0 if not active

opendbc/car/tesla/carcontroller.py, opendbc/car/tesla/carstate.py
- hands_on_level is valid, we dont need the steering_warning
- If `EPAS3S_sysStatus` it shows `EAC_INHIBITED`, it's a temporary fault, so we don't need complex combination of `EPAS3S_eacErrorCode` and `EPAS3S_eacStatus`.
=> Tesla: simplify the logic for handling steering-related status codes

opendbc/car/tesla/carcontroller.py, opendbc/car/tesla/teslacan.py
The APS_eacMonitor message, sent by the Autopilot computer, tells the EPAS if steering commands are allowed. 
Setting APS_eacAllow to 1 always lets us engage steering.
=> Tesla: allow Steering below 18mph

opendbc/car/ford/interface.py, opendbc/car/ford/radar_interface.py
For https://github.com/commaai/opendbc/pull/1363
Verified with this code in the `test_radar_interface` test_models function:
```
if self.CP.flags & 1:  # CAN FD
assert abs(msgs - 1200) < 50  # 20 Hz
else:
assert abs(msgs - 2000) < 50  # 33.3 Hz
```
=> Set Ford CAN radar timestep

opendbc/car/ford/radar_interface.py
Split from https://github.com/commaai/opendbc/pull/1408
- Each track message's `CAN_SCAN_INDEX_2LSB_xx` signal matches the header's when triggered on the header message
- Every cycle we now receive exactly 65 track updates when triggered on the header message
=> Ford: trigger radar update on header message

opendbc/car/ford/carcontroller.py
See the undershoot of accel when coming to a final stop: https://commaai.github.io/opendbc-data/longitudinal_reports/FORD_BRONCO_SPORT_MK1_b9d015f8ff659e1e_0000043a--98baf2b862.html
---
Report on this branch: https://commaai.github.io/opendbc-data/longitudinal_reports/FORD_BRONCO_SPORT_MK1_b9d015f8ff659e1e_00000494--6f8f5b9bd5.html
=> Ford Bronco: compensate for creeping when stopping

opendbc/car/ford/interface.py
Each point is effectively ~8 Hz, so some delay is useful
=> Ford: set radar delay

opendbc/car/__init__.py, opendbc/car/ford/carcontroller.py, opendbc/car/ford/fordcan.py, opendbc/car/toyota/carcontroller.py
Left is this PR, right is master.
Uphill requesting -0.2 m/s^2:
---
Downhill requesting 0.2 m/s^2 (I applied a moving average over 1s to aEgo since it is too noisy to see the trend). PCM's pitch compensation isn't great, but it's better than not being able to brake properly at various pitches:
=> Ford: compensate pitch for brake actuation bit

opendbc/car/ford/interface.py
Restores similar closed loop control from before https://github.com/commaai/openpilot/pull/32706
Ford's ABS and PCM seem to have pitch compensation (or at the very least try to close the loop using the ego speed/accel), but it's very slow, this PR should mitigate that.
---
Here shows the ABS braking down a hill and then the PCM slowly applying gas when it goes up the next hill, all with small acceleration requests from the planner:
https://connect.comma.ai/b9d015f8ff659e1e/000004c5--5e22b30690/436/468
=> Ford: add long tuning back

opendbc/car/ford/interface.py, opendbc/car/ford/radar_interface.py
track ID goes from 100k to 30k for `./regen.py 'b9d015f8ff659e1e/000004b6--2657291be4' 7 --whitelist-procs card`, saves 1-2% CPU
- fixes creating capnp radar point object only to delete it if it's not valid (this is the big CPU savings contributor)
- if newly valid point, fixes comparing it with empty radar point, double incrementing its track id
=> Ford: fix unnecessary radar point creation and deletion

opendbc/car/ford/interface.py
FYI, CAN parsing and accessing the messages and signals from the CANParser dicts is mostly the slowest part, clustering takes only ~10-20% of the time.
@deanlee I see you have some optimization PRs, do they make a significant difference? Please post time differences using the [debug script](https://github.com/commaai/openpilot/blob/master/selfdrive/debug/check_can_parser_performance.py) if you haven't and I'll check it out soon!
=> Ford: enable radar

opendbc/car/ford/interface.py
Looks like the diff between PCM set speed and vEgo can be as high as 0.6 m/s, going to choose 0.4 m/s as the final breakpoint as a good middle ground:
---
Before/after:
=> Ford: limit acceleration near PCM set speed

opendbc/can/parser_pyx.pyx
This PR adds filtering for CAN messages  based on the bus and addresses that the CANParser specifically cares about.
Instead of converting and copying all incoming messages from Python to C++ , we now only parse and copy those with relevant addresses to the c++ `CanFrame` vector. This reduces the overhead from unnecessary message processing, lowering CPU and memory usage while enhancing overall performance and efficiency.
Below are the performance benchmark results comparing this PR against the current master branch:
**Benchmark (PR):**
```
6000 CAN packets, 10 runs
190.79 mean ms, 219.88 max ms, 180.86 min ms, 10.96 std ms
0.0318 mean ms / CAN packet
```
**Benchmark (Master):**
```
6000 CAN packets, 10 runs
335.81 mean ms, 394.27 max ms, 312.58 min ms, 24.96 std ms
0.0560 mean ms / CAN …
```
=> CANParser: filter CAN messages by bus and addresses

opendbc/can/common.h, opendbc/can/common.pxd, opendbc/can/common_dbc.h, opendbc/can/parser.cc, opendbc/can/parser_pyx.pyx
This PR greatly simplifies the update logic, resulting in reduced code complexity and eliminating unnecessary data copying.
1. Removal of `SignalValue` Struct and `CANParser::query_latest` Function: These components, previously used for copying updated values to Cython, have been removed. This change streamlines the data flow between C++ and Cython.
2. Direct Exposure of `MessageState` to Cython: `MessageState` is now directly accessible from Cython, allowing values to be read straight from the C++ object. This eliminates the need for intermediate copying, optimizing performance and simplifying the overall code structure.
Additionally, this PR includes changes from #1381, where value dictionaries are now initialized directly from DBC messages, though it does not include the …
=> CANParser: expose `MessageState` to Cython to eliminate data copying

opendbc/can/parser_pyx.pyx
Fixes a process replay diff introduced in https://github.com/commaai/opendbc/pull/1383. The bus timeout detection should still receive all messages to determine if the entire bus has dropped out.
https://github.com/commaai/openpilot/actions/runs/11640003241/job/32416858994?pr=33919
=> CANParser: only filter bus

opendbc/car/tesla/carstate.py
The latest version of autopilot changes the meaning of most of the values for `DI_vehicleHoldState`.  Switching to `DI_cruiseState` should reduce our exposure to changes like this by decreasing the number of signals used.
I don't like using a constant speed threshold because we used to do that and I have seen it bounce in and out of the standstill state quickly/repeatedly causing the wheel to jerk back and forth rapidly.  I suppose we could address this with a hysteresis when entering the standstill state, but the signal I am changing it to seems to do that for us.
=> tesla: fix standstill

opendbc/car/toyota/carstate.py
Useful when working on porting this to other cars and having a list of cars that don't have this message
=> Toyota: set pcm_accel_net when possible

opendbc/car/toyota/carcontroller.py
Reverts commaai/opendbc#1461
Need to get the aEgo delay thing figured out for high jerk scenarios, but on the right track. Reverting until it works in all cases
=> Revert "Toyota: learn offset for PCM acceleration request"

opendbc/car/toyota/carcontroller.py
- Fixes case where PCM can be stuck applying brakes while we request 1.5 m/s^2 (e.g. Corolla) after coming to a quick stop
- Improves gas responsiveness in start from stop situations, PCM's acceleration request is closer to our request
Looks like there's almost no difference in the report for start from stop in regards to overshooting/reaching target:
master report: https://commaai.github.io/opendbc-data/longitudinal_reports/TOYOTA_CAMRY_TSS2_6483a59cd49b6650_00000068--f3684c0b08.html
this PR report: https://commaai.github.io/opendbc-data/longitudinal_reports/TOYOTA_CAMRY_TSS2_6483a59cd49b6650_00000062--f6537659bd.html
However in actual driving, this leads to clear improvements for start from stop, perhaps the step change elicits a different response than a ramp:
Camry Hybrid:
- uphill …
=> Toyota: more responsive start from stop

opendbc/car/toyota/carcontroller.py, opendbc/car/toyota/carstate.py
We mainly want to reduce the high frequency oscillations and feedback from the PCM signals, not restrict the rate. This should do that. Split from https://github.com/commaai/opendbc/pull/1475
=> Toyota: use a filter for PCM compensation

opendbc/car/toyota/carcontroller.py
To be clear, I am measuring the `PCM_CRUISE->ACCEL_NET` brake accel readback signal. I've observed down rates when requesting -3.5 m/s^2 of anywhere from -3.5 m/s^3  to -4.8 m/s^3 across Corolla, Lexus, Camry Hybrid, but the Camry Hybrid (and most other hybrids) is the only one able to actually achieve that jerk (seen -4.5 m/s^3). The other two ICE cars are 2x to 4x slower.
So limiting to -4 m/s^3 doesn't degrade performance that much in terms of realized jerk and allows us to better control for brake overshoot when we merge aEgo error correction.
Follow up to https://github.com/commaai/opendbc/pull/1481
=> Toyota: lower accel down rate limit

opendbc/car/toyota/carcontroller.py
fixes some overshoot due to the [down rate limit](https://github.com/commaai/opendbc/pull/1481) we merged recently
=> Toyota: PERMIT_BRAKING shouldn't use rate limited decel

opendbc/car/hyundai/carstate.py
This reverts commit 68d93be9598d7993b8146d7d398b3fa9dbf20f20.
Fixes unable to engage with stock ACC, but now prevents enabling with the pause/resume button
=> Reapply "Hyundai: always publish cruise and main buttons" (#1486)

opendbc/car/toyota/carcontroller.py
Here the Corolla hit a bump which caused the localizer pitch to oscillate rapidly, we should filter the signal a bit to prevent overreaction: https://connect.comma.ai/a2bddce0b6747e10/000003fa--6edfaa70be/900/960
Slower pitch updates also allows the aEgo error-corrector to compensate for incorrect pitch faster
middle is old vs. new actuators output accel on https://github.com/commaai/opendbc/pull/1499, bottom is pitch
=> Toyota: filter pitch for new tune

opendbc/car/toyota/carstate.py
here's a come to stop scenario where Corolla released brakes too much due to bad creep accel logic:
green: previous actuators output
orange: new actuators output
=> Toyota: don't release brakes coming to a stop w/ new tune

opendbc/car/toyota/carcontroller.py
Compensates for overshoot during high jerk maneuvers better, since there will always be some delay to the PCM ACCEL_NET.
To be clear, this has little effect on the Lexus ES since its jerk limit is so low, it doesn't overshoot that much, but it does fix other cars like the Corolla with 2x higher jerk and most likely the Camry Hybrid with 4x higher jerk.
Split from https://github.com/commaai/opendbc/pull/1513
=> Toyota: prevent overshoot w/ new tune

opendbc/car/toyota/carcontroller.py
Split from https://github.com/commaai/opendbc/pull/1513. Useful to avoid persistent errors which is more common on the Corolla.
Comparing a new long report on the Lexus ES vs. the one in https://github.com/commaai/opendbc/pull/1515:
come to stop is the same
start from stop is the same
creep is the same
=> Toyota: use a PID for PCM compensation

opendbc/car/car.capnp, opendbc/car/toyota/carcontroller.py, opendbc/car/toyota/interface.py
Before: https://commaai.github.io/opendbc-data/longitudinal_reports/TOYOTA_COROLLA_TSS2_a2bddce0b6747e10_000003a9--cbb0f4bdcc.html
After: https://commaai.github.io/opendbc-data/longitudinal_reports/TOYOTA_COROLLA_TSS2_a2bddce0b6747e10_000004fe--1b980939f0.html
There's less overshoot across all maneuvers without sacrificing response time:
start from stop is quicker with no overshoot:
---
creep shows no gas overshoot, with minor brake overshoot (though previously we overshot from -1 m/s^2 to -2.5 m/s^2, so this is a massive improvement):
---
brake step responses show less overshoot:
---
gas step responses also show less overshoot:
though it didn't reach target on the +2 m/s^2 maneuvers strangely, but we were requesting the max:
=> Corolla TSS2: support new Toyota tune

opendbc/car/toyota/carcontroller.py, opendbc/car/toyota/carstate.py, opendbc/car/toyota/interface.py
Split from https://github.com/commaai/opendbc/pull/1522, enabled by https://github.com/commaai/opendbc/pull/1532
Removes the overshoot of aEgo near a stop due to kalman filter and high speed threshold wheel speed sensors. Has tiny impact on control now, but enables us to trust aEgo more in the future.
livePose.accelerationDevice.x would be more ideal as it can measure acceleration far earlier than this signal
=> Toyota: improve ego acceleration near stop

opendbc/car/toyota/carcontroller.py, opendbc/car/toyota/interface.py
Split from https://github.com/commaai/opendbc/pull/1522
This just mainly reduces integral windup during high jerk maneuvers.
You can see the braking overshoot decreases from ~-2.8 m/s^2 to ~-1.7 m/s^2 for a target of -1 m/s^2
(this is with ki=0.25 so that derivative can fully compensate, but ki will be left at 0.5 to start in this PR)
`a2bddce0b6747e10/000005be--78a61e8ab6`
=> Toyota TSS2: add longitudinal derivative

.github/workflows/tests.yml, .pre-commit-config.yaml, opendbc/can/logger.h
It's our one non-Python dependency, and it hasn't caught much. If we're missing it, we can add it back.
=> remove cppcheck

opendbc/car/toyota/carcontroller.py
Allows more time for brakes to unwind before we command accel, right now brake release is very abrupt on my hybrid Camry
=> Toyota: new longitudinal tune improvements

opendbc/car/hyundai/fingerprints.py
Adds fingerprints from a 2024 Hyundai Ioniq 6 Limited.
Route: e427c77ff2e36741/00000000--eeded7fe50
=> Hyundai: Add latest 2024 Ioniq 6 fingerprints

opendbc/car/toyota/interface.py
Using the future estimated aEgo, we can now effectively prevent overshoot before it happens. This is with ki of 0.5 (0.25 in master), but the effect is similar.
=> Toyota: raise max acceleration for TSS2

opendbc/car/hyundai/carcontroller.py, opendbc/car/hyundai/carstate.py, opendbc/car/hyundai/hyundaican.py, opendbc/car/hyundai/interface.py
**Description**
- This PR re-implements changes from a previous PR: https://github.com/commaai/opendbc/pull/1518
- Addressed a bug where non-camera SCC cars were incorrectly parsing `SCC11`/`SCC12` on bus 2. This fix is detailed in the commit: https://github.com/commaai/opendbc/pull/1563/commits/855e4317ad1369d9cfa29b27cc17242522c7a727
- The last PR failed `test_models` in the `openpilot` project due to a missing merge of the related panda PR into `openpilot/master`, as well as the bug introduced mentioned above. More context: https://github.com/commaai/opendbc/pull/1282#issuecomment-2492842630
**Validation**
- With the latest changes, `openpilot` has successfully passed `test_models` as verified in the following action run in the `openpilot` PR: …
=> Hyundai CAN Longitudinal: Enable for Camera SCC cars

opendbc/dbc/hyundai_kia_generic.dbc
Added `SLC_ON` and `SLC_SET_SPEED` signals to the ELECT_GEAR message.
Route: `e1107f9d04dfb1e2/00000179--d93c2e7bc1`
On my car, 
* `CF_Clu_SldMainSW` is used for enabling speed limit mode. 
* `CF_Clu_SldMainSW` is the same physical button as `CF_Clu_CruiseMainSW`, but goes rising edge on the second press of it
* When `CF_Clu_SldMainSW` goes rising edge, `MainMode_ACC` goes Falling Edge and `SLC_ON` (new) goes Rising Edge and stays like that until `CF_Clu_SldMainSW` is pressed once more. 
* The `SLC_SET_SPEED` is the limit speed chosen on the dash. It was displayed in km/h for me but my car is EU. Not sure how it would look on American cars.
* The speed is controlled via the known set and res buttons
Because this signal was missing, it causes a bad behavior with OP long control. 
More …
=> Add speed limit control signals for Ioniq PHEV 2020

opendbc/car/honda/carcontroller.py, opendbc/car/honda/hondacan.py, opendbc/car/honda/interface.py
@csouers identified a nice bus abstraction cleanup in #1330, but it shouldn't be in a car port PR. This PR lifts out just that change for separate review and validation. LGTM in testing locally, including process_replay.
=> Honda: Bus abstraction cleanup

docs/CARS.md, opendbc/car/volkswagen/values.py
Same issue as #1272, with the same eventual resolution.
=> VW MQB: Temporarily remove 2024 Volkswagen Tiguan

opendbc/car/toyota/carcontroller.py
swaglog already has a mechanism to collate/suppress repetitive messages.
=> Toyota: Cleanup SecOC key mismatch logging

opendbc/car/docs.py
`include_custom` flag not used in `docs.py`. Will add mentioned filter from screenshot in PR #1556 but still in draft. Discord message reference link [here](https://discord.com/channels/469524606043160576/1282121586002104402/1322660730775928944)<br><br>
=> docs: remove unused code

opendbc/car/honda/values.py, opendbc/car/hyundai/fingerprints.py
<details open><summary>View table</summary><br>
|Dongle, platform, VIN|Name from VIN 🆚 CarDocs|Segments|Bad seg tags|Good seg tags|
|:---------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------|:----------------------------------------|:---------------|:-------------------------------------------------|
|[7d0f7c027f1227fb](https://useradmin.comma.ai/?onebox=7d0f7c027f1227fb)<br><sub>HONDA_RIDGELINE<br>5FPYK3F57........</sub>|HONDA Ridgeline 2025 🆚<br>Honda Ridgeline 2017-24<br><sub>🎉 <b>New model year!</b> 🎉</sub>|2 routes,<br>27 segments<br>(0.5 hours)||- valid torque params: 27<br>- all lat active: 0|
Dongles to re-run category: …
=> [bot] Car docs: update model years from new users

opendbc/dbc/generator/toyota/_toyota_2017.dbc, opendbc/dbc/generator/toyota/_toyota_adas_standard.dbc, opendbc/dbc/generator/toyota/toyota_new_mc_pt.dbc, opendbc/dbc/generator/toyota/toyota_nodsu_pt.dbc, opendbc/dbc/generator/toyota/toyota_tnga_k_pt.dbc
Prereq for #1319 - migrate ADAS messages with SecOC overlaps/conflicts to a separate generator include.
=> Toyota: Separate DBC generator include for certain ADAS messages

opendbc/car/hyundai/values.py
The 2018 Genesis G90 should not be subject to the 255 steer max limit as it is fully capable of requesting the default 384 without error. I have been driving with this change since February with over 7k miles without issue. Attaching most recent route.
Car
2018 Genesis G90
Route
590a1a98ea35681c/2024-12-20--16-07-15/0
Including debug of car commanding and holding steer value of 384 without backing off in a tight freeway exit turn
=> Remove STEER_MAX limit for Genesis G90

opendbc/car/toyota/carcontroller.py
Doesn't do much. The future estimated aEgo we use for error correction provides a similar effect to derivative but is more pronounced and less noisy at larger scales, so we'll just keep that.
On the bottom of each plot, orange is derivative **removed** (this PR), green is the real route with current derivative.
Highway coasting: ![image](https://github.com/user-attachments/assets/f892ad9c-d511-4d3f-a105-0c981cddccac)
Highway accel: ![image](https://github.com/user-attachments/assets/61ddae8e-4190-4d4e-acf3-9d3ba77359ac)
Medium speed accel: ![image](https://github.com/user-attachments/assets/4a25db1d-5a6e-4580-9a8f-31ff720dca7d)
Medium speed braking: ![image](https://github.com/user-attachments/assets/c2c6bdf2-c43f-4f03-886e-934cd29b70c6)
=> Toyota: remove longitudinal derivative

docs/CARS.md, opendbc/car/honda/values.py
Due to #1637, temporarily remove 2022 Acura MDX from CARS.md and the comma shop. This is a documentation change only, currently-working cars will continue to work subject to the known bugs.
=> Honda: Temporarily revoke support for 2022 Acura MDX

opendbc/car/toyota/values.py
This PR adds the 2025 Toyota RAV4 Hybrid to the list of supported models.
Route for validation: `259d13f76542c811/00000005--7a4743f55f`
=> docs: Add support for 2025 Toyota RAV4 Hybrid

opendbc/car/toyota/carstate.py
brake includes user and computer
=> Toyota: log gas and brake

opendbc/car/tesla/carstate.py, opendbc/car/tesla/values.py
While experimenting with the Longitudinal Maneuvers Testing Tool, I noticed that the Model 3 throws an ACC fault `JERK_ISO_OUT_OF_BOUNDS` when the jerk is equal 5 and the accel is 0.
To avoid this fault, the jerk must be below 5.0 m/s³.
4.9m/s^3 Jerk: 
b5f2b5b4ef23f4b6/0000004c--a25a821a66
5.0m/s^3 Jerk (ACC Faulted):
b5f2b5b4ef23f4b6/0000004d--9567898415
=> Tesla: Jerk Limit

opendbc/car/toyota/carcontroller.py
Solves issues like: https://github.com/commaai/opendbc/issues/1632 by constantly slowly unwinding integral. This helps us recover from a large momentary error, without needing to oscillate/over/undershoot to the other side to unwind.
An alternative solution to https://github.com/commaai/opendbc/pull/1651. This is more generic, as the Prius example starts undershooting at ~6 m/s, which I haven't seen happen on any of our cars here (mostly 1-2 m/s).
=> Toyota: unwind longitudinal integral

opendbc/car/tesla/interface.py
Since openpilot without radar is not reliable, the stock ACC will be used unless experimental mode is enabled.
=> Tesla: longitudinal behind alpha toggle

opendbc/car/toyota/carcontroller.py
Regression from https://github.com/commaai/opendbc/pull/1532
Due to Toyota PCM's overzealous processing of ACC acceleration requests, the small jump that can occur when stopping can cause the brake controller to overreact and let go of the brakes entirely. This is only possible if the PID controller is applying a smaller acceleration than feedforward.
This issue at least affects hybrids, as seen in this case:
https://connect.comma.ai/d9b97c1d3b8c39b2/00000020--177f5572ab/1346/1362
This usually does not happen as [longcontrol.py starts with the last output accel when stopping](https://github.com/commaai/openpilot/blob/540c45bfec37266d943a1433bff82c9f88068fb5/selfdrive/controls/lib/longcontrol.py#L72), but Toyota is the only brand that has its final PID controller in carcontroller due to …
=> Toyota: fix acceleration discontinuity when stopping

opendbc/car/toyota/carcontroller.py
The Prius TSS2 displays much worse braking undershoot/let off when stopping compared to any of our cars here I've tested. This PR increases the gain at lower speeds to compensate for the higher PCM accel processing only displayed at low speed.
User reports and looking at the routes show improved behavior, including less instances where the car stops too close to the lead.
1d5211a9795b6ec2/0000015d--d282782d47
Closes: https://github.com/commaai/opendbc/issues/1632
=> Toyota: tweak longitudinal gains

opendbc/car/toyota/carcontroller.py
Avoids unsetting PERMIT_BRAKING when stopping on steep-enough uphills. We don't consider the creep force (and don't have an accurate/simple measurement), so this can incorrectly cause the car to creep forward when stopping.
https://connect.comma.ai/d9b97c1d3b8c39b2/00000033--81e54208be/1743/1766
=> Toyota: clip pitch for PERMIT_BRAKING

opendbc/car/ford/values.py
Assist has ACC w/ stop and go and lane centering. 2021 Lightning doesn't exist
https://media.ford.com/content/dam/fordmedia/North%20America/US/product/2022/f-150-lightning/pdf/F-150_Lightning_Tech_Specs.pdf
https://live.dealer-asset.co/me18/product/file/EN-F-150-Brochure.pdf
All Mach-E come with Assist 2.0: https://cdn.dealereprocess.org/cdn/brochures/ford/2021-mustangmache.pdf
=> Ford: fix required package docs

opendbc/car/car.capnp, opendbc/car/gm/carstate.py, opendbc/car/interfaces.py, opendbc/car/volkswagen/carstate.py
To remove logic that lives in openpilot now for handling the brands' various implementation of button enabling. Pt. 1 of deleting [car_specific.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/car_specific.py)
=> Add buttonEnable carState field

opendbc/car/volkswagen/carstate.py
In rare configurations, the EPS reverts back to INITIALIZING when auto start-stop has stopped the engine at standstill. It might be related to EPS configuration options that control whether EPS power assist is available with ignition-on but the engine not running.
Route demonstrating the problem: `ba88d39b49c5e6b8/0000000b--afe45956d1`
The other fault states give us the coverage we need.
=> VW: Don't treat the initializing state as a fault

pyproject.toml
pre-req to publishing car/ to pypi
`Can't have direct dependency: pandacan@`: https://github.com/commaai/opendbc/actions/runs/13252490998/job/36993192664
=> rm panda as dependency

opendbc/dbc/volvo_v60_2015_pt.dbc
Most signals moved around after loading/saving with cabana. I also found good signals for the brake pedal.
This isn't used in openpilot at the moment but I am working on a port.
=> update Volvo V60 signals

opendbc/car/toyota/carstate.py
Reverts commaai/opendbc#1640
Some of the routes were before we logged the hybrid ECU, which makes them not hybrid in the test_models test, and some TSSP hybrid cars don't have `BRAKE`
=> Revert "Toyota: log gas and brake"

opendbc/car/tesla/carcontroller.py, opendbc/car/tesla/carstate.py, opendbc/car/tesla/values.py
The stock signal sets the hands on level to 1 when the torque is above 0.5 for at least around 0.25s to 0.3s, then resets it to 0 the frame that the torque drops below 0.5 again. This matches that but with a quicker activation time. Tested and lane changes felt more responsive and less likely to disengage the system.
Tested stock limits here: https://connect.comma.ai/2c912ca5de3b1ee9/00000036--8e3c857ddb/1463/1764
=> Tesla: quicker steering pressed logic

opendbc/car/tesla/interface.py
The delay is much lower than the 0.45 we are using, causing jittery extrapolations
=> Tesla: lower steering actuator delay

opendbc/car/docs_definitions.py
- RJ45 cable is no longer required on v2 harness box
- OBD-II had duplicate `long_obdc_cable` entries
- VW J533 was missing the comma power, even though the website states it
is included
=> remove rj45 cable, duplicate obd-c for obd-ii conn

opendbc/car/fw_versions.py, opendbc/car/tests/test_fw_fingerprint.py
Tesla only has one ECU we can query at the moment (EPS), and it also matches several other brands so they are tried first by accident, slowing down FW querying:
```
{'body': set(), 'chrysler': set(), 'ford': {(1840, None)}, 'gm': set(), 'honda': set(), 'hyundai': {(1840, None)}, 'mazda': {(1840, None)}, 'nissan': set(), 'subaru': set(), 'tesla': {(1840, None)}, 'toyota': set(), 'volkswagen': set()}
```
=> FW query: sort brands by percentage of ECU matches

conftest.py, opendbc/safety/tests/test.sh
fix from https://github.com/commaai/opendbc/pull/1756 so we don't execute cppcheck test and shell scripts inside misra/
=> Fix pytest discovery

opendbc/car/tesla/carcontroller.py
Unclear if this does anything on newer cars. FSD is seen at 35+, and during high curvature rate turns, this effectively limits the rate much lower than intended.
https://connect.comma.ai/2c912ca5de3b1ee9/00000061--464f9c85c3
See the up and down limits are effectively the same because of this:
=> Tesla: remove old fault prevention code

opendbc/car/hyundai/values.py
In [docs_definitions.py](https://github.com/commaai/opendbc/blob/master/opendbc/car/docs_definitions.py#L190), `false` is the default
<br>
Line 190:
```
`CarFootnote = namedtuple("CarFootnote", ["text", "column", "docs_only", "shop_footnote"], defaults=(False, False))
```
=> Remove redundant parameter in `hyundai/values.py`

opendbc/car/tesla/carcontroller.py
This doesn't cause faults apparently, so it's unnecessary
=> Tesla: remove angle delta limit

docs/CARS.md, opendbc/car/hyundai/fingerprints.py, opendbc/car/hyundai/values.py
Add firmware versions for the 2024 Genesis GV70 Electrified. Expand supported model-year range up to 2024.
Dongle ID: `d83a7170c18fb4ff`
Thanks to the community 2024 Genesis GV70 Electrified ownerjaredislate.
=> Genesis: Add FW versions for GV70 Electrified 2024

opendbc/dbc/generator/honda/honda_pilot_2023_can.dbc
This gearbox message is actually used on the non-Hybrid 6th gen CRV. Similar to the Accord 1.5/2.0L gearbox differences.
Verification - 2dc4489d7e1410ca/00000004--eb4c907d01
See https://github.com/commaai/opendbc/pull/1057
=> Honda: CANFD Gearbox

opendbc/car/ford/interface.py, opendbc/car/ford/values.py
There's an issue preventing F150 Lightning from having a smooth install. A custom, extended harness is required or another solution needs to be identified.
See: https://github.com/commaai/openpilot/issues/30302
=> Ford: pull F150 Lightning out of dashcam

docs/CARS.md, opendbc/car/ford/values.py
Route: `05dafe69b25c52d8/00000001--25b7fa8377`
=> Ford: expand F-150 model year to include 2021

opendbc/car/car.capnp
In support of commaai/openpilot#34679.
=> cereal: add currentCurvature to CarControl

opendbc/car/volkswagen/carstate.py, opendbc/car/volkswagen/values.py, opendbc/dbc/vw_meb.dbc, opendbc/dbc/vw_mqb_2010.dbc
Switch from reading the transmission message directly, to an aggregate/proxy message from the CAN gateway. This allows the exact same gear-position handling for MQB, MQBevo, and MEB.
We still have to detect presence of Getriebe_11 as part of MQB startup, this is deliberate. I was hoping we could get rid of the special-case for e-Golf, but sadly the proxy message doesn't translate that for us.
**Verification**
* Validated behavior against the comma car segments dataset
* `pytest selfdrive/car`
* `selfdrive/test/process_replay/test_processes.py`
@sshane When openpilot bumps opendbc, this will produce a tiny process_replay diff for gear position, just due to timing. We get Getriebe_11 at 100Hz and Gateway_73 is 20Hz.
```
***** results for segment regenED976DEB757|2024-08-30--03-18-02--0 …
```
=> VW MQB: Change source of gear position signal

opendbc/car/rivian/carstate.py, opendbc/dbc/rivian_can.dbc
The current signal doesn't capture door open when not in full ignition/ready state, and also doesn't capture any other door
=> Rivian: add passenger door open signals

opendbc/car/ccp.py, opendbc/car/isotp.py, opendbc/car/xcp.py
`uds.py` was moved from panda into opendbc. This PR keeps the other diagnostics protocols (isotp, CCP and XCP) together  by moving them to opendbc as well.
Maybe `isotp.py` should be removed entirely. It's not used anywhere as far as I can tell, and `uds.py` already has it's own implementation for a `IsoTpMessage`. `IsoTpMessage` should probably moved to a different file and get some tests, but that is a PR for another day.
=> Move isotp.py, ccp.py and xcp.py from panda

opendbc/car/tests/test_vehicle_model.py, opendbc/car/vehicle_model.py
For https://github.com/commaai/opendbc/pull/1231
=> Add vehicle_model.py

opendbc/car/hyundai/values.py
Reverts commaai/opendbc#1825
These need to match safety, and this makes it harder to check by eye that they match
=> Revert "Simplify Hyundai safety flag values"

opendbc/safety/safety.h, opendbc/safety/safety/safety_chrysler.h, opendbc/safety/safety/safety_ford.h, opendbc/safety/safety/safety_gm.h, opendbc/safety/safety/safety_hyundai.h, opendbc/safety/safety/safety_hyundai_canfd.h, opendbc/safety/safety/safety_mazda.h, opendbc/safety/safety/safety_nissan.h, opendbc/safety/safety/safety_rivian.h, opendbc/safety/safety/safety_subaru.h, opendbc/safety/safety/safety_subaru_preglobal.h, opendbc/safety/safety/safety_tesla.h, opendbc/safety/safety/safety_toyota.h, opendbc/safety/safety/safety_volkswagen_mqb.h, opendbc/safety/safety/safety_volkswagen_pq.h, opendbc/safety/safety_declarations.h
confusing that both modes have attributes in the same struct, and we need different max steers for Hyundai now (plus we never used them for other brands, causing blocked messages while disengaged)
=> safety: split torque and angle steering limits

opendbc/safety/tests/test.sh, pyproject.toml
This is in order to support exclusion markers e.g. #1851.
This also replaces lcov, since it's one less dependency, is smaller, and can be installed via uv (or apt).
Compared to gcov, gcovr:
➖ txt reports take 180ms instead of 8ms, so test.sh takes 2% longer to run on my machine.
Compared to lcov, gcovr:
➕ html reports take 300ms instead of 800ms, so test.sh is 6% faster.
➕ generated report size is 2.8 MB vs 4.2 MB
➕ transitive install size is 2.15 MB vs 32.07 MB
➕ report is faster to navigate, contains more info (e.g. branch info)
gcovr sample: [link](https://ccdunder.github.io/gcovr-comparison/gcovr/)
lcov sample: [link](https://ccdunder.github.io/gcovr-comparison/lcov/)
=> Replace gcov & lcov with gcovr

.github/workflows/test_models_trigger.yaml
whenever we leave a comment we get pinged with a failure due to an if conditional not being added on the bump opendbc step itself. adding this check will allow the workflow to run with no failures.
GHAs Failing: https://github.com/commaai/opendbc/actions/workflows/test_models_trigger.yaml
=> `test_models_trigger.yaml`: add checkout check to prevent opendbc bump fail

opendbc/car/rivian/carstate.py
Found when testing https://github.com/commaai/opendbc/pull/1910. A value of 3 can cancel stock ACC (ACM/Autonomous eXperience Module), but likely permanently faults it after some time:
2d2da5dea63b5c5e/00000004--c739b2e2a0
=> Rivian: add VDM fault signal

opendbc/car/tests/test_can_fingerprint.py, opendbc/car/tests/test_car_interfaces.py, opendbc/car/tests/test_fw_fingerprint.py, opendbc/car/tests/test_routes.py
This change reduces the `car/tests/` collection time to ~0.4s.
```
~/opendbc$ pytest --cache-clear --collect-only opendbc/car/tests/
================================ 1735 tests collected in 0.42s ===========================
```
This links to https://github.com/commaai/opendbc/issues/1184.
=> Replace @parameterized.expand with @pytest.mark.parametrize to improve test speed

opendbc/safety/safety/safety_rivian.h
From https://github.com/commaai/opendbc/pull/1903
=> Rivian safety: check missing rx addr

opendbc/car/rivian/carstate.py
We've caused Imps by sending the VDM implausible commands (rapidly oscillating cruise states), but haven't repro'd Cntr. We've seen at least one user hit this, so we're removing until we confirm it's actually a fault that prevents enabling. VDM_AdasFaultStatus_Brk_Intv is the default, so maybe it's a fine state to enable in.
=> Rivian: remove a VDM ACC fault signal

opendbc/can/common.pxd, opendbc/can/parser_pyx.pyx
This PR adds `nogil` annotations to the cython `CANParser`, enabling the GIL to be released during C++ operations. By allowing the GIL to be freed, this change enhances the potential for improved multi-threaded performance, especially in scenarios where multiple threads need to run concurrently, such as in test cases that involve parsing CAN messages (e.g., test_car_interface).
=> parser_pyx: add nogil for improved threading performance

opendbc/safety/tests/test_ford.py, opendbc/safety/tests/test_gm.py, opendbc/safety/tests/test_honda.py, opendbc/safety/tests/test_hyundai_canfd.py, opendbc/safety/tests/test_rivian.py, opendbc/safety/tests/test_tesla.py, opendbc/safety/tests/test_toyota.py, opendbc/safety/tests/test_volkswagen_mqb.py, opendbc/safety/tests/test_volkswagen_pq.py
common already checks for Base suffix
=> safety tests: remove redundant test skips

opendbc/safety/safety/safety_hyundai_canfd.h
split from https://github.com/commaai/opendbc/pull/1985
=> Hyundai CAN FD safety: more clear what is common

opendbc/safety/safety/safety_hyundai_canfd.h, opendbc/safety/tests/test_hyundai_canfd.py
we need some pre-processor ASAP
for https://github.com/commaai/opendbc/pull/1903, some cars have both messages so safety can select the wrong one randomly
=> Hyundai CAN FD safety: replace alt buttons live detection with param

opendbc/safety/tests/safety_replay/helpers.py
Noticed a good amount of blocked tx messages when running some CAN FD routes via safety replay in this PR:
- https://github.com/commaai/opendbc/pull/1903
**Before**
```
replaying b5d6dc830ad63071|2022-12-12--21-28-25/12 with safety mode 28, param 13, alternative experience 0
no steering msgs found!
RX
total rx msgs: 190253
invalid rx msgs: 0
safety tick rx invalid: False
invalid addrs: set()
TX
total openpilot msgs: 10200
total msgs with controls allowed: 6698
blocked msgs: 265
blocked with controls allowed: 81
blocked addrs: Counter({298: 203, 416: 62})
```
**After**
```
replaying b5d6dc830ad63071|2022-12-12--21-28-25/12 with safety mode 28, param 13, alternative experience 0
RX
total rx msgs: 190253
invalid rx msgs: 0
safety tick rx invalid: False
invalid addrs: set()
TX
total openpilot …
```
=> Hyundai CAN FD: Fix steering messages in safety replay

opendbc/car/hyundai/carcontroller.py
Closes https://github.com/commaai/opendbc/issues/1899
=> Hyundai: split car controller by CAN FD

opendbc/safety/safety/safety_toyota.h
Sienna has both addresses (so it can select one randomly), but uses the non-alt brake message
https://github.com/commaai/openpilot/actions/runs/13805849303/job/38616391153?pr=34848
=> Toyota: add static rx check for alt brake

opendbc/car/car.capnp, opendbc/car/ford/radar_interface.py, opendbc/car/gm/radar_interface.py, opendbc/car/honda/radar_interface.py
Radar just sends the last message while in reverse (for everything; tracks, headers, etc.), so we need to detect a stalled scan index and add a fault instead of stop sending liveTracks:
=> Ford: radar is invalid when in reverse

opendbc/car/body/interface.py, opendbc/car/body/radar_interface.py, opendbc/car/car_helpers.py, opendbc/car/chrysler/interface.py, opendbc/car/docs.py, opendbc/car/ford/interface.py, opendbc/car/gm/interface.py, opendbc/car/honda/interface.py, opendbc/car/hyundai/interface.py, opendbc/car/interfaces.py, opendbc/car/mazda/interface.py, opendbc/car/mazda/radar_interface.py, opendbc/car/mock/interface.py, opendbc/car/mock/radar_interface.py, opendbc/car/nissan/interface.py, opendbc/car/nissan/radar_interface.py, opendbc/car/rivian/interface.py, opendbc/car/subaru/interface.py, opendbc/car/subaru/radar_interface.py, opendbc/car/tesla/interface.py, opendbc/car/tesla/radar_interface.py, opendbc/car/tests/test_car_interfaces.py, opendbc/car/tests/test_fw_fingerprint.py, opendbc/car/tests/test_lateral_limits.py, opendbc/car/toyota/interface.py, opendbc/car/volkswagen/interface.py, opendbc/car/volkswagen/radar_interface.py
Removes need to define empty radar interface file, one less thing when porting a car. pytest collection time is not sped up with the static imports, so leaving that out until there's a cleaner solution
=> car interfaces: each specify their own dependencies

opendbc/safety/tests/safety_replay/helpers.py
Was analyzing [this issue](https://github.com/commaai/opendbc/issues/1994) and realized that we never had `hyundaiLegacy` in the steering message checks in safety replay 😁
Before:
```
replaying 3687c15bdfe09295/0000005f--888dec6063/2 with safety mode 23, param 0, alternative experience 1
no steering msgs found!
RX
total rx msgs: 230451
invalid rx msgs: 0
safety tick rx invalid: False
invalid addrs: set()
TX
total openpilot msgs: 6000
total msgs with controls allowed: 0
blocked msgs: 5966
blocked with controls allowed: 0
blocked addrs: Counter({832: 5966})
```
After:
```
replaying 3687c15bdfe09295/0000005f--888dec6063/2 with safety mode 23, param 0, alternative experience 1
RX
total rx msgs: 230451
invalid rx msgs: 0
safety tick rx invalid: False
invalid addrs: set()
TX
total openpilot …
```
=> Safety Replay: add Hyundai Legacy to steering message checks

opendbc/car/docs_definitions.py
To match the website
https://comma.ai/shop/car-harness?make=OBD-II
=> docs: add USB-C coupler to OBD-II harness

opendbc/car/docs_definitions.py
The J533 harness has constant power from the gateway.
=> docs: remove comma power from J533 harness

opendbc/car/gm/carcontroller.py, opendbc/car/gm/gmcan.py, opendbc/car/gm/values.py, opendbc/dbc/generator/gm/gm_global_a_powertrain.dbc, opendbc/safety/safety/safety_gm.h, opendbc/safety/tests/common.py, opendbc/safety/tests/test_gm.py
Correct scaling and offset now. Plus checksum is 1 bit larger, which captures that fake inverse bit, removed some set mes.
Opened to preserve, will verify later.
This does not change behavior.
=> GM: fix ASCMGasRegenCmd scale and units

opendbc/car/docs_definitions.py
Match the [website][1]
[1]: https://comma.ai/shop/obd-c-cable
=> docs: add long OBD-C cable length

opendbc/car/subaru/fingerprints.py
Updated abs, engine, and transmission firmware versions for the 2022 Subaru Outback Touring XL
Dongle ID: 9dd15af9f772f8ab
=> Subaru: Add FW for 2022 Subaru Outback Touring XL

opendbc/safety/safety/safety_ford.h, opendbc/safety/safety/safety_rivian.h, opendbc/safety/tests/test_rivian.py
For https://github.com/commaai/opendbc/pull/2016
<details><summary>During a low speed high curvature turn, they can be seen >1 kph apart:</summary>
</details>
<details><summary>During braking and acceleration they can be seen close together:</summary>
</details>
The comment for the ESP signal is as follows:
```
CM_ SG_ 520 ESP_Vehicle_Speed "ESP calculated vehicle speed. Average of front wheels on rear wheel drive vehicles. Average of all four wheels on dual motor vehicles.";
```
<details><summary>Since we don't have too much information about the VDM signal, we just have to make an educated guess. But from how it varies most when turning, it sounds like it's averaging the wheel speeds differently, or is a more direct measurement from a different location/sensors. Note here how the VDM …
=> Rivian safety: check 2nd speed source

opendbc/car/tesla/carstate.py
The existing signal would only describe the stalk position if the auto-cancel blinker option was disabled, in effect it would be a single frame. This now captures all states properly
=> Tesla: fix convenience blinker

.github/workflows/tests.yml
This change moves the GIT_REF definition into the environment section, otherwise it's not really used as expected by the script
I can also set it like this 
```
GIT_REF: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.event.before || format('origin/{0}', github.event.repository.default_branch) }}
```
I think this is better for forks in the long run as some (like us at SP for the time being) use `master-new` for our rewrite with this it becomes more universal
=> CI: Set GIT_REF as an environment variable for safety mutation tests

.github/workflows/tests.yml
- Introduced in https://github.com/commaai/opendbc/pull/1956, safety mutation test in `master` currently does not do a git diff to run mutation tests properly due to bad formatting
- Fix nested GitHub expression syntax in mutation job
- Replace nested `${{ ... }}` with `format()` function
- Fix reference to default branch in GIT_REF environment variable
- Ensure proper evaluation of branch conditions in workflow
| Before | After |
| -- | -- |
| ![image](https://github.com/user-attachments/assets/45763542-fee6-4659-b74d-1d1e8ea3cb5d) | ![image](https://github.com/user-attachments/assets/7de895d1-55d0-43eb-83df-559128fe61fd) |
=> CI: Fix `GIT_REF` formatting in safety mutation workflow

opendbc/safety/safety.h, opendbc/safety/safety_declarations.h
Split from https://github.com/commaai/opendbc/pull/2087
Our brake, gas, and regen controls allowed logic only worked because every safety mode implemented at least one message it checked a relay malfunction for. Without that, these would never be executed. Additionally it would be run multiple times per rx message needlessly.
This PR:
- Run generic rx checks only once for every incoming rx message (up from minimum of zero times and down from max of len(rx_msgs)
=> safety: split relay malfunction and generic rx checks

opendbc/safety/safety/safety_body.h, opendbc/safety/safety/safety_chrysler.h, opendbc/safety/safety/safety_ford.h, opendbc/safety/safety/safety_gm.h, opendbc/safety/safety/safety_honda.h, opendbc/safety/safety/safety_hyundai.h, opendbc/safety/safety/safety_hyundai_canfd.h, opendbc/safety/safety/safety_mazda.h, opendbc/safety/safety/safety_nissan.h, opendbc/safety/safety/safety_rivian.h, opendbc/safety/safety/safety_subaru.h, opendbc/safety/safety/safety_subaru_preglobal.h, opendbc/safety/safety/safety_tesla.h, opendbc/safety/safety/safety_toyota.h, opendbc/safety/safety/safety_volkswagen_mqb.h, opendbc/safety/safety/safety_volkswagen_pq.h
For https://github.com/commaai/opendbc/pull/2092
Improves readability. Consistent with RxCheck now. Allows us to add a new field to CanMsg without changing 100 lines (since our compiler warns/errors for this if we don't have at least one named argument).
=> safety: switch to field initializer for check_relay

opendbc/safety/safety/safety_gm.h
split from https://github.com/commaai/opendbc/pull/2095
=> GM ASCM safety: use disable_forwarding

opendbc/safety/safety/safety_honda.h, opendbc/safety/tests/test_honda.py
=> safety: move Honda to msg block config

opendbc/safety/board/drivers/can_common.h, opendbc/safety/board/utils.h, opendbc/safety/safety.h, opendbc/safety/safety_declarations.h
No-op change for https://github.com/commaai/panda/issues/2171
- Moves some functions and declarations around so that they can be correctly included in Panda headers.
In [panda](https://github.com/commaai/panda), we currently need some defintions from [safety.h](https://github.com/commaai/opendbc/blob/master/opendbc/safety/safety.h). But we can't include safety.h directly because it contains function implementatinos (we eventually should link the implementations at compile time). 
So in this PR, we're just safely moving code that will allow us to include headers from opendbc without compiler errors.
- Panda needs access to `SAFETY_ALLOUTPUT`. But we can't directly include safety.h anywhere in panda because safety.h contains implementations (can't link multiple objects files that contain …
=> No-op changes to make Panda happy

opendbc/car/hyundai/values.py
The 2022 Hyundai Kona requires more conservative steering torque limits compared to standard Hyundai models. This PR applies the ALT_LIMITS_2 flag 
dongle id: [0099bdb24d82951b]
=> Kona 2022 alt limit flag

opendbc/car/tesla/carstate.py
Normally we use the hands on level to disengage, however that seems to be quite delayed. FSD will disengage on the union of hands on level for normal, slow overrides, as well as an EAC status of `EAC_INHIBITED` && fault code of `EAC_ERROR_HIGH_ANGLE_RATE_SAFETY`. When this new combination is true, FSD disengages as normal--no alerts/faults/messages, just a disengage chime. This PR matches that.
Confusingly, we actually re-enabled steering after these events when you expected it to disengage. That's fixed.
FSD route testing rapid overriding: https://connect.comma.ai/2c912ca5de3b1ee9/0000023e--ad364991c0/657/715
=> Tesla: fix steer fault when quickly overriding

opendbc/dbc/tesla_model3_party.dbc, opendbc/safety/safety/safety_tesla.h, opendbc/safety/tests/test_tesla.py
Closes https://github.com/commaai/opendbc/issues/2200, matching how https://github.com/commaai/opendbc/pull/2049 added 2nd speed check, which was based on Ford
It looks like the signal in `DI_speed` uses the motor speeds to calculate its speed (calibration is likely [mentioned here](https://service.tesla.com/docs/ModelY/ServiceManual/en-us/GUID-5B457CEE-3E8B-4EBA-920E-5F9A2402F131.html), look for "Inverter Resolver Error Learning"), and the signal in `ESP_B` uses the wheel speed sensors ([mentioned here](https://service.tesla.com/docs/Model3/ServiceManual/en-us/GUID-E4D1FACE-A01E-4645-8DA0-0D9296C5AB4C.html)).
The closest Tesla error code I found was [DIR_a075_motorSpeedMismatch](https://tesware.net/alerts/model3/DIR_a075_motorSpeedMismatch), so it's very likely it also checks for …
=> Tesla safety: check 2nd speed source

opendbc/car/tesla/carcontroller.py, opendbc/car/tesla/teslacan.py
Still need to manually set `DAS_control` since we try to match the stock counter when canceling with stock long
```python
print(packer.make_can_msg('APS_eacMonitor', 0, {})[1].hex())
000000
print(packer.make_can_msg('APS_eacMonitor', 0, {})[1].hex())
000100
print(packer.make_can_msg('APS_eacMonitor', 0, {})[1].hex())
000200
print(packer.make_can_msg('APS_eacMonitor', 0, {})[1].hex())
000300
print(packer.make_can_msg('APS_eacMonitor', 0, {})[1].hex())
000400
print(packer.make_can_msg('APS_eacMonitor', 0, {})[1].hex())
```
=> Tesla: let CANPacker set counters

opendbc/can/common.h
Two failure modes with current function:
- Suffix one character longer than string: false positive (npos is -1, so is subtraction)
- String starts with suffix and ends with suffix: false negative (gets first occurrence)
```c++
endswith("DI_gearDI", "DI") -> false
endswith("DI_gear", "Checksum") -> true
```
=> dbc: fix incorrect endwith check

opendbc/dbc/tesla_model3_party.dbc
So we don't have to ignore it in safety
=> Tesla: add missing checksum signal

opendbc/safety/safety/safety_tesla.h, opendbc/safety/tests/test_tesla.py
Checks `ESP_wheelSpeedsQF`, conveniently the same name as Ford's quality flag signals
=> Tesla safety: check quality flag ESP_B (2nd speed)

.github/workflows/tests.yml, opendbc/safety/tests/libsafety/SConscript
resolves: https://github.com/commaai/openpilot/issues/35093
special handling was added for mac to resolve gcc (internally, clang) to the actual GNU compiler (resolved as gcc-<ver> with brew): https://github.com/commaai/panda/pull/1241
with a recent update to MacOS (some time near 15.4), `gcc` was broken.
upon checking, clang17 supports `-std=gnu11`, which was the original complaint. as well, builds just fine. but there are still issues with building on less than 15 with clang.
using gcc on less than 15.
```
-- with .app --
➜ clang --version
Apple clang version 17.0.0 (clang-1700.0.13.3)
Target: arm64-apple-darwin24.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
-- with default CommandLineTools version, also …
```
=> fix(macos): macOS 15 and greater

opendbc/dbc/generator/gm/gm_global_a_powertrain.dbc
When paired with EBCMRegenPaddle, State "5" unlocks the full 70kW regen available to the chevy bolt (State 7 is for gen1 bolts, state 5 is gen2). Static bytes must also be defined and sent for car to accept the signal. 
I'm using it to get access to full regen with a pedal interceptor, but it may also be an applicable method for regen blending on GM acc enabled vehicles. Still testing.
=> Bolt 70kW Regen Signal

opendbc/car/honda/carstate.py, opendbc/car/honda/hondacan.py, opendbc/dbc/generator/honda/_bosch_2018.dbc
Reverts commaai/opendbc#2104
This may have broken @MarcoTheDingo 's 2022 Civic, who reported to me no longer having steering work on his car after rebasing his Tuning branch with todays PR cleanup. 
Working on confirming/debugging but would be best to revert for now. Can reopen later if needed
=> Revert "Honda Bosch: Steer to zero"

opendbc/safety/tests/common.py, opendbc/safety/tests/test_tesla.py
split from https://github.com/commaai/opendbc/pull/2115
Python doesn't do the same rounding that C++ CANParser does! it tries to avoid bias :'(
=> safety: add round helper

opendbc/car/honda/values.py
- verify Honda torque arrays start at zero in `CarControllerParams`
- clarify comment explaining this check
- `ruff check opendbc/car/honda/values.py`
- `pre-commit` *(fails: command not found)*
=> Fix torque array assert

opendbc/car/isotp_parallel_query.py
- fix misspelled `subaddress` in `_can_rx`
- `./test.sh` *(fails: No route to host)*
=> Fix typos in isotp_parallel_query helper

README.md
- clarify structure section phrase
- fix typo `entirery` -> `entirety`
- `./setup.sh` *(fails: Failed to fetch pytest-mock from pypi.org)*
=> Fix phrasing in README

.github/workflows/tests.yml
Cache hit, but version had been bumped so it always built cppcheck and never cached it. Don't see a reason for per-branch either
=> Fix cppcheck cache

opendbc/car/interfaces.py
Maybe at one point it used to do more
Edit: ah yeah, these are all gone: https://github.com/commaai/openpilot/blob/0eba392cf24e5ebbd09d7a3ff4acd9f98daeb3bb/selfdrive/car/toyota/interface.py#L291-L319
=> interfaces: remove redundant function

opendbc/car/car.capnp, opendbc/car/hyundai/carstate.py, opendbc/car/interfaces.py
We went from checking every 50 Hz CLU11 button message to checking at 100 Hz, so we halve the time we sample for user button presses. I guess this wasn't a problem for most cars, but the issue below shows the PCM enabling a little bit out of the new halved sample window which is now fixed again.
Broken in https://github.com/commaai/openpilot/pull/33710
Closes https://github.com/commaai/opendbc/issues/2156
Matching old reference carstate and interface: https://github.com/commaai/openpilot/blob/6a15aa3f8c58e40e5e47c7ce4c906f5368ec243a/selfdrive/car/hyundai/interface.py
=> Hyundai: fix recent enable button press regression

opendbc/car/hyundai/carstate.py
Forgot to include for CAN FD...pulls out check into function
for https://github.com/commaai/opendbc/pull/2262
=> Hyundai CAN FD: fix recent enable button press regression

opendbc/car/tesla/carcontroller.py
We limit the lateral jerk for Tesla, but because at very low speed this allows for super high angle rates, we should limit it for comfort. Once the models get better, we can gradually raise this.
=> Tesla: lower comfort angle rate limit

opendbc/car/toyota/carstate.py
goes high when dash is showing a fault that doesn't prevent engagement. this signal also goes 1 when we cancel via sending temp faulted ACC_CONTROL message, so not to be relied on. only if it's constantly high, it can be useful for debugging issues
=> Toyota: log temp dash faults

opendbc/car/interfaces.py
Now doesn't reset to unpressed if it gets a single sample under the threshold, it ramps back down like CANParser and safety's invalid counter counter. Only difference is we allow going above the threshold by 2x, so also allow time for the torque to switch signs before dropping.
old vs. new (these plots are before https://github.com/commaai/opendbc/pull/2233):
=> interfaces: improve steering pressed signal

opendbc/safety/modes/tesla.h, opendbc/safety/safety.h, opendbc/safety/safety_declarations.h
old angle check uses per-frame angle deltas, new angle check uses jerk
=> safety: add frequency parameter to angle limit struct

opendbc/car/ford/fingerprints.py
Note: route is missing EPS fw...
Route: `0b2c0bec9a28eb0f/00000000--d6637dad8d`
Second route: `0b2c0bec9a28eb0f/00000001--c766afec05` (eps still missing)
=> Ford: add F-150 Lightning 2022 FW

opendbc/car/hyundai/interface.py
Would show dashcam mode for a user in Zendesk today instead of various CAN bus disconnect errors (non-US car with HDA2 topology but marketed as HDA1, so got wrong harness)
=> Hyundai CAN FD: add supported configuration checking

opendbc/car/honda/values.py, opendbc/car/tests/test_docs.py
We've been weighting what to fail during runtime and what to fail during tests: Causing an exception during run time is too much for a misformatted docs string, better to keep in the test for now
=> Car docs: fix year test

opendbc/car/ford/carcontroller.py
Validation
* Dongle ID: 
* Route:
=> Bronco special

opendbc/dbc/generator/hyundai/hyundai_canfd.dbc
This signal is for LFA2 vehicles that uses steering grip sensor.  https://www.hyundaimotorgroup.com/innovation/CONT0000000000005027
Validation
* Dongle ID: `e1107f9d04dfb1e2`
* Route: `e1107f9d04dfb1e2/0000025f--8df0049cd4`
> [!NOTE]
> The signal name is not 100% confirmed officially. This is because while I found found the signal on an official DBC, the message address was not the same as what I found, and neither was the structure completely. However, the values themselves mapped to what I found, so my only guess is that the signal simply got updated since the dbc I found. 
> [!NOTE]
> needed by: https://github.com/commaai/opendbc/pull/1676
=> HKG: Add hands-on detection signal for LFA2 vehicles

opendbc/car/honda/carstate.py, opendbc/car/honda/interface.py, opendbc/car/honda/values.py
Convert the all-doors-state message to auto-detection.
Doors beyond the driver's door aren't necessarily of critical value, but it won't be too hard to keep with auto-detect, and I'd like to minimize behavior changes during the refactor project.
=> Honda: Door open message refactor, part 1

opendbc/safety/tests/common.py
The Subaru LKAS_ANGLE message is limited to a signed, 17-bit integer, which is more than enough for it's maximum steering of around 485 degrees (at least for my Ascent). However, the `test_angle_cmd_when_enabled()` defaults to twice the maximum steering angle, which will overflow this value and result in erroneously failed tests.
I have added a class variable, and logic that will default the test angle to twice the max angle value when it is not specifically configured. This keeps current behavior for existing tests, but will allow me to constraint he maximum test angle to the limits of my CAN bus messages. It's quite possible that other vehicles will be affected as more angle-based steering systems are supported, too.
=> Allow configurable maximum angle for AngleSteeringSafetyTest

opendbc/dbc/generator/honda/honda_crv_executive_2016_can.dbc, opendbc/dbc/generator/honda/honda_fit_hybrid_2018_can.dbc
`STEERING_SENSORS` for these DBCs can use one of the existing common definitions.
=> Honda: Steering sensors refactor

opendbc/car/car.capnp, opendbc/car/ford/carstate.py, opendbc/car/honda/carstate.py, opendbc/car/tesla/carstate.py
Can't remove these as they're used for control in some cars, but no need to parse it out on the other cars.
This even resolves this Honda TODO:
https://github.com/commaai/opendbc/blob/cdf3e4a199995cc46b4169eadb8920135b45a7c3/opendbc/car/honda/carstate.py#L33
=> Slimming `carState`, part 2

opendbc/car/chrysler/carstate.py, opendbc/car/gm/carstate.py, opendbc/car/honda/carstate.py, opendbc/car/hyundai/carstate.py, opendbc/car/interfaces.py, opendbc/car/mazda/carstate.py, opendbc/car/nissan/carstate.py, opendbc/car/subaru/carstate.py, opendbc/car/toyota/carstate.py, opendbc/car/volkswagen/carstate.py
Reverts commaai/opendbc#2514
```
FAILED test_models.py::TestCarModel_14_CHEVROLET_BOLT_EUV::test_panda_safety_carstate@CarTestRoute(route='f08912a233c1584f/2022-08-11--18-02-41', car_model=<CAR.CHEVROLET_BOLT_EUV>, segment=1) - AssertionError: 1 is not false : panda safety doesn't agree with openpilot: {'standstill': 5}
FAILED test_models.py::TestCarModel_21_CHEVROLET_VOLT_2019::test_panda_safety_carstate@CarTestRoute(route='477dd485611d1e6e/00000009--85fc06e10a', car_model=<CAR.CHEVROLET_VOLT_2019>, segment=None) - AssertionError: 1 is not false : panda safety doesn't agree with openpilot: {'standstill': 1}
FAILED test_models.py::TestCarModel_19_CHEVROLET_TRAVERSE::test_panda_safety_carstate@CarTestRoute(route='a40976dc9f28ba62/0000001f--160e210119', car_model=<CAR.CHEVROLET_TRAVERSE>, …
```
=> Revert "Slimming `carState`, part 6"

opendbc/car/honda/values.py
Adding Civic Hybrid 2025, uses existing fingerprints.
https://discord.com/channels/469524606043160576/469532500335656972/1393459006244262009
Validation
* Dongle ID: c3adb3c7be513ea7
* Route: 0000001e--95b660fd39
=> Honda: Update docs, adding 2025 Civic Hybrid

opendbc/car/honda/interface.py
Acura RDX can't use the common generated gearbox messages, and doesn't have a CVT option. This code path wouldn't be followed in the real world, but fuzzy CI tests can probe past the check, so make its snowflake status official.
=> Honda: Acura RDX is a snowflake

SConstruct, opendbc/can/common.h, opendbc/can/common.pxd, opendbc/can/parser.cc, opendbc/can/parser_pyx.pyx, opendbc/can/tests/test_checksums.py
Our frequency checks are currently relatively lax. While it would be nice (in theory) to make them stricter, I can't recall an issue the extra strictness would have caught.
And this lets us ship a significant red diff (https://github.com/commaai/opendbc/pull/2521) to car ports.
---
A sample from running `test_models` on this branch:
```bash
0x444 TRACK_14 got 21.00Hz, old 500.00 new 476.20
0x445 TRACK_15 got 21.00Hz, old 500.00 new 476.20
0x156 STEERING_SENSORS got 100.00Hz, old 100.00 new 100.00
0x1A4 VSA_STATUS got 50.99Hz, old 200.00 new 196.10
0x1B0 STANDSTILL got 50.99Hz, old 200.00 new 196.10
0x158 ENGINE_DATA got 100.00Hz, old 100.00 new 100.00
0x17C POWERTRAIN_DATA got 100.00Hz, old 100.00 new 100.00
0x188 GEARBOX_AUTO got 100.00Hz, old 200.00 new 100.00
0x1D0 WHEEL_SPEEDS got …
```
=> CANParser: auto-detect frequency

opendbc/car/docs_definitions.py
```python
Column.VIDEO: self.video or "",  # replaced with an image and link from template in get_column
Column.SETUP_VIDEO: self.setup_video or "",  # replaced with an image and link from template in get_column
```
- `SETUP_VIDEO` [comment](https://github.com/commaai/opendbc/blob/master/opendbc/car/docs_definitions.py#L330) says it should look like `VIDEO` but it shows as text link in current openpilot's [CARS.md](https://github.com/commaai/openpilot/blob/master/docs/CARS.md)
<br>
=> Docs: Add missing Youtube icon to `SETUP_VIDEO`

opendbc/car/hyundai/carstate.py, opendbc/car/toyota/carstate.py, opendbc/car/volkswagen/carstate.py
There are a few warts of the new dynamic CANParser:
* if a message is read conditionally, it will make `canValid` drop to False briefly once it is read  
* longer term, this is fixed by *parsing* all messages in a DBC all the time (pending performance improvements) but only considering them for the `canValid` flag once you've read from it
* VW's variable 1-50Hz messages need manual handling for now; long term solution needs some thought
That being said, I think the line savings are definitely worth the trade-offs (>100 lines gone from Hyundai's carstate.py!).
=> car dynamic parsing fixups

opendbc/dbc/tesla_model3_party.dbc
The new Tesla Model Y Juniper does not include the `IBST_status` message.
`ESP_status` is the same across all vehicles. 
This is likely due to the [new brake system](https://www.teslaoracle.com/2025/03/27/tesla-re-engineers-the-brake-system-in-the-new-model-y-juniper-for-autopilot-and-human-drivers/) implemented in the Juniper.
In a second PR, I would like to replace `IBST_status` with `ESP_status` in carstate and safety to support Tesla Juniper as well.
Validation
* Route: da74b4dc7cea694c/00000001--cdff470bcf
=> Tesla: add ESP Status

opendbc/can/parser.py
Bolt has a loopback CANParser on sent messages which won't be alive until we start sending messages.
=> Fix busTimeout on Chevy Bolt during startup

opendbc/safety/tests/test_elm327.py
Test ELM327 safety with a malformed length GM camera diagnostic address to increase coverage
=> Test: ELM327 GM camera diagnostic address with malformed length

opendbc/dbc/psa_aee2010_r3.dbc
This PR adds DBC for the AEE2010_R3 electronic platform used in 20+ recent models from PSA Group.
Initial platform support PR: #2379
* Dongle ID: 6a7075a4fdd765ee
* Route: 6a7075a4fdd765ee/0000004e--1f612006dd
=> PSA: add DBC for AEE2010_R3 electronic architecture

opendbc/car/honda/hondacan.py, opendbc/dbc/generator/honda/_bosch_adas_2018.dbc, opendbc/dbc/generator/honda/_nidec_common.dbc, opendbc/dbc/generator/honda/honda_civic_ex_2022_can.dbc, opendbc/dbc/generator/honda/honda_common_canfd.dbc
Fix some signal overlaps, "don't know" placeholders overlapping things that were apparently learned later.
The Bosch messages are identical and could be put in a generator template, but I'll take a look at that when we're ready for a round of Bosch DBC consolidation.
=> Honda: Cleanup LKAS_HUD signal overlaps

opendbc/car/honda/carstate.py
Act on the regen paddle signals added in #2622. Resolves occurrences of #1100 with stock ACC.
Leaving that bug open, as some safety refactoring is needed to solve it for alpha OP long.
**Before:** `f39cf149898833ff/0000003e--1fd6c210b4`
**After:** `f39cf149898833ff/0000003f--f8fa7f2c17`
Requires commaai/openpilot#35929.
=> Honda: Disengage stock ACC on regen paddle

opendbc/car/honda/interface.py, opendbc/car/honda/values.py
* Fix ALT_BRAKE detection
* Make EPS and VSA firmware optional for CAN-FD cars
=> Honda: Bosch CAN-FD platform cleanup, part 2

opendbc/car/honda/carstate.py
Reverts commaai/opendbc#2624.
When engaged, this acted correctly to disengage instead of throwing an immediate disengage alert. But when disengaged, if the driver had regen braking active, we'd reject and cancel the first engagement attempt before the platform ACC could disable regen braking on its own.
This wasn't intentional, or a good UX tradeoff, so reverting for release. Will work on a proper fix later.
=> Revert "Honda: Disengage stock ACC on regen paddle"

opendbc/car/volkswagen/fingerprints.py
Add missing engine and transmission firmware for the Passat GTE (PHEV).
**Route:** `bc71d9c2e52736a5/0000000e--314c232038`
=> VW MQB: Add FW for 2017 Volkswagen Passat GTE

opendbc/car/honda/fingerprints.py, opendbc/car/honda/interface.py
We removed the mod from our Civic a while ago and are choosing to no longer support this in stock openpilot at this time.
Our [blog post](https://blog.comma.ai/safer-control-of-steering/) on this is still relevant.
=> Honda: remove EPS mod support

opendbc/car/nissan/fingerprints.py
Validation
* Dongle ID: 74c81c1645dda5fd
* Route: 74c81c1645dda5fd/00000000--c4f4545110
All Log Files
[74c81c1645dda5fd_00000000--c4f4545110--0--rlog.zst.zip](https://github.com/user-attachments/files/21820189/74c81c1645dda5fd_00000000--c4f4545110--0--rlog.zst.zip)
Model: Nissan Leaf 2021 UK
=> Nissan: add new fingerprint for Nissan Leaf 2021 UK 

opendbc/car/honda/interface.py, opendbc/car/honda/values.py
Picked from #2687.
* New cars will default to the lateral acceleration torque controller
* Changes Accord 11G steer actuator delay slightly, should be immaterial with lagd
* Move the tire stiffness comment to where tire stiffness data is now kept
* Whitespace cleanup
=> Honda: Interface refactor, part 1

opendbc/car/tests/routes.py
The current test route is using older firmware which only shows 6 bytes but newer vehicle firmwares show 8 bytes for the message sizes on the bus for certain messages including the display message for current touch points on display, which is used  by certain forks.
This new route is on newer firmware which has the correct 8 bytes per message for these specific messages which should fix the failing tests downstream.
Validation
* Dongle ID: c8a98e58647765ad
* Route: https://connect.comma.ai/c8a98e58647765ad/00000002--84e4746136
Note: This route is not mine directly, it was provided by @incodemines
This fixes #2698
=> Tesla: Replace 6 byte Model Y test route

opendbc/dbc/generator/honda/_steering_control_b.dbc, opendbc/dbc/generator/honda/acura_rdx_2018_can.dbc, opendbc/dbc/generator/honda/honda_crv_executive_2016_can.dbc, opendbc/dbc/generator/honda/honda_crv_touring_2016_can.dbc
Clean up and consolidate the length 6 variants, and add some new fault enums.
There was one difference in the very oldest DBC, treating `STEER_ANGLE_RATE` as `STEER_MOTOR_TORQUE` which disagrees with every other Honda DBC. This would be easy to confuse during early reverse engineering. I'm cleaning this up without specific validation, but openpilot doesn't make use of this signal anyway. It uses the angle-rate from `STEERING_SENSORS` and doesn't read EPS motor torque at all anymore.
=> Honda: Steer control status refactor, part 2

opendbc/car/honda/fingerprints.py
I figured out how to test and it is working on open pilot 0.10:
fe2ba9751305fd5a/00000002--d160f9a2ca
Canadian model Acura ILX 2018 Premium Tech
Validation
* Dongle ID:  fe2ba9751305fd5a
* Route:  00000002--d160f9a2ca
=> Honda: Add FW for 2018 Acura ILX

docs/CARS.md, opendbc/car/tesla/values.py
Per @incodemines, there should have been a doc update when fixing #2698.
=> Tesla: Extend supported model-years for HW4 Model Y

opendbc/car/honda/carcontroller.py, opendbc/car/honda/values.py
Garbage-collect dead code: none of the `acc_alert` cases were actually sent to any car. This could be leftover from many years ago when we stopped triggering sound-generating alerts on the car.
=> Honda: Refactor HUD alerts

opendbc/car/honda/carcontroller.py, opendbc/car/honda/hondacan.py
Null effect refactor, prep for #2473 or its spiritual successor.
`create_ui_commands()` is too big, it builds up to five messages, the argument list is unwieldy, and the LKAS_HUD message is about to get more arguments.
* Break `create_ui_commands()` into several pieces.
* Start moving more of the bus and car logic up into carcontroller
=> Honda: Refactor create_ui_commands

opendbc/car/honda/carstate.py
Prerequisite for merging Honda ALT_RADAR cars.
As of this writing, this alert will only affect the recently-merged Honda City. The rest of the cars with non-zero minimum steer speeds are all set on CarDocs only.
=> Honda: Static minimum steer speed handling

pyproject.toml
Pipelines broke since last night https://github.com/commaai/opendbc/actions/runs/17701582104/job/50307962453 
(also seen in sunnypilot) due to a pycapnp update from `2.1.0` to `2.2.0`, this pins so we are back to "working order" but probably we should embrace the change? i'm unfamiliar with the change tho.
=> CI: bugfix of tests by pinning pycapnp to 2.1.0

opendbc/car/honda/carcontroller.py, opendbc/car/honda/hondacan.py, opendbc/car/honda/interface.py, opendbc/car/honda/values.py
Resurrect the support pieces of #2104, which was backed out in #2240.
The change itself works great, on the cars where it works, what remains is to establish the set of cars it works on.
=> Honda: Support for Traffic Jam Assist steering control bit

opendbc/dbc/vw_mqb.dbc
This PR adds missing AWV signals for VW MQB in the ACC_10 message, these signals are used for the `AWA` function which is apart of the `AWV` function, and provides Evasive Steering Assistance as apart of the Front Assist package by using the signals added in this PR to command steering to the EPS, it is important to note this is only a DBC edit, as for the EPS to accept these signals it needs to be parameterized by ODIS to support `AWA`. 
`AWA` = `Ausweichassistent` = `Evasive Steering Assistant`
=> VW MQB: Add missing AWV (ACC_10) & LH_EPS_03 Signals
